#!/bin/bash
# Extract DDL statements from PostgreSQL dump files for sqlc schema files
#
# Extracts: CREATE TABLE, ALTER TABLE (IDENTITY, PRIMARY KEY)
# Skips: COMMENT, SET, SELECT, OWNER TO, atlas_schema_revisions
#
# Usage:
#   ./scripts/db/extract-sqlc-schema-postgres.sh <schema_name> <dump_file> <output_file>
#
# Example:
#   ./scripts/db/extract-sqlc-schema-postgres.sh watch data/dump/sql/dump_watch.pg.sql tools/sqlc/schemas/postgres/01_watch.sql

set -euo pipefail

if [ $# -ne 3 ]; then
	echo "Usage: $0 <schema_name> <dump_file> <output_file>" >&2
	echo "" >&2
	echo "Extracts DDL statements from PostgreSQL dump file and formats them for sqlc." >&2
	echo "" >&2
	echo "Arguments:" >&2
	echo "  schema_name  Schema name (watch, keygen, or sign)" >&2
	echo "  dump_file    Path to PostgreSQL dump file" >&2
	echo "  output_file  Path to output sqlc schema file" >&2
	exit 1
fi

SCHEMA_NAME="$1"
DUMP_FILE="$2"
OUTPUT_FILE="$3"

if [ ! -f "$DUMP_FILE" ]; then
	echo "Error: Dump file not found: $DUMP_FILE" >&2
	exit 1
fi

# Create output directory if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Write header with DO NOT EDIT comment
echo "-- Code generated by \`make extract-sqlc-schema-postgres-${SCHEMA_NAME}\`. DO NOT EDIT." >"$OUTPUT_FILE"
echo "-- Extracted from $(basename "$DUMP_FILE")" >>"$OUTPUT_FILE"
echo "" >>"$OUTPUT_FILE"

# Determine which tables to exclude based on schema
# - atlas_schema_revisions: excluded from all schemas (not needed for sqlc)
# - seed: excluded from sign schema (exists in keygen, avoid duplication)
# - musig2_nonces: excluded from sign schema (exists in keygen, avoid duplication)
EXCLUDE_PATTERNS="atlas_schema_revisions"
if [ "$SCHEMA_NAME" = "sign" ]; then
	EXCLUDE_PATTERNS="$EXCLUDE_PATTERNS|seed|musig2_nonces"
fi

# Extract DDL statements, excluding specified tables
# This awk script handles:
# 1. CREATE TABLE blocks (multi-line, ending with ';')
# 2. ALTER TABLE ... ADD GENERATED BY DEFAULT AS IDENTITY blocks (multi-line, ending with ');')
# 3. ALTER TABLE ONLY ... ADD CONSTRAINT ... PRIMARY KEY statements (2 lines)
# All are subject to the same exclude pattern filtering
awk -v exclude_patterns="$EXCLUDE_PATTERNS" '
BEGIN {
    skip = 0
    in_block = 0
    # Split exclude patterns by | and create array
    split(exclude_patterns, patterns, "|")
}

# Function to check if a line matches any exclude pattern
function is_excluded(line) {
    for (i in patterns) {
        if (line ~ patterns[i]) {
            return 1
        }
    }
    return 0
}

{
    # Handle CREATE TABLE start
    if (/^CREATE TABLE/) {
        if (is_excluded($0)) {
            skip = 1
            in_block = 1
            next
        } else {
            skip = 0
            in_block = 1
            print
            next
        }
    }

    # Handle ALTER TABLE ... IDENTITY start (multi-line block)
    # Pattern: ALTER TABLE public.<table> ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    if (/^ALTER TABLE .* ALTER COLUMN .* ADD GENERATED BY DEFAULT AS IDENTITY/) {
        if (is_excluded($0)) {
            skip = 1
            in_block = 1
            next
        } else {
            skip = 0
            in_block = 1
            print
            next
        }
    }

    # Handle ALTER TABLE ONLY ... PRIMARY KEY (2-line block)
    # Pattern: ALTER TABLE ONLY public.<table>
    #     ADD CONSTRAINT <name> PRIMARY KEY (<col>);
    if (/^ALTER TABLE ONLY/) {
        if (is_excluded($0)) {
            skip = 1
            in_block = 1
            next
        } else {
            skip = 0
            in_block = 1
            print
            next
        }
    }

    # Handle end of block (any block type ends with ; at end of line)
    if (skip && /;$/) {
        skip = 0
        in_block = 0
        next
    }

    # Skip lines when skip flag is set
    if (skip) {
        next
    }

    # Print lines within block
    if (in_block) {
        print
        if (/;$/) {
            print ""
            in_block = 0
        }
    }
}
' "$DUMP_FILE" |
	# Clean up formatting for sqlc:
	# - Remove SET statements (PostgreSQL session config)
	# - Remove SELECT statements (PostgreSQL extensions)
	# - Remove comment-only lines (PostgreSQL dump comments)
	# - Remove empty comment lines
	# - Remove ALTER TABLE ... OWNER TO lines
	# - Remove public. schema prefix (sqlc prefers without)
	sed -E \
		-e '/^SET /d' \
		-e '/^SELECT /d' \
		-e '/^-- Dumped from/d' \
		-e '/^-- Dumped by/d' \
		-e '/^-- PostgreSQL/d' \
		-e '/^-- Name:/d' \
		-e '/^-- TOC/d' \
		-e '/^ALTER TABLE .* OWNER TO/d' \
		-e 's/public\.//g' \
		-e '/^--$/d' \
		>>"$OUTPUT_FILE"

echo "Extracted schema written to: $OUTPUT_FILE" >&2
