#!/bin/bash
# Generate composite SQLite schemas for E2E testing
#
# SQLC merges all schema files via glob (*.sql), so shared tables like `seed`
# and `musig2_nonces` can only exist in one file (02_keygen.sql). However,
# E2E initialization loads one schema file per wallet, and the sign wallet
# also needs these shared tables at runtime.
#
# This script generates per-wallet composite schemas in a subdirectory (e2e/)
# that SQLC's glob does not reach, ensuring:
# - No duplicate tables in SQLC codegen
# - Each wallet's E2E database has all required tables
#
# Usage:
#   ./scripts/db/generate-e2e-sqlite-schemas.sh
#
# Output:
#   tools/sqlc/schemas/sqlite/e2e/01_watch.sql
#   tools/sqlc/schemas/sqlite/e2e/02_keygen.sql
#   tools/sqlc/schemas/sqlite/e2e/03_sign.sql

set -euo pipefail

# Resolve project root (script is at scripts/db/)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

SQLC_SCHEMA_DIR="${PROJECT_ROOT}/tools/sqlc/schemas/sqlite"
E2E_SCHEMA_DIR="${SQLC_SCHEMA_DIR}/e2e"

WATCH_SCHEMA="${SQLC_SCHEMA_DIR}/01_watch.sql"
KEYGEN_SCHEMA="${SQLC_SCHEMA_DIR}/02_keygen.sql"
SIGN_SCHEMA="${SQLC_SCHEMA_DIR}/03_sign.sql"

HEADER="-- Code generated by \`generate-e2e-sqlite-schemas.sh\`. DO NOT EDIT."

# Tables to extract from keygen schema and add to sign schema.
# These tables are shared between keygen and sign wallets at runtime,
# but live only in 02_keygen.sql for SQLC codegen to avoid duplicates.
SHARED_TABLES=("seed" "musig2_nonces")

# Extract a CREATE TABLE block from a SQLite schema file.
# SQLite CREATE TABLE blocks start with "CREATE TABLE <name>" and end with ");".
# Args: $1 = table name, $2 = source file
extract_table() {
	local table_name="$1"
	local source_file="$2"

	awk -v table="$table_name" '
	BEGIN { found = 0 }
	$0 ~ "^CREATE TABLE " table " \\(" {
		found = 1
	}
	found {
		print
		if (/\);/) {
			found = 0
		}
	}
	' "$source_file"
}

# Validate source schemas exist
for schema in "$WATCH_SCHEMA" "$KEYGEN_SCHEMA" "$SIGN_SCHEMA"; do
	if [ ! -f "$schema" ]; then
		echo "Error: Source schema not found: $schema" >&2
		echo "Run 'make generate-sqlite-schema' first." >&2
		exit 1
	fi
done

# Create output directory
mkdir -p "$E2E_SCHEMA_DIR"

# Watch: copy as-is (self-contained)
{
	echo "$HEADER"
	echo "-- Source: 01_watch.sql"
	echo ""
	cat "$WATCH_SCHEMA" | grep -v "^-- Code generated by"
} >"${E2E_SCHEMA_DIR}/01_watch.sql"

# Keygen: copy as-is (self-contained)
{
	echo "$HEADER"
	echo "-- Source: 02_keygen.sql"
	echo ""
	cat "$KEYGEN_SCHEMA" | grep -v "^-- Code generated by"
} >"${E2E_SCHEMA_DIR}/02_keygen.sql"

# Sign: base schema + shared tables from keygen
{
	echo "$HEADER"
	echo "-- Source: 03_sign.sql + shared tables (${SHARED_TABLES[*]}) from 02_keygen.sql"
	echo ""
	cat "$SIGN_SCHEMA" | grep -v "^-- Code generated by"
	echo ""
	echo "-- Shared tables (from 02_keygen.sql, needed by sign wallet at runtime)"
	for table in "${SHARED_TABLES[@]}"; do
		echo ""
		extract_table "$table" "$KEYGEN_SCHEMA"
	done
} >"${E2E_SCHEMA_DIR}/03_sign.sql"

echo "E2E SQLite schemas generated in: ${E2E_SCHEMA_DIR}/" >&2
echo "  01_watch.sql  (copy of watch schema)" >&2
echo "  02_keygen.sql (copy of keygen schema)" >&2
echo "  03_sign.sql   (sign + ${SHARED_TABLES[*]} from keygen)" >&2
