package imports

import (
	"context"
	"errors"
	"fmt"

	keygenusecase "github.com/hiromaily/go-crypto-wallet/internal/application/usecase/keygen"
	"github.com/hiromaily/go-crypto-wallet/internal/di"
)

func runFullPubKey(container di.Container, fileName string) error {
	fmt.Println("import full pubkey key generated by sign wallet")

	// validator
	if fileName == "" {
		return errors.New("file option [-file] is required")
	}

	// import generated private key to keygen wallet
	useCase := container.NewKeygenImportFullPubkeyUseCase()
	err := useCase.Import(context.Background(), keygenusecase.ImportFullPubkeyInput{
		FileName: fileName,
	})
	if err != nil {
		return fmt.Errorf("fail to import full pubkey: %w", err)
	}
	fmt.Println("Done!")

	return nil
}
