package imports

import (
	"github.com/spf13/cobra"

	"github.com/hiromaily/go-crypto-wallet/internal/di"
	wallets "github.com/hiromaily/go-crypto-wallet/internal/interface-adapters/wallet"
)

// AddCommands adds all import subcommands
func AddCommands(parentCmd *cobra.Command, wallet *wallets.Keygener, container di.Container) {
	// privkey command
	var privkeyAccount string
	privkeyCmd := &cobra.Command{
		Use:   "privkey",
		Short: "import generated private key in database to keygen wallet",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runPrivKey(container, privkeyAccount)
		},
	}
	privkeyCmd.Flags().StringVar(&privkeyAccount, "account", "", "target account")
	parentCmd.AddCommand(privkeyCmd)

	// fullpubkey command
	var fullpubkeyFile string
	fullpubkeyCmd := &cobra.Command{
		Use:   "fullpubkey",
		Short: "import full pubkey key generated by sign wallet",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runFullPubKey(container, fullpubkeyFile)
		},
	}
	fullpubkeyCmd.Flags().StringVar(&fullpubkeyFile, "file", "", "full-pubkey file path")
	parentCmd.AddCommand(fullpubkeyCmd)
}
