// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hiromaily/go-crypto-wallet/pkg/chains/xrp/xrplgo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionSubmitter creates a new instance of MockTransactionSubmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionSubmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionSubmitter {
	mock := &MockTransactionSubmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionSubmitter is an autogenerated mock type for the TransactionSubmitter type
type MockTransactionSubmitter struct {
	mock.Mock
}

type MockTransactionSubmitter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionSubmitter) EXPECT() *MockTransactionSubmitter_Expecter {
	return &MockTransactionSubmitter_Expecter{mock: &_m.Mock}
}

// GetTransaction provides a mock function for the type MockTransactionSubmitter
func (_mock *MockTransactionSubmitter) GetTransaction(ctx context.Context, txID string, targetLedgerVersion uint64) (*xrplgo.TxInfo, error) {
	ret := _mock.Called(ctx, txID, targetLedgerVersion)

	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}

	var r0 *xrplgo.TxInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64) (*xrplgo.TxInfo, error)); ok {
		return returnFunc(ctx, txID, targetLedgerVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64) *xrplgo.TxInfo); ok {
		r0 = returnFunc(ctx, txID, targetLedgerVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*xrplgo.TxInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64) error); ok {
		r1 = returnFunc(ctx, txID, targetLedgerVersion)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionSubmitter_GetTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransaction'
type MockTransactionSubmitter_GetTransaction_Call struct {
	*mock.Call
}

// GetTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - txID string
//   - targetLedgerVersion uint64
func (_e *MockTransactionSubmitter_Expecter) GetTransaction(ctx interface{}, txID interface{}, targetLedgerVersion interface{}) *MockTransactionSubmitter_GetTransaction_Call {
	return &MockTransactionSubmitter_GetTransaction_Call{Call: _e.mock.On("GetTransaction", ctx, txID, targetLedgerVersion)}
}

func (_c *MockTransactionSubmitter_GetTransaction_Call) Run(run func(ctx context.Context, txID string, targetLedgerVersion uint64)) *MockTransactionSubmitter_GetTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionSubmitter_GetTransaction_Call) Return(txInfo *xrplgo.TxInfo, err error) *MockTransactionSubmitter_GetTransaction_Call {
	_c.Call.Return(txInfo, err)
	return _c
}

func (_c *MockTransactionSubmitter_GetTransaction_Call) RunAndReturn(run func(ctx context.Context, txID string, targetLedgerVersion uint64) (*xrplgo.TxInfo, error)) *MockTransactionSubmitter_GetTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitTransaction provides a mock function for the type MockTransactionSubmitter
func (_mock *MockTransactionSubmitter) SubmitTransaction(ctx context.Context, signedTx string) (*xrplgo.SentTx, uint64, error) {
	ret := _mock.Called(ctx, signedTx)

	if len(ret) == 0 {
		panic("no return value specified for SubmitTransaction")
	}

	var r0 *xrplgo.SentTx
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*xrplgo.SentTx, uint64, error)); ok {
		return returnFunc(ctx, signedTx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *xrplgo.SentTx); ok {
		r0 = returnFunc(ctx, signedTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*xrplgo.SentTx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) uint64); ok {
		r1 = returnFunc(ctx, signedTx)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, signedTx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTransactionSubmitter_SubmitTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitTransaction'
type MockTransactionSubmitter_SubmitTransaction_Call struct {
	*mock.Call
}

// SubmitTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - signedTx string
func (_e *MockTransactionSubmitter_Expecter) SubmitTransaction(ctx interface{}, signedTx interface{}) *MockTransactionSubmitter_SubmitTransaction_Call {
	return &MockTransactionSubmitter_SubmitTransaction_Call{Call: _e.mock.On("SubmitTransaction", ctx, signedTx)}
}

func (_c *MockTransactionSubmitter_SubmitTransaction_Call) Run(run func(ctx context.Context, signedTx string)) *MockTransactionSubmitter_SubmitTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionSubmitter_SubmitTransaction_Call) Return(sentTx *xrplgo.SentTx, v uint64, err error) *MockTransactionSubmitter_SubmitTransaction_Call {
	_c.Call.Return(sentTx, v, err)
	return _c
}

func (_c *MockTransactionSubmitter_SubmitTransaction_Call) RunAndReturn(run func(ctx context.Context, signedTx string) (*xrplgo.SentTx, uint64, error)) *MockTransactionSubmitter_SubmitTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// WaitValidation provides a mock function for the type MockTransactionSubmitter
func (_mock *MockTransactionSubmitter) WaitValidation(ctx context.Context, targetLedgerVersion uint64) (uint64, error) {
	ret := _mock.Called(ctx, targetLedgerVersion)

	if len(ret) == 0 {
		panic("no return value specified for WaitValidation")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (uint64, error)); ok {
		return returnFunc(ctx, targetLedgerVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) uint64); ok {
		r0 = returnFunc(ctx, targetLedgerVersion)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, targetLedgerVersion)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionSubmitter_WaitValidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitValidation'
type MockTransactionSubmitter_WaitValidation_Call struct {
	*mock.Call
}

// WaitValidation is a helper method to define mock.On call
//   - ctx context.Context
//   - targetLedgerVersion uint64
func (_e *MockTransactionSubmitter_Expecter) WaitValidation(ctx interface{}, targetLedgerVersion interface{}) *MockTransactionSubmitter_WaitValidation_Call {
	return &MockTransactionSubmitter_WaitValidation_Call{Call: _e.mock.On("WaitValidation", ctx, targetLedgerVersion)}
}

func (_c *MockTransactionSubmitter_WaitValidation_Call) Run(run func(ctx context.Context, targetLedgerVersion uint64)) *MockTransactionSubmitter_WaitValidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionSubmitter_WaitValidation_Call) Return(v uint64, err error) *MockTransactionSubmitter_WaitValidation_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockTransactionSubmitter_WaitValidation_Call) RunAndReturn(run func(ctx context.Context, targetLedgerVersion uint64) (uint64, error)) *MockTransactionSubmitter_WaitValidation_Call {
	_c.Call.Return(run)
	return _c
}
