// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	xrp0 "github.com/hiromaily/go-crypto-wallet/internal/application/dto/xrp"
	"github.com/hiromaily/go-crypto-wallet/internal/application/ports/api/xrp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSignerListPreparer creates a new instance of MockSignerListPreparer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSignerListPreparer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSignerListPreparer {
	mock := &MockSignerListPreparer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSignerListPreparer is an autogenerated mock type for the SignerListPreparer type
type MockSignerListPreparer struct {
	mock.Mock
}

type MockSignerListPreparer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSignerListPreparer) EXPECT() *MockSignerListPreparer_Expecter {
	return &MockSignerListPreparer_Expecter{mock: &_m.Mock}
}

// PrepareSignerListSetTransaction provides a mock function for the type MockSignerListPreparer
func (_mock *MockSignerListPreparer) PrepareSignerListSetTransaction(ctx context.Context, senderAccount string, signerQuorum uint32, signerEntries []xrp.SignerEntryInput, instructions *xrp0.Instructions) (*xrp0.SignerListSetTxInput, string, error) {
	ret := _mock.Called(ctx, senderAccount, signerQuorum, signerEntries, instructions)

	if len(ret) == 0 {
		panic("no return value specified for PrepareSignerListSetTransaction")
	}

	var r0 *xrp0.SignerListSetTxInput
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint32, []xrp.SignerEntryInput, *xrp0.Instructions) (*xrp0.SignerListSetTxInput, string, error)); ok {
		return returnFunc(ctx, senderAccount, signerQuorum, signerEntries, instructions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint32, []xrp.SignerEntryInput, *xrp0.Instructions) *xrp0.SignerListSetTxInput); ok {
		r0 = returnFunc(ctx, senderAccount, signerQuorum, signerEntries, instructions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*xrp0.SignerListSetTxInput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint32, []xrp.SignerEntryInput, *xrp0.Instructions) string); ok {
		r1 = returnFunc(ctx, senderAccount, signerQuorum, signerEntries, instructions)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, uint32, []xrp.SignerEntryInput, *xrp0.Instructions) error); ok {
		r2 = returnFunc(ctx, senderAccount, signerQuorum, signerEntries, instructions)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSignerListPreparer_PrepareSignerListSetTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareSignerListSetTransaction'
type MockSignerListPreparer_PrepareSignerListSetTransaction_Call struct {
	*mock.Call
}

// PrepareSignerListSetTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - senderAccount string
//   - signerQuorum uint32
//   - signerEntries []xrp.SignerEntryInput
//   - instructions *xrp0.Instructions
func (_e *MockSignerListPreparer_Expecter) PrepareSignerListSetTransaction(ctx interface{}, senderAccount interface{}, signerQuorum interface{}, signerEntries interface{}, instructions interface{}) *MockSignerListPreparer_PrepareSignerListSetTransaction_Call {
	return &MockSignerListPreparer_PrepareSignerListSetTransaction_Call{Call: _e.mock.On("PrepareSignerListSetTransaction", ctx, senderAccount, signerQuorum, signerEntries, instructions)}
}

func (_c *MockSignerListPreparer_PrepareSignerListSetTransaction_Call) Run(run func(ctx context.Context, senderAccount string, signerQuorum uint32, signerEntries []xrp.SignerEntryInput, instructions *xrp0.Instructions)) *MockSignerListPreparer_PrepareSignerListSetTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		var arg3 []xrp.SignerEntryInput
		if args[3] != nil {
			arg3 = args[3].([]xrp.SignerEntryInput)
		}
		var arg4 *xrp0.Instructions
		if args[4] != nil {
			arg4 = args[4].(*xrp0.Instructions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSignerListPreparer_PrepareSignerListSetTransaction_Call) Return(signerListSetTxInput *xrp0.SignerListSetTxInput, s string, err error) *MockSignerListPreparer_PrepareSignerListSetTransaction_Call {
	_c.Call.Return(signerListSetTxInput, s, err)
	return _c
}

func (_c *MockSignerListPreparer_PrepareSignerListSetTransaction_Call) RunAndReturn(run func(ctx context.Context, senderAccount string, signerQuorum uint32, signerEntries []xrp.SignerEntryInput, instructions *xrp0.Instructions) (*xrp0.SignerListSetTxInput, string, error)) *MockSignerListPreparer_PrepareSignerListSetTransaction_Call {
	_c.Call.Return(run)
	return _c
}
