// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hiromaily/go-crypto-wallet/internal/application/dto/xrp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionPreparer creates a new instance of MockTransactionPreparer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionPreparer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionPreparer {
	mock := &MockTransactionPreparer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionPreparer is an autogenerated mock type for the TransactionPreparer type
type MockTransactionPreparer struct {
	mock.Mock
}

type MockTransactionPreparer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionPreparer) EXPECT() *MockTransactionPreparer_Expecter {
	return &MockTransactionPreparer_Expecter{mock: &_m.Mock}
}

// CreateRawTransaction provides a mock function for the type MockTransactionPreparer
func (_mock *MockTransactionPreparer) CreateRawTransaction(ctx context.Context, senderAccount string, receiverAccount string, amount float64, instructions *xrp.Instructions) (*xrp.TxInput, string, error) {
	ret := _mock.Called(ctx, senderAccount, receiverAccount, amount, instructions)

	if len(ret) == 0 {
		panic("no return value specified for CreateRawTransaction")
	}

	var r0 *xrp.TxInput
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, float64, *xrp.Instructions) (*xrp.TxInput, string, error)); ok {
		return returnFunc(ctx, senderAccount, receiverAccount, amount, instructions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, float64, *xrp.Instructions) *xrp.TxInput); ok {
		r0 = returnFunc(ctx, senderAccount, receiverAccount, amount, instructions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*xrp.TxInput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, float64, *xrp.Instructions) string); ok {
		r1 = returnFunc(ctx, senderAccount, receiverAccount, amount, instructions)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, float64, *xrp.Instructions) error); ok {
		r2 = returnFunc(ctx, senderAccount, receiverAccount, amount, instructions)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTransactionPreparer_CreateRawTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRawTransaction'
type MockTransactionPreparer_CreateRawTransaction_Call struct {
	*mock.Call
}

// CreateRawTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - senderAccount string
//   - receiverAccount string
//   - amount float64
//   - instructions *xrp.Instructions
func (_e *MockTransactionPreparer_Expecter) CreateRawTransaction(ctx interface{}, senderAccount interface{}, receiverAccount interface{}, amount interface{}, instructions interface{}) *MockTransactionPreparer_CreateRawTransaction_Call {
	return &MockTransactionPreparer_CreateRawTransaction_Call{Call: _e.mock.On("CreateRawTransaction", ctx, senderAccount, receiverAccount, amount, instructions)}
}

func (_c *MockTransactionPreparer_CreateRawTransaction_Call) Run(run func(ctx context.Context, senderAccount string, receiverAccount string, amount float64, instructions *xrp.Instructions)) *MockTransactionPreparer_CreateRawTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		var arg4 *xrp.Instructions
		if args[4] != nil {
			arg4 = args[4].(*xrp.Instructions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTransactionPreparer_CreateRawTransaction_Call) Return(txInput *xrp.TxInput, s string, err error) *MockTransactionPreparer_CreateRawTransaction_Call {
	_c.Call.Return(txInput, s, err)
	return _c
}

func (_c *MockTransactionPreparer_CreateRawTransaction_Call) RunAndReturn(run func(ctx context.Context, senderAccount string, receiverAccount string, amount float64, instructions *xrp.Instructions) (*xrp.TxInput, string, error)) *MockTransactionPreparer_CreateRawTransaction_Call {
	_c.Call.Return(run)
	return _c
}
