// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hiromaily/go-crypto-wallet/internal/application/dto/ripple"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRippleAdminer creates a new instance of MockRippleAdminer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRippleAdminer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRippleAdminer {
	mock := &MockRippleAdminer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRippleAdminer is an autogenerated mock type for the RippleAdminer type
type MockRippleAdminer struct {
	mock.Mock
}

type MockRippleAdminer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRippleAdminer) EXPECT() *MockRippleAdminer_Expecter {
	return &MockRippleAdminer_Expecter{mock: &_m.Mock}
}

// ValidationCreate provides a mock function for the type MockRippleAdminer
func (_mock *MockRippleAdminer) ValidationCreate(ctx context.Context, secret string) (*ripple.ResponseValidationCreate, error) {
	ret := _mock.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for ValidationCreate")
	}

	var r0 *ripple.ResponseValidationCreate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ripple.ResponseValidationCreate, error)); ok {
		return returnFunc(ctx, secret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ripple.ResponseValidationCreate); ok {
		r0 = returnFunc(ctx, secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ripple.ResponseValidationCreate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, secret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRippleAdminer_ValidationCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidationCreate'
type MockRippleAdminer_ValidationCreate_Call struct {
	*mock.Call
}

// ValidationCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - secret string
func (_e *MockRippleAdminer_Expecter) ValidationCreate(ctx interface{}, secret interface{}) *MockRippleAdminer_ValidationCreate_Call {
	return &MockRippleAdminer_ValidationCreate_Call{Call: _e.mock.On("ValidationCreate", ctx, secret)}
}

func (_c *MockRippleAdminer_ValidationCreate_Call) Run(run func(ctx context.Context, secret string)) *MockRippleAdminer_ValidationCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRippleAdminer_ValidationCreate_Call) Return(responseValidationCreate *ripple.ResponseValidationCreate, err error) *MockRippleAdminer_ValidationCreate_Call {
	_c.Call.Return(responseValidationCreate, err)
	return _c
}

func (_c *MockRippleAdminer_ValidationCreate_Call) RunAndReturn(run func(ctx context.Context, secret string) (*ripple.ResponseValidationCreate, error)) *MockRippleAdminer_ValidationCreate_Call {
	_c.Call.Return(run)
	return _c
}

// WalletPropose provides a mock function for the type MockRippleAdminer
func (_mock *MockRippleAdminer) WalletPropose(ctx context.Context, passphrase string) (*ripple.ResponseWalletPropose, error) {
	ret := _mock.Called(ctx, passphrase)

	if len(ret) == 0 {
		panic("no return value specified for WalletPropose")
	}

	var r0 *ripple.ResponseWalletPropose
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ripple.ResponseWalletPropose, error)); ok {
		return returnFunc(ctx, passphrase)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ripple.ResponseWalletPropose); ok {
		r0 = returnFunc(ctx, passphrase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ripple.ResponseWalletPropose)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, passphrase)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRippleAdminer_WalletPropose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalletPropose'
type MockRippleAdminer_WalletPropose_Call struct {
	*mock.Call
}

// WalletPropose is a helper method to define mock.On call
//   - ctx context.Context
//   - passphrase string
func (_e *MockRippleAdminer_Expecter) WalletPropose(ctx interface{}, passphrase interface{}) *MockRippleAdminer_WalletPropose_Call {
	return &MockRippleAdminer_WalletPropose_Call{Call: _e.mock.On("WalletPropose", ctx, passphrase)}
}

func (_c *MockRippleAdminer_WalletPropose_Call) Run(run func(ctx context.Context, passphrase string)) *MockRippleAdminer_WalletPropose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRippleAdminer_WalletPropose_Call) Return(responseWalletPropose *ripple.ResponseWalletPropose, err error) *MockRippleAdminer_WalletPropose_Call {
	_c.Call.Return(responseWalletPropose, err)
	return _c
}

func (_c *MockRippleAdminer_WalletPropose_Call) RunAndReturn(run func(ctx context.Context, passphrase string) (*ripple.ResponseWalletPropose, error)) *MockRippleAdminer_WalletPropose_Call {
	_c.Call.Return(run)
	return _c
}

// WalletProposeWithKey provides a mock function for the type MockRippleAdminer
func (_mock *MockRippleAdminer) WalletProposeWithKey(ctx context.Context, seed string, keyType ripple.XRPKeyType) (*ripple.ResponseWalletPropose, error) {
	ret := _mock.Called(ctx, seed, keyType)

	if len(ret) == 0 {
		panic("no return value specified for WalletProposeWithKey")
	}

	var r0 *ripple.ResponseWalletPropose
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ripple.XRPKeyType) (*ripple.ResponseWalletPropose, error)); ok {
		return returnFunc(ctx, seed, keyType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ripple.XRPKeyType) *ripple.ResponseWalletPropose); ok {
		r0 = returnFunc(ctx, seed, keyType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ripple.ResponseWalletPropose)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ripple.XRPKeyType) error); ok {
		r1 = returnFunc(ctx, seed, keyType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRippleAdminer_WalletProposeWithKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalletProposeWithKey'
type MockRippleAdminer_WalletProposeWithKey_Call struct {
	*mock.Call
}

// WalletProposeWithKey is a helper method to define mock.On call
//   - ctx context.Context
//   - seed string
//   - keyType ripple.XRPKeyType
func (_e *MockRippleAdminer_Expecter) WalletProposeWithKey(ctx interface{}, seed interface{}, keyType interface{}) *MockRippleAdminer_WalletProposeWithKey_Call {
	return &MockRippleAdminer_WalletProposeWithKey_Call{Call: _e.mock.On("WalletProposeWithKey", ctx, seed, keyType)}
}

func (_c *MockRippleAdminer_WalletProposeWithKey_Call) Run(run func(ctx context.Context, seed string, keyType ripple.XRPKeyType)) *MockRippleAdminer_WalletProposeWithKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ripple.XRPKeyType
		if args[2] != nil {
			arg2 = args[2].(ripple.XRPKeyType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRippleAdminer_WalletProposeWithKey_Call) Return(responseWalletPropose *ripple.ResponseWalletPropose, err error) *MockRippleAdminer_WalletProposeWithKey_Call {
	_c.Call.Return(responseWalletPropose, err)
	return _c
}

func (_c *MockRippleAdminer_WalletProposeWithKey_Call) RunAndReturn(run func(ctx context.Context, seed string, keyType ripple.XRPKeyType) (*ripple.ResponseWalletPropose, error)) *MockRippleAdminer_WalletProposeWithKey_Call {
	_c.Call.Return(run)
	return _c
}
