// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: btc_tx.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteAllBtcTx = `-- name: DeleteAllBtcTx :execresult
DELETE FROM btc_tx
`

func (q *Queries) DeleteAllBtcTx(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAllBtcTx)
}

const getBtcTxByID = `-- name: GetBtcTxByID :one
SELECT id, coin, action, unsigned_hex_tx, signed_hex_tx, sent_hash_tx, total_input_amount, total_output_amount, fee, current_tx_type, unsigned_updated_at, sent_updated_at FROM btc_tx
WHERE id = $1
`

func (q *Queries) GetBtcTxByID(ctx context.Context, id int64) (BtcTx, error) {
	row := q.db.QueryRowContext(ctx, getBtcTxByID, id)
	var i BtcTx
	err := row.Scan(
		&i.ID,
		&i.Coin,
		&i.Action,
		&i.UnsignedHexTx,
		&i.SignedHexTx,
		&i.SentHashTx,
		&i.TotalInputAmount,
		&i.TotalOutputAmount,
		&i.Fee,
		&i.CurrentTxType,
		&i.UnsignedUpdatedAt,
		&i.SentUpdatedAt,
	)
	return i, err
}

const getBtcTxCountByUnsignedHex = `-- name: GetBtcTxCountByUnsignedHex :one
SELECT COUNT(*) as count FROM btc_tx
WHERE coin = $1 AND action = $2 AND unsigned_hex_tx = $3
`

type GetBtcTxCountByUnsignedHexParams struct {
	Coin          interface{}
	Action        interface{}
	UnsignedHexTx string
}

func (q *Queries) GetBtcTxCountByUnsignedHex(ctx context.Context, arg GetBtcTxCountByUnsignedHexParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBtcTxCountByUnsignedHex, arg.Coin, arg.Action, arg.UnsignedHexTx)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBtcTxIDBySentHash = `-- name: GetBtcTxIDBySentHash :one
SELECT id FROM btc_tx
WHERE coin = $1 AND action = $2 AND sent_hash_tx = $3
`

type GetBtcTxIDBySentHashParams struct {
	Coin       interface{}
	Action     interface{}
	SentHashTx string
}

func (q *Queries) GetBtcTxIDBySentHash(ctx context.Context, arg GetBtcTxIDBySentHashParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBtcTxIDBySentHash, arg.Coin, arg.Action, arg.SentHashTx)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getBtcTxIDByUnsignedHex = `-- name: GetBtcTxIDByUnsignedHex :one
SELECT id FROM btc_tx
WHERE coin = $1 AND action = $2 AND unsigned_hex_tx = $3
`

type GetBtcTxIDByUnsignedHexParams struct {
	Coin          interface{}
	Action        interface{}
	UnsignedHexTx string
}

func (q *Queries) GetBtcTxIDByUnsignedHex(ctx context.Context, arg GetBtcTxIDByUnsignedHexParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBtcTxIDByUnsignedHex, arg.Coin, arg.Action, arg.UnsignedHexTx)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getBtcTxSentHashList = `-- name: GetBtcTxSentHashList :many
SELECT sent_hash_tx FROM btc_tx
WHERE coin = $1 AND action = $2 AND current_tx_type = $3
`

type GetBtcTxSentHashListParams struct {
	Coin          interface{}
	Action        interface{}
	CurrentTxType int16
}

func (q *Queries) GetBtcTxSentHashList(ctx context.Context, arg GetBtcTxSentHashListParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBtcTxSentHashList, arg.Coin, arg.Action, arg.CurrentTxType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sent_hash_tx string
		if err := rows.Scan(&sent_hash_tx); err != nil {
			return nil, err
		}
		items = append(items, sent_hash_tx)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBtcTx = `-- name: InsertBtcTx :one
INSERT INTO btc_tx (
  coin, action, unsigned_hex_tx, signed_hex_tx, sent_hash_tx,
  total_input_amount, total_output_amount, fee, current_tx_type,
  unsigned_updated_at, sent_updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertBtcTxParams struct {
	Coin              interface{}
	Action            interface{}
	UnsignedHexTx     string
	SignedHexTx       string
	SentHashTx        string
	TotalInputAmount  string
	TotalOutputAmount string
	Fee               string
	CurrentTxType     int16
	UnsignedUpdatedAt sql.NullTime
	SentUpdatedAt     sql.NullTime
}

func (q *Queries) InsertBtcTx(ctx context.Context, arg InsertBtcTxParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBtcTx,
		arg.Coin,
		arg.Action,
		arg.UnsignedHexTx,
		arg.SignedHexTx,
		arg.SentHashTx,
		arg.TotalInputAmount,
		arg.TotalOutputAmount,
		arg.Fee,
		arg.CurrentTxType,
		arg.UnsignedUpdatedAt,
		arg.SentUpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateBtcTx = `-- name: UpdateBtcTx :exec
UPDATE btc_tx
SET coin = $1, action = $2, unsigned_hex_tx = $3, signed_hex_tx = $4, sent_hash_tx = $5,
    total_input_amount = $6, total_output_amount = $7, fee = $8, current_tx_type = $9,
    unsigned_updated_at = $10, sent_updated_at = $11
WHERE id = $12
`

type UpdateBtcTxParams struct {
	Coin              interface{}
	Action            interface{}
	UnsignedHexTx     string
	SignedHexTx       string
	SentHashTx        string
	TotalInputAmount  string
	TotalOutputAmount string
	Fee               string
	CurrentTxType     int16
	UnsignedUpdatedAt sql.NullTime
	SentUpdatedAt     sql.NullTime
	ID                int64
}

func (q *Queries) UpdateBtcTx(ctx context.Context, arg UpdateBtcTxParams) error {
	_, err := q.db.ExecContext(ctx, updateBtcTx,
		arg.Coin,
		arg.Action,
		arg.UnsignedHexTx,
		arg.SignedHexTx,
		arg.SentHashTx,
		arg.TotalInputAmount,
		arg.TotalOutputAmount,
		arg.Fee,
		arg.CurrentTxType,
		arg.UnsignedUpdatedAt,
		arg.SentUpdatedAt,
		arg.ID,
	)
	return err
}

const updateBtcTxAfterSent = `-- name: UpdateBtcTxAfterSent :execresult
UPDATE btc_tx
SET current_tx_type = $1, signed_hex_tx = $2, sent_hash_tx = $3, sent_updated_at = $4
WHERE id = $5
`

type UpdateBtcTxAfterSentParams struct {
	CurrentTxType int16
	SignedHexTx   string
	SentHashTx    string
	SentUpdatedAt sql.NullTime
	ID            int64
}

func (q *Queries) UpdateBtcTxAfterSent(ctx context.Context, arg UpdateBtcTxAfterSentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBtcTxAfterSent,
		arg.CurrentTxType,
		arg.SignedHexTx,
		arg.SentHashTx,
		arg.SentUpdatedAt,
		arg.ID,
	)
}

const updateBtcTxType = `-- name: UpdateBtcTxType :execresult
UPDATE btc_tx
SET current_tx_type = $1
WHERE id = $2
`

type UpdateBtcTxTypeParams struct {
	CurrentTxType int16
	ID            int64
}

func (q *Queries) UpdateBtcTxType(ctx context.Context, arg UpdateBtcTxTypeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBtcTxType, arg.CurrentTxType, arg.ID)
}

const updateBtcTxTypeBySentHash = `-- name: UpdateBtcTxTypeBySentHash :execresult
UPDATE btc_tx
SET current_tx_type = $1
WHERE coin = $2 AND action = $3 AND sent_hash_tx = $4
`

type UpdateBtcTxTypeBySentHashParams struct {
	CurrentTxType int16
	Coin          interface{}
	Action        interface{}
	SentHashTx    string
}

func (q *Queries) UpdateBtcTxTypeBySentHash(ctx context.Context, arg UpdateBtcTxTypeBySentHashParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBtcTxTypeBySentHash,
		arg.CurrentTxType,
		arg.Coin,
		arg.Action,
		arg.SentHashTx,
	)
}
