// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_request.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteAllPaymentRequests = `-- name: DeleteAllPaymentRequests :execresult
DELETE FROM payment_request
WHERE coin = $1
`

func (q *Queries) DeleteAllPaymentRequests(ctx context.Context, coin interface{}) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAllPaymentRequests, coin)
}

const getAllPaymentRequests = `-- name: GetAllPaymentRequests :many
SELECT id, coin, payment_id, sender_address, sender_account, receiver_address, amount, is_done, updated_at FROM payment_request
WHERE coin = $1 AND payment_id IS NULL
`

func (q *Queries) GetAllPaymentRequests(ctx context.Context, coin interface{}) ([]PaymentRequest, error) {
	rows, err := q.db.QueryContext(ctx, getAllPaymentRequests, coin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentRequest
	for rows.Next() {
		var i PaymentRequest
		if err := rows.Scan(
			&i.ID,
			&i.Coin,
			&i.PaymentID,
			&i.SenderAddress,
			&i.SenderAccount,
			&i.ReceiverAddress,
			&i.Amount,
			&i.IsDone,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentRequestsByPaymentID = `-- name: GetPaymentRequestsByPaymentID :many
SELECT id, coin, payment_id, sender_address, sender_account, receiver_address, amount, is_done, updated_at FROM payment_request
WHERE coin = $1 AND payment_id = $2
`

type GetPaymentRequestsByPaymentIDParams struct {
	Coin      interface{}
	PaymentID sql.NullInt64
}

func (q *Queries) GetPaymentRequestsByPaymentID(ctx context.Context, arg GetPaymentRequestsByPaymentIDParams) ([]PaymentRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentRequestsByPaymentID, arg.Coin, arg.PaymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentRequest
	for rows.Next() {
		var i PaymentRequest
		if err := rows.Scan(
			&i.ID,
			&i.Coin,
			&i.PaymentID,
			&i.SenderAddress,
			&i.SenderAccount,
			&i.ReceiverAddress,
			&i.Amount,
			&i.IsDone,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPaymentRequest = `-- name: InsertPaymentRequest :one
INSERT INTO payment_request (coin, payment_id, sender_address, sender_account, receiver_address, amount, is_done, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertPaymentRequestParams struct {
	Coin            interface{}
	PaymentID       sql.NullInt64
	SenderAddress   string
	SenderAccount   string
	ReceiverAddress string
	Amount          string
	IsDone          bool
	UpdatedAt       sql.NullTime
}

func (q *Queries) InsertPaymentRequest(ctx context.Context, arg InsertPaymentRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPaymentRequest,
		arg.Coin,
		arg.PaymentID,
		arg.SenderAddress,
		arg.SenderAccount,
		arg.ReceiverAddress,
		arg.Amount,
		arg.IsDone,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updatePaymentRequestIsDone = `-- name: UpdatePaymentRequestIsDone :execresult
UPDATE payment_request
SET is_done = $1
WHERE coin = $2 AND payment_id = $3
`

type UpdatePaymentRequestIsDoneParams struct {
	IsDone    bool
	Coin      interface{}
	PaymentID sql.NullInt64
}

func (q *Queries) UpdatePaymentRequestIsDone(ctx context.Context, arg UpdatePaymentRequestIsDoneParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePaymentRequestIsDone, arg.IsDone, arg.Coin, arg.PaymentID)
}

const updatePaymentRequestPaymentID = `-- name: UpdatePaymentRequestPaymentID :execresult
UPDATE payment_request
SET payment_id = $1
WHERE id = $2
`

type UpdatePaymentRequestPaymentIDParams struct {
	PaymentID sql.NullInt64
	ID        int64
}

func (q *Queries) UpdatePaymentRequestPaymentID(ctx context.Context, arg UpdatePaymentRequestPaymentIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePaymentRequestPaymentID, arg.PaymentID, arg.ID)
}
