// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seed.sql

package sqlcgen

import (
	"context"
)

const getSeed = `-- name: GetSeed :one
SELECT id, coin, seed, updated_at FROM seed WHERE coin = $1 LIMIT 1
`

func (q *Queries) GetSeed(ctx context.Context, coin interface{}) (Seed, error) {
	row := q.db.QueryRowContext(ctx, getSeed, coin)
	var i Seed
	err := row.Scan(
		&i.ID,
		&i.Coin,
		&i.Seed,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSeed = `-- name: InsertSeed :one
INSERT INTO seed (coin, seed) VALUES ($1, $2)
RETURNING id
`

type InsertSeedParams struct {
	Coin interface{}
	Seed string
}

func (q *Queries) InsertSeed(ctx context.Context, arg InsertSeedParams) (int16, error) {
	row := q.db.QueryRowContext(ctx, insertSeed, arg.Coin, arg.Seed)
	var id int16
	err := row.Scan(&id)
	return id, err
}
