// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: xrp_detail_tx.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getXRPDetailTxBlobList = `-- name: GetXRPDetailTxBlobList :many
SELECT xrp_detail_tx.tx_blob
FROM xrp_detail_tx
  INNER JOIN tx ON tx.id = xrp_detail_tx.tx_id
WHERE tx.coin = $1
  AND xrp_detail_tx.current_tx_type = $2
`

type GetXRPDetailTxBlobListParams struct {
	Coin          interface{}
	CurrentTxType int16
}

func (q *Queries) GetXRPDetailTxBlobList(ctx context.Context, arg GetXRPDetailTxBlobListParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getXRPDetailTxBlobList, arg.Coin, arg.CurrentTxType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tx_blob string
		if err := rows.Scan(&tx_blob); err != nil {
			return nil, err
		}
		items = append(items, tx_blob)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getXRPDetailTxByID = `-- name: GetXRPDetailTxByID :one
SELECT id, tx_id, uuid, current_tx_type, sender_account, sender_address, receiver_account, receiver_address, amount, xrp_tx_type, fee, flags, last_ledger_sequence, sequence, signing_pubkey, txn_signature, hash, earliest_ledger_version, signed_tx_id, tx_blob, sent_updated_at
FROM xrp_detail_tx
WHERE id = $1
`

func (q *Queries) GetXRPDetailTxByID(ctx context.Context, id int64) (XrpDetailTx, error) {
	row := q.db.QueryRowContext(ctx, getXRPDetailTxByID, id)
	var i XrpDetailTx
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.Uuid,
		&i.CurrentTxType,
		&i.SenderAccount,
		&i.SenderAddress,
		&i.ReceiverAccount,
		&i.ReceiverAddress,
		&i.Amount,
		&i.XrpTxType,
		&i.Fee,
		&i.Flags,
		&i.LastLedgerSequence,
		&i.Sequence,
		&i.SigningPubkey,
		&i.TxnSignature,
		&i.Hash,
		&i.EarliestLedgerVersion,
		&i.SignedTxID,
		&i.TxBlob,
		&i.SentUpdatedAt,
	)
	return i, err
}

const getXRPDetailTxsByTxID = `-- name: GetXRPDetailTxsByTxID :many
SELECT id, tx_id, uuid, current_tx_type, sender_account, sender_address, receiver_account, receiver_address, amount, xrp_tx_type, fee, flags, last_ledger_sequence, sequence, signing_pubkey, txn_signature, hash, earliest_ledger_version, signed_tx_id, tx_blob, sent_updated_at
FROM xrp_detail_tx
WHERE tx_id = $1
`

func (q *Queries) GetXRPDetailTxsByTxID(ctx context.Context, txID int64) ([]XrpDetailTx, error) {
	rows, err := q.db.QueryContext(ctx, getXRPDetailTxsByTxID, txID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XrpDetailTx
	for rows.Next() {
		var i XrpDetailTx
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Uuid,
			&i.CurrentTxType,
			&i.SenderAccount,
			&i.SenderAddress,
			&i.ReceiverAccount,
			&i.ReceiverAddress,
			&i.Amount,
			&i.XrpTxType,
			&i.Fee,
			&i.Flags,
			&i.LastLedgerSequence,
			&i.Sequence,
			&i.SigningPubkey,
			&i.TxnSignature,
			&i.Hash,
			&i.EarliestLedgerVersion,
			&i.SignedTxID,
			&i.TxBlob,
			&i.SentUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertXRPDetailTx = `-- name: InsertXRPDetailTx :one
INSERT INTO xrp_detail_tx (
    tx_id,
    uuid,
    current_tx_type,
    sender_account,
    sender_address,
    receiver_account,
    receiver_address,
    amount,
    xrp_tx_type,
    fee,
    flags,
    last_ledger_sequence,
    sequence,
    signing_pubkey,
    txn_signature,
    hash,
    earliest_ledger_version,
    signed_tx_id,
    tx_blob,
    sent_updated_at
  )
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20
  )
RETURNING id
`

type InsertXRPDetailTxParams struct {
	TxID                  int64
	Uuid                  string
	CurrentTxType         int16
	SenderAccount         string
	SenderAddress         string
	ReceiverAccount       string
	ReceiverAddress       string
	Amount                string
	XrpTxType             string
	Fee                   string
	Flags                 int64
	LastLedgerSequence    int64
	Sequence              int64
	SigningPubkey         string
	TxnSignature          string
	Hash                  string
	EarliestLedgerVersion int64
	SignedTxID            string
	TxBlob                string
	SentUpdatedAt         sql.NullTime
}

func (q *Queries) InsertXRPDetailTx(ctx context.Context, arg InsertXRPDetailTxParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertXRPDetailTx,
		arg.TxID,
		arg.Uuid,
		arg.CurrentTxType,
		arg.SenderAccount,
		arg.SenderAddress,
		arg.ReceiverAccount,
		arg.ReceiverAddress,
		arg.Amount,
		arg.XrpTxType,
		arg.Fee,
		arg.Flags,
		arg.LastLedgerSequence,
		arg.Sequence,
		arg.SigningPubkey,
		arg.TxnSignature,
		arg.Hash,
		arg.EarliestLedgerVersion,
		arg.SignedTxID,
		arg.TxBlob,
		arg.SentUpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateXRPDetailTxAfterSent = `-- name: UpdateXRPDetailTxAfterSent :execresult
UPDATE xrp_detail_tx
SET current_tx_type = $1,
  signed_tx_id = $2,
  tx_blob = $3,
  earliest_ledger_version = $4,
  sent_updated_at = $5
WHERE uuid = $6
`

type UpdateXRPDetailTxAfterSentParams struct {
	CurrentTxType         int16
	SignedTxID            string
	TxBlob                string
	EarliestLedgerVersion int64
	SentUpdatedAt         sql.NullTime
	Uuid                  string
}

func (q *Queries) UpdateXRPDetailTxAfterSent(ctx context.Context, arg UpdateXRPDetailTxAfterSentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateXRPDetailTxAfterSent,
		arg.CurrentTxType,
		arg.SignedTxID,
		arg.TxBlob,
		arg.EarliestLedgerVersion,
		arg.SentUpdatedAt,
		arg.Uuid,
	)
}

const updateXRPDetailTxType = `-- name: UpdateXRPDetailTxType :execresult
UPDATE xrp_detail_tx
SET current_tx_type = $1
WHERE id = $2
`

type UpdateXRPDetailTxTypeParams struct {
	CurrentTxType int16
	ID            int64
}

func (q *Queries) UpdateXRPDetailTxType(ctx context.Context, arg UpdateXRPDetailTxTypeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateXRPDetailTxType, arg.CurrentTxType, arg.ID)
}

const updateXRPDetailTxTypeBySentHash = `-- name: UpdateXRPDetailTxTypeBySentHash :execresult
UPDATE xrp_detail_tx
SET current_tx_type = $1
WHERE tx_blob = $2
`

type UpdateXRPDetailTxTypeBySentHashParams struct {
	CurrentTxType int16
	TxBlob        string
}

func (q *Queries) UpdateXRPDetailTxTypeBySentHash(ctx context.Context, arg UpdateXRPDetailTxTypeBySentHashParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateXRPDetailTxTypeBySentHash, arg.CurrentTxType, arg.TxBlob)
}
