-- Code generated by `make extract-sqlc-schema-postgres-watch`. DO NOT EDIT.
-- Extracted from dump_watch.postgres.sql

CREATE TABLE address (
    id bigint NOT NULL,
    coin coin_all NOT NULL,
    account account_type NOT NULL,
    wallet_address character varying(255) NOT NULL,
    is_allocated boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE btc_tx (
    id bigint NOT NULL,
    coin coin_btc_bch NOT NULL,
    action action_type NOT NULL,
    unsigned_hex_tx text NOT NULL,
    signed_hex_tx text NOT NULL,
    sent_hash_tx text NOT NULL,
    total_input_amount numeric(26,10) NOT NULL,
    total_output_amount numeric(26,10) NOT NULL,
    fee numeric(26,10) NOT NULL,
    current_tx_type smallint DEFAULT 1 NOT NULL,
    unsigned_updated_at timestamp with time zone DEFAULT now(),
    sent_updated_at timestamp with time zone
);

CREATE TABLE btc_tx_input (
    id bigint NOT NULL,
    tx_id bigint NOT NULL,
    input_txid character varying(255) NOT NULL,
    input_vout integer NOT NULL,
    input_address character varying(255) NOT NULL,
    input_account character varying(255) NOT NULL,
    input_amount numeric(26,10) NOT NULL,
    input_confirmations bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE btc_tx_output (
    id bigint NOT NULL,
    tx_id bigint NOT NULL,
    output_address character varying(255) NOT NULL,
    output_account character varying(255) NOT NULL,
    output_amount numeric(26,10) NOT NULL,
    is_change boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE eth_detail_tx (
    id bigint NOT NULL,
    tx_id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    current_tx_type smallint DEFAULT 1 NOT NULL,
    sender_account character varying(255) NOT NULL,
    sender_address character varying(255) NOT NULL,
    receiver_account character varying(255) NOT NULL,
    receiver_address character varying(255) NOT NULL,
    amount bigint NOT NULL,
    fee bigint NOT NULL,
    gas_limit integer NOT NULL,
    nonce bigint NOT NULL,
    unsigned_hex_tx text NOT NULL,
    signed_hex_tx text NOT NULL,
    sent_hash_tx text NOT NULL,
    unsigned_updated_at timestamp with time zone DEFAULT now(),
    sent_updated_at timestamp with time zone
);

CREATE TABLE payment_request (
    id bigint NOT NULL,
    coin coin_payment NOT NULL,
    payment_id bigint,
    sender_address character varying(255) NOT NULL,
    sender_account character varying(255) NOT NULL,
    receiver_address character varying(255) NOT NULL,
    amount numeric(26,10) NOT NULL,
    is_done boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE tx (
    id bigint NOT NULL,
    coin coin_eth_xrp_hyt NOT NULL,
    action action_type NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE xrp_detail_tx (
    id bigint NOT NULL,
    tx_id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    current_tx_type smallint DEFAULT 1 NOT NULL,
    sender_account character varying(255) NOT NULL,
    sender_address character varying(255) NOT NULL,
    receiver_account character varying(255) NOT NULL,
    receiver_address character varying(255) NOT NULL,
    amount character varying(255) NOT NULL,
    xrp_tx_type character varying(255) NOT NULL,
    fee character varying(255) NOT NULL,
    flags bigint NOT NULL,
    last_ledger_sequence bigint NOT NULL,
    sequence bigint NOT NULL,
    signing_pubkey character varying(255) NOT NULL,
    txn_signature character varying(255) NOT NULL,
    hash character varying(255) NOT NULL,
    earliest_ledger_version bigint NOT NULL,
    signed_tx_id character varying(255) NOT NULL,
    tx_blob text NOT NULL,
    sent_updated_at timestamp with time zone
);

CREATE TABLE xrp_multisig_signature (
    id bigint NOT NULL,
    pending_multisig_id bigint NOT NULL,
    signer_account character varying(255) NOT NULL,
    signed_tx_blob text NOT NULL,
    signer_weight integer NOT NULL,
    signed_at timestamp with time zone DEFAULT now()
);

CREATE TABLE xrp_pending_multisig (
    id bigint NOT NULL,
    tx_uuid character varying(36) NOT NULL,
    account_id character varying(255) NOT NULL,
    unsigned_tx_json text NOT NULL,
    xrp_tx_type character varying(50) NOT NULL,
    required_quorum integer NOT NULL,
    current_weight integer DEFAULT 0 NOT NULL,
    status multisig_status DEFAULT 'pending'::multisig_status NOT NULL,
    combined_tx_blob text,
    submitted_tx_hash character varying(255),
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

