// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: xrp_multisig_signature.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteXRPMultisigSignaturesByPendingID = `-- name: DeleteXRPMultisigSignaturesByPendingID :exec
DELETE FROM xrp_multisig_signature
WHERE pending_multisig_id = $1
`

func (q *Queries) DeleteXRPMultisigSignaturesByPendingID(ctx context.Context, pendingMultisigID int64) error {
	_, err := q.db.ExecContext(ctx, deleteXRPMultisigSignaturesByPendingID, pendingMultisigID)
	return err
}

const getSignatureCountByPendingID = `-- name: GetSignatureCountByPendingID :one
SELECT COUNT(*) as signature_count
FROM xrp_multisig_signature
WHERE pending_multisig_id = $1
`

func (q *Queries) GetSignatureCountByPendingID(ctx context.Context, pendingMultisigID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSignatureCountByPendingID, pendingMultisigID)
	var signature_count int64
	err := row.Scan(&signature_count)
	return signature_count, err
}

const getTotalSignedWeightByPendingID = `-- name: GetTotalSignedWeightByPendingID :one
SELECT COALESCE(SUM(signer_weight), 0) as total_weight
FROM xrp_multisig_signature
WHERE pending_multisig_id = $1
`

func (q *Queries) GetTotalSignedWeightByPendingID(ctx context.Context, pendingMultisigID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalSignedWeightByPendingID, pendingMultisigID)
	var total_weight interface{}
	err := row.Scan(&total_weight)
	return total_weight, err
}

const getXRPMultisigSignatureByID = `-- name: GetXRPMultisigSignatureByID :one
SELECT id, pending_multisig_id, signer_account, signed_tx_blob, signer_weight, signed_at FROM xrp_multisig_signature
WHERE id = $1
`

func (q *Queries) GetXRPMultisigSignatureByID(ctx context.Context, id int64) (XrpMultisigSignature, error) {
	row := q.db.QueryRowContext(ctx, getXRPMultisigSignatureByID, id)
	var i XrpMultisigSignature
	err := row.Scan(
		&i.ID,
		&i.PendingMultisigID,
		&i.SignerAccount,
		&i.SignedTxBlob,
		&i.SignerWeight,
		&i.SignedAt,
	)
	return i, err
}

const getXRPMultisigSignatureByPendingAndSigner = `-- name: GetXRPMultisigSignatureByPendingAndSigner :one
SELECT id, pending_multisig_id, signer_account, signed_tx_blob, signer_weight, signed_at FROM xrp_multisig_signature
WHERE pending_multisig_id = $1 AND signer_account = $2
LIMIT 1
`

type GetXRPMultisigSignatureByPendingAndSignerParams struct {
	PendingMultisigID int64
	SignerAccount     string
}

func (q *Queries) GetXRPMultisigSignatureByPendingAndSigner(ctx context.Context, arg GetXRPMultisigSignatureByPendingAndSignerParams) (XrpMultisigSignature, error) {
	row := q.db.QueryRowContext(ctx, getXRPMultisigSignatureByPendingAndSigner, arg.PendingMultisigID, arg.SignerAccount)
	var i XrpMultisigSignature
	err := row.Scan(
		&i.ID,
		&i.PendingMultisigID,
		&i.SignerAccount,
		&i.SignedTxBlob,
		&i.SignerWeight,
		&i.SignedAt,
	)
	return i, err
}

const getXRPMultisigSignaturesByPendingID = `-- name: GetXRPMultisigSignaturesByPendingID :many
SELECT id, pending_multisig_id, signer_account, signed_tx_blob, signer_weight, signed_at FROM xrp_multisig_signature
WHERE pending_multisig_id = $1
ORDER BY signed_at ASC
`

func (q *Queries) GetXRPMultisigSignaturesByPendingID(ctx context.Context, pendingMultisigID int64) ([]XrpMultisigSignature, error) {
	rows, err := q.db.QueryContext(ctx, getXRPMultisigSignaturesByPendingID, pendingMultisigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XrpMultisigSignature
	for rows.Next() {
		var i XrpMultisigSignature
		if err := rows.Scan(
			&i.ID,
			&i.PendingMultisigID,
			&i.SignerAccount,
			&i.SignedTxBlob,
			&i.SignerWeight,
			&i.SignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertXRPMultisigSignature = `-- name: InsertXRPMultisigSignature :one
INSERT INTO xrp_multisig_signature (
  pending_multisig_id, signer_account, signed_tx_blob, signer_weight, signed_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertXRPMultisigSignatureParams struct {
	PendingMultisigID int64
	SignerAccount     string
	SignedTxBlob      string
	SignerWeight      int32
	SignedAt          sql.NullTime
}

func (q *Queries) InsertXRPMultisigSignature(ctx context.Context, arg InsertXRPMultisigSignatureParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertXRPMultisigSignature,
		arg.PendingMultisigID,
		arg.SignerAccount,
		arg.SignedTxBlob,
		arg.SignerWeight,
		arg.SignedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
