FROM wallet-golang:1.11

#RUN go get -u github.com/hiromaily/go-bitcon/...

RUN mkdir -p /go/src/github.com/hiromaily/go-bitcon
WORKDIR /go/src/github.com/hiromaily/go-bitcon

#RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/wallet ./cmd/wallet/main.go
#RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/coldwallet1 ./cmd/coldwallet1/main.go

#CMD ["/go/bin/wallet", "-f", "/go/src/github.com/hiromaily/go-bitcon/data/toml/local_watch_only.toml"]
