FROM cayenne-wallet-golang:1.11

#RUN go get -u github.com/mf-financial/cayenne_wallet/...

RUN mkdir -p /go/src/github.com/mf-financial/cayenne_wallet
WORKDIR /go/src/github.com/mf-financial/cayenne_wallet

#RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/wallet ./cmd/wallet/main.go
#RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/coldwallet1 ./cmd/coldwallet1/main.go

#CMD ["/go/bin/wallet", "-f", "/go/src/github.com/mf-financial/cayenne_wallet/data/toml/local_watch_only.toml"]
