version: "2"

run:
  go: "1.25.5"
  timeout: 5m

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

formatters:
  enable:
    - gofumpt       # Detects whether code was gofumpt-ed.
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hiromaily
  exclusions:
    generated: strict

linters:
  enable:
    - asasalint                 # Detects "[]any" used as argument for variadic "func(...any)".
    - bodyclose
    - copyloopvar               # Detects places where loop variables are copied.
    - depguard
    - dogsled                   # Detects assignments with too many blank identifiers.
    - dupword                   # Detects duplicate words.
    - durationcheck             # Detect cases where two time.Duration values are being multiplied in possibly erroneous ways.
    - errcheck
    - errchkjson                # Detects unsupported types passed to json encoding functions and reports if checks for the returned error can be omitted.
    - exhaustive                # Detects missing options in enum switch statements.
    - exptostd                  # Detects functions from golang.org/x/exp/ that can be replaced by std functions.
    - fatcontext                # Detects nested contexts in loops and function literals.
    - forbidigo
    - gocheckcompilerdirectives # Detects invalid go compiler directive comments (//go:).
    - gocritic                  # Metalinter; detects bugs, performance, and styling issues.
    - gocyclo
    - gosec                     # Detects security problems.
    - govet
    - iface                     # Detects incorrect use of interfaces. Currently only used for "identical" interfaces in the same package.
    - importas                  # Enforces consistent import aliases.
    - ineffassign
    - makezero                  # Finds slice declarations with non-zero initial length.
    - mirror                    # Detects wrong mirror patterns of bytes/strings usage.
    - misspell                  # Detects commonly misspelled English words in comments.
    - nakedret                  # Detects uses of naked returns.
    - nilnesserr                # Detects returning nil errors. It combines the features of nilness and nilerr,
    - nosprintfhostport         # Detects misuse of Sprintf to construct a host with port in a URL.
    - nolintlint                # Detects ill-formed or insufficient nolint directives.
    - perfsprint                # Detects fmt.Sprintf uses that can be replaced with a faster alternative.
    - prealloc                  # Detects slice declarations that could potentially be pre-allocated.
    - predeclared               # Detects code that shadows one of Go's predeclared identifiers
    - reassign                  # Detects reassigning a top-level variable in another package.
    - revive                    # Metalinter; drop-in replacement for golint.
    - spancheck                 # Detects mistakes with OpenTelemetry/Census spans.
    - staticcheck
    - thelper                   # Detects test helpers without t.Helper().
    - tparallel                 # Detects inappropriate usage of t.Parallel().
    - unconvert                 # Detects unnecessary type conversions.
    - unparam
    - unused
    - usestdlibvars             # Detects the possibility to use variables/constants from the Go standard library.
    - usetesting                # Reports uses of functions with replacement inside the testing package.
    - wastedassign              # Detects wasted assignment statements.
  
  disable:
    - errcheck
  
  settings:
    depguard: 
      rules:
        websocket:
          deny:
            - pkg: "nhooyr.io/websocket"
              desc: The containerd websocket package was migrated to a separate module. Use github.com/coder/websocket instead.
    forbidigo:
      forbid:
        - pkg: ^regexp$
          pattern: ^regexp\.MustCompile
          msg: Use internal/lazyregexp.New instead.

    gocyclo:
      min-complexity: 16

    gosec:
      excludes:
        - G104 # G104: Errors unhandled;
        - G115 # G115: integer overflow conversion;
        - G306 # G306: Expect WriteFile permissions to be 0600 or less (too restrictive; also flags "0o644" permissions)
        - G307 # G307: Deferring unsafe method 

    govet:
      enable:
        - shadow
      settings:
        shadow:
          strict: true

    lll:
      line-length: 120

    importas:
      # Do not allow unaliased imports of aliased packages.
      no-unaliased: true

      # set aliases for packages
      # alias:
      #   - pkg: gotest.tools/v3/assert/cmp
      #     alias: is

    nakedret:
      # Disallow naked returns if func has more lines of code than this setting.
      # Default: 30
      max-func-lines: 0

    staticcheck:
      checks:
        - all
        - -QF1008 # Omit embedded fields from selector expression; https://staticcheck.dev/docs/checks/#QF1008

    revive:
      rules:
        - name: empty-block       # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-block
        - name: empty-lines       # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-lines
        - name: line-length-limit # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#line-length-limit
          arguments: [120]
        - name: unused-receiver   # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-receiver
        - name: use-any           # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#use-any
        - name: use-errors-new    # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#use-errors-new
        # - name: import-shadowing  # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#import-shadowing

    usetesting:
      os-chdir: false           # FIXME(thaJeztah): Disable `os.Chdir()` detections; should be automatically disabled on Go < 1.24; see https://github.com/docker/cli/pull/5835#issuecomment-2665302478
      context-background: false # FIXME(thaJeztah): Disable `context.Background()` detections; should be automatically disabled on Go < 1.24; see https://github.com/docker/cli/pull/5835#issuecomment-2665302478
      context-todo: false       # FIXME(thaJeztah): Disable `context.TODO()` detections; should be automatically disabled on Go < 1.24; see https://github.com/docker/cli/pull/5835#issuecomment-2665302478

  exclusions:
    generated: strict

    rules:
      # Exclude some linters from running on tests files.
      # - path: _test\.go
      #   linters:
      #     - gosec
      - text: "ST1000: at least one file in a package should have a package comment"
        linters:
          - staticcheck
      - text: 'declaration of "err" shadows declaration'
        linters:
          - govet
      # Exclude SA1019 (deprecated) warnings - these are expected for backward compatibility
      - text: "SA1019:"
        linters:
          - staticcheck

    # Exclude files from all linters.
    paths:
      - ".*\\.pb\\.go"
      #- ".*\\.test\\.go"
    
    # Log a warning if an exclusion rule is unused.
    # Default: false
    warn-unused: true