networks:
  xrp:
    name: xrp
    driver: bridge

services:
  #########################################################################
  # xrptipbot/rippled
  # - Documentations
  #  - https://github.com/ripple/rippled
  #  - https://xrpl.org/install-rippled.html
  #  - https://xrpl.org/configure-rippled.html
  #  - https://xrpl.org/connect-your-rippled-to-the-xrp-test-net.html
  # - Build Docker Container for rippled
  #  - run `./scripts/build-rippled-container.sh` before running docker compose
  #------------------------------------------------------------------------
  # $ docker compose -f compose.xrp.yaml exec xrp-node sh
  #########################################################################
  xrp-node:
    image: local-rippled:latest
    container_name: xrp-node
    volumes:
      - ./docker/nodes/xrp/config:/config
      - ./docker/nodes/xrp/db:/var/lib/rippled/db
      - ./data/certs:/etc/ssl/certs
    ports:
      #- "${WRP_WEBSOCKET_PORT:-51233}:80"
      - "${WRP_PUBLIC_WEBSOCKET_PORT:-6005}:6005"
      - "${WRP_ADMIN_WEBSOCKET_PORT:-6006}:6006"
    stdin_open: true
    tty: true
    networks:
      - xrp
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "--post-data={\"method\":\"server_info\",\"params\":[{}]}", "--header=Content-Type: application/json", "http://localhost:6006"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    #command:
    #  - /opt/ripple/bin/rippled --net --conf /etc/opt/ripple/rippled.cfg
