package descriptor

// Descriptor Service - BTC ONLY
//
// ┌─────────────────────────────────────────────────────────────────────────────┐
// │ WARNING: DO NOT USE THIS FILE FOR BCH (Bitcoin Cash) IMPLEMENTATIONS        │
// │                                                                             │
// │ BCH does NOT support output descriptors (BIP380).                           │
// │ BCH uses legacy wallet with address export/import workflow instead.         │
// │                                                                             │
// │ For BCH implementations, see:                                               │
// │   - internal/infrastructure/api/btc/bch/                                    │
// │   - docs/chains/bch/README.md                                               │
// └─────────────────────────────────────────────────────────────────────────────┘

import (
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/btcsuite/btcd/btcutil/hdkeychain"
	"github.com/btcsuite/btcd/chaincfg"
)

const (
	descriptorFormatPKH    = "pkh([%s%s]%s/%d/*)"
	descriptorFormatSHWPKH = "sh(wpkh([%s%s]%s/%d/*))"
	descriptorFormatWPKH   = "wpkh([%s%s]%s/%d/*)"
	descriptorFormatTR     = "tr([%s%s]%s/%d/*)"
)

// DescriptorService generates descriptors for supported single-signature templates.
//
// Note: Descriptors generated by this service do NOT include checksums.
// The watch wallet adds checksums using Bitcoin Core's getdescriptorinfo RPC before importing.
type DescriptorService struct {
	chainParams *chaincfg.Params
}

// NewDescriptorService creates a descriptor service for the given Bitcoin network parameters.
func NewDescriptorService(chainParams *chaincfg.Params) *DescriptorService {
	return &DescriptorService{
		chainParams: chainParams,
	}
}

func (d *DescriptorService) formatDescriptor(
	template string,
	fingerprint string,
	derivationPath string,
	xpub *hdkeychain.ExtendedKey,
	isChange bool,
) (string, error) {
	if xpub == nil {
		return "", errors.New("extended public key is nil")
	}

	if xpub.IsPrivate() {
		return "", errors.New("extended key must be public")
	}

	if d.chainParams != nil && !xpub.IsForNet(d.chainParams) {
		return "", fmt.Errorf("extended public key network mismatch: expected %s", d.chainParams.Name)
	}

	normalizedFingerprint := strings.ToLower(strings.TrimSpace(fingerprint))
	normalizedPath := normalizeDerivationPath(derivationPath)

	if err := ValidateFingerprint(normalizedFingerprint); err != nil {
		return "", fmt.Errorf("invalid fingerprint: %w", err)
	}

	if err := ValidateDerivationPath(normalizedPath); err != nil {
		return "", fmt.Errorf("invalid derivation path: %w", err)
	}

	changeIndex := 0
	if isChange {
		changeIndex = 1
	}

	descriptor := fmt.Sprintf(template, normalizedFingerprint, normalizedPath, xpub.String(), changeIndex)

	// Note: Checksum is NOT added here because the domain layer's BIP380 implementation
	// produces incorrect checksums. Instead, the watch wallet will add checksums using
	// Bitcoin Core's getdescriptorinfo RPC before importing (which guarantees correctness).
	// This allows keygen to remain offline while ensuring correct checksums.
	// TODO: Fix BIP380 checksum implementation in internal/domain/wallet/descriptor_builder.go

	return descriptor, nil
}

func normalizeDerivationPath(path string) string {
	trimmed := strings.TrimSpace(path)

	if strings.HasPrefix(trimmed, "m/") || strings.HasPrefix(trimmed, "M/") {
		trimmed = trimmed[1:]
	}

	return trimmed
}

func (d *DescriptorService) formatAndSortMultisigKeys(
	signers []MultisigSigner,
	isChange bool,
	shouldSort bool,
) ([]string, error) {
	changeIndex := 0
	if isChange {
		changeIndex = 1
	}

	keyStrings := make([]string, len(signers))
	for i, signer := range signers {
		keyStr, err := d.formatMultisigKey(signer, changeIndex)
		if err != nil {
			return nil, fmt.Errorf("invalid signer %d: %w", i, err)
		}
		keyStrings[i] = keyStr
	}

	// Sort keys only for sortedmulti() descriptors (WSH, SHWSH).
	// For multi() descriptors (SH), preserve original order.
	if shouldSort {
		sort.Strings(keyStrings)
	}

	return keyStrings, nil
}

// GenerateBech32Descriptor generates a Bech32 (wpkh) descriptor following BIP380.
//
// Format: wpkh([fingerprint/84'/0'/0']xpub.../0/*)
func (d *DescriptorService) GenerateBech32Descriptor(
	fingerprint string,
	derivationPath string,
	xpub *hdkeychain.ExtendedKey,
	isChange bool,
) (string, error) {
	return d.formatDescriptor(descriptorFormatWPKH, fingerprint, derivationPath, xpub, isChange)
}

// GenerateP2PKHDescriptor generates a P2PKH (legacy) descriptor following BIP380.
//
// Format: pkh([fingerprint/44'/0'/0']xpub.../0/*)
func (d *DescriptorService) GenerateP2PKHDescriptor(
	fingerprint string,
	derivationPath string,
	xpub *hdkeychain.ExtendedKey,
	isChange bool,
) (string, error) {
	return d.formatDescriptor(descriptorFormatPKH, fingerprint, derivationPath, xpub, isChange)
}

// GenerateP2SHSegWitDescriptor generates a P2SH-SegWit descriptor following BIP380.
//
// Format: sh(wpkh([fingerprint/49'/0'/0']xpub.../0/*))
func (d *DescriptorService) GenerateP2SHSegWitDescriptor(
	fingerprint string,
	derivationPath string,
	xpub *hdkeychain.ExtendedKey,
	isChange bool,
) (string, error) {
	return d.formatDescriptor(descriptorFormatSHWPKH, fingerprint, derivationPath, xpub, isChange)
}

// GenerateTaprootDescriptor generates a Taproot (tr) descriptor following BIP380.
//
// Format: tr([fingerprint/86'/0'/0']xpub.../0/*)
func (d *DescriptorService) GenerateTaprootDescriptor(
	fingerprint string,
	derivationPath string,
	xpub *hdkeychain.ExtendedKey,
	isChange bool,
) (string, error) {
	return d.formatDescriptor(descriptorFormatTR, fingerprint, derivationPath, xpub, isChange)
}
