// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Address struct {
	ID            int64
	Coin          string
	Account       string
	WalletAddress string
	IsAllocated   int64
	UpdatedAt     sql.NullString
}

type AuthAccountKey struct {
	ID                     int64
	Coin                   string
	KeyType                string
	AuthAccount            string
	Account                string
	P2pkhAddress           string
	P2shSegwitAddress      string
	Bech32Address          string
	TaprootAddress         sql.NullString
	FullPublicKey          string
	MultisigAddress        string
	RedeemScript           string
	WalletImportFormat     string
	AccountExtendedPrivkey sql.NullString
	Idx                    int64
	AddrStatus             int64
	UpdatedAt              sql.NullString
}

type AuthFullpubkey struct {
	ID             int64
	Coin           string
	AuthAccount    string
	Purpose        int64
	FullPublicKey  string
	ExtendedPubkey sql.NullString
	Fingerprint    sql.NullString
	DerivationPath sql.NullString
	UpdatedAt      sql.NullString
}

type BtcAccountKey struct {
	ID                     int64
	Coin                   string
	KeyType                string
	Account                string
	P2pkhAddress           string
	P2shSegwitAddress      string
	Bech32Address          string
	TaprootAddress         sql.NullString
	FullPublicKey          string
	MultisigAddress        string
	RedeemScript           string
	WalletImportFormat     string
	AccountExtendedPrivkey sql.NullString
	Idx                    int64
	AddrStatus             int64
	UpdatedAt              sql.NullString
}

type BtcTx struct {
	ID                int64
	Coin              string
	Action            string
	UnsignedHexTx     string
	SignedHexTx       string
	SentHashTx        string
	TotalInputAmount  string
	TotalOutputAmount string
	Fee               string
	CurrentTxType     int64
	UnsignedUpdatedAt sql.NullString
	SentUpdatedAt     sql.NullString
}

type BtcTxInput struct {
	ID                 int64
	TxID               int64
	InputTxid          string
	InputVout          int64
	InputAddress       string
	InputAccount       string
	InputAmount        string
	InputConfirmations int64
	UpdatedAt          sql.NullString
}

type BtcTxOutput struct {
	ID            int64
	TxID          int64
	OutputAddress string
	OutputAccount string
	OutputAmount  string
	IsChange      int64
	UpdatedAt     sql.NullString
}

type EthAccountKey struct {
	ID            int64
	Account       string
	Address       string
	FullPublicKey string
	PrivateKey    string
	Idx           int64
	AddrStatus    int64
	UpdatedAt     sql.NullString
}

type EthDetailTx struct {
	ID                int64
	TxID              int64
	Uuid              string
	CurrentTxType     int64
	SenderAccount     string
	SenderAddress     string
	ReceiverAccount   string
	ReceiverAddress   string
	Amount            int64
	Fee               int64
	GasLimit          int64
	Nonce             int64
	UnsignedHexTx     string
	SignedHexTx       string
	SentHashTx        string
	UnsignedUpdatedAt sql.NullString
	SentUpdatedAt     sql.NullString
}

type Musig2Nonce struct {
	ID            int64
	SignerID      string
	TransactionID string
	PublicNonce   []byte
	IsUsed        int64
	CreatedAt     sql.NullString
	UsedAt        sql.NullString
}

type PaymentRequest struct {
	ID              int64
	Coin            string
	PaymentID       sql.NullInt64
	SenderAddress   string
	SenderAccount   string
	ReceiverAddress string
	Amount          string
	IsDone          int64
	UpdatedAt       sql.NullString
}

type Seed struct {
	ID        int64
	Coin      string
	Seed      string
	UpdatedAt sql.NullString
}

type Tx struct {
	ID        int64
	Coin      string
	Action    string
	UpdatedAt sql.NullString
}

type XrpAccountKey struct {
	ID               int64
	Coin             string
	Account          string
	AccountID        string
	KeyType          int64
	MasterKey        string
	MasterSeed       string
	MasterSeedHex    string
	PublicKey        string
	PublicKeyHex     string
	IsRegularKeyPair int64
	AllocatedID      int64
	AddrStatus       int64
	UpdatedAt        sql.NullString
}

type XrpDetailTx struct {
	ID                    int64
	TxID                  int64
	Uuid                  string
	CurrentTxType         int64
	SenderAccount         string
	SenderAddress         string
	ReceiverAccount       string
	ReceiverAddress       string
	Amount                string
	XrpTxType             string
	Fee                   string
	Flags                 int64
	LastLedgerSequence    int64
	Sequence              int64
	SigningPubkey         string
	TxnSignature          string
	Hash                  string
	EarliestLedgerVersion int64
	SignedTxID            string
	TxBlob                string
	SentUpdatedAt         sql.NullString
}
