-- Code generated by `generate-e2e-sqlite-schemas.sh`. DO NOT EDIT.
-- Source: 01_watch.sql


CREATE TABLE address (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  coin TEXT NOT NULL,
  account TEXT NOT NULL,
  wallet_address TEXT NOT NULL,
  is_allocated INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE btc_tx (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  coin TEXT NOT NULL,
  "action" TEXT NOT NULL,
  unsigned_hex_tx TEXT NOT NULL,
  signed_hex_tx TEXT NOT NULL,
  sent_hash_tx TEXT NOT NULL,
  total_input_amount NUMERIC NOT NULL,
  total_output_amount NUMERIC NOT NULL,
  fee NUMERIC NOT NULL,
  current_tx_type INTEGER NOT NULL DEFAULT 1,
  unsigned_updated_at TEXT DEFAULT (CURRENT_TIMESTAMP),
  sent_updated_at TEXT
);

CREATE TABLE btc_tx_input (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tx_id INTEGER NOT NULL,
  input_txid TEXT NOT NULL,
  input_vout INTEGER NOT NULL,
  input_address TEXT NOT NULL,
  input_account TEXT NOT NULL,
  input_amount NUMERIC NOT NULL,
  input_confirmations INTEGER NOT NULL,
  updated_at TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE btc_tx_output (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tx_id INTEGER NOT NULL,
  output_address TEXT NOT NULL,
  output_account TEXT NOT NULL,
  output_amount NUMERIC NOT NULL,
  is_change INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE eth_detail_tx (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tx_id INTEGER NOT NULL,
  uuid TEXT NOT NULL,
  current_tx_type INTEGER NOT NULL DEFAULT 1,
  sender_account TEXT NOT NULL,
  sender_address TEXT NOT NULL,
  receiver_account TEXT NOT NULL,
  receiver_address TEXT NOT NULL,
  amount INTEGER NOT NULL,
  fee INTEGER NOT NULL,
  gas_limit INTEGER NOT NULL,
  nonce INTEGER NOT NULL,
  unsigned_hex_tx TEXT NOT NULL,
  signed_hex_tx TEXT NOT NULL,
  sent_hash_tx TEXT NOT NULL,
  unsigned_updated_at TEXT DEFAULT (CURRENT_TIMESTAMP),
  sent_updated_at TEXT
);

CREATE TABLE payment_request (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  coin TEXT NOT NULL,
  payment_id INTEGER,
  sender_address TEXT NOT NULL,
  sender_account TEXT NOT NULL,
  receiver_address TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  is_done INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE tx (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  coin TEXT NOT NULL,
  "action" TEXT NOT NULL,
  updated_at TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE xrp_detail_tx (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tx_id INTEGER NOT NULL,
  uuid TEXT NOT NULL,
  current_tx_type INTEGER NOT NULL DEFAULT 1,
  sender_account TEXT NOT NULL,
  sender_address TEXT NOT NULL,
  receiver_account TEXT NOT NULL,
  receiver_address TEXT NOT NULL,
  amount TEXT NOT NULL,
  xrp_tx_type TEXT NOT NULL,
  fee TEXT NOT NULL,
  flags INTEGER NOT NULL,
  last_ledger_sequence INTEGER NOT NULL,
  sequence INTEGER NOT NULL,
  signing_pubkey TEXT NOT NULL,
  txn_signature TEXT NOT NULL,
  hash TEXT NOT NULL,
  earliest_ledger_version INTEGER NOT NULL,
  signed_tx_id TEXT NOT NULL,
  tx_blob TEXT NOT NULL,
  sent_updated_at TEXT
);

CREATE TABLE xrp_multisig_signature (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pending_multisig_id INTEGER NOT NULL,
  signer_account TEXT NOT NULL,
  signed_tx_blob TEXT NOT NULL,
  signer_weight INTEGER NOT NULL,
  signed_at TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE xrp_pending_multisig (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tx_uuid TEXT NOT NULL,
  account_id TEXT NOT NULL,
  unsigned_tx_json TEXT NOT NULL,
  xrp_tx_type TEXT NOT NULL,
  required_quorum INTEGER NOT NULL,
  current_weight INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending',
  combined_tx_blob TEXT,
  submitted_tx_hash TEXT,
  expires_at TEXT,
  created_at TEXT DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT DEFAULT (CURRENT_TIMESTAMP)
);
