// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// AccountPubkeyFee is an object representing the database table.
type AccountPubkeyFee struct {
	ID            uint64    `boil:"id" json:"id" toml:"id" yaml:"id"`
	WalletAddress string    `boil:"wallet_address" json:"wallet_address" toml:"wallet_address" yaml:"wallet_address"`
	Account       string    `boil:"account" json:"account" toml:"account" yaml:"account"`
	IsAllocated   null.Bool `boil:"is_allocated" json:"is_allocated,omitempty" toml:"is_allocated" yaml:"is_allocated,omitempty"`
	UpdatedAt     null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *accountPubkeyFeeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accountPubkeyFeeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccountPubkeyFeeColumns = struct {
	ID            string
	WalletAddress string
	Account       string
	IsAllocated   string
	UpdatedAt     string
}{
	ID:            "id",
	WalletAddress: "wallet_address",
	Account:       "account",
	IsAllocated:   "is_allocated",
	UpdatedAt:     "updated_at",
}

// Generated where

var AccountPubkeyFeeWhere = struct {
	ID            whereHelperuint64
	WalletAddress whereHelperstring
	Account       whereHelperstring
	IsAllocated   whereHelpernull_Bool
	UpdatedAt     whereHelpernull_Time
}{
	ID:            whereHelperuint64{field: "`account_pubkey_fee`.`id`"},
	WalletAddress: whereHelperstring{field: "`account_pubkey_fee`.`wallet_address`"},
	Account:       whereHelperstring{field: "`account_pubkey_fee`.`account`"},
	IsAllocated:   whereHelpernull_Bool{field: "`account_pubkey_fee`.`is_allocated`"},
	UpdatedAt:     whereHelpernull_Time{field: "`account_pubkey_fee`.`updated_at`"},
}

// AccountPubkeyFeeRels is where relationship names are stored.
var AccountPubkeyFeeRels = struct {
}{}

// accountPubkeyFeeR is where relationships are stored.
type accountPubkeyFeeR struct {
}

// NewStruct creates a new relationship struct
func (*accountPubkeyFeeR) NewStruct() *accountPubkeyFeeR {
	return &accountPubkeyFeeR{}
}

// accountPubkeyFeeL is where Load methods for each relationship are stored.
type accountPubkeyFeeL struct{}

var (
	accountPubkeyFeeAllColumns            = []string{"id", "wallet_address", "account", "is_allocated", "updated_at"}
	accountPubkeyFeeColumnsWithoutDefault = []string{"wallet_address", "account"}
	accountPubkeyFeeColumnsWithDefault    = []string{"id", "is_allocated", "updated_at"}
	accountPubkeyFeePrimaryKeyColumns     = []string{"id"}
)

type (
	// AccountPubkeyFeeSlice is an alias for a slice of pointers to AccountPubkeyFee.
	// This should generally be used opposed to []AccountPubkeyFee.
	AccountPubkeyFeeSlice []*AccountPubkeyFee

	accountPubkeyFeeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accountPubkeyFeeType                 = reflect.TypeOf(&AccountPubkeyFee{})
	accountPubkeyFeeMapping              = queries.MakeStructMapping(accountPubkeyFeeType)
	accountPubkeyFeePrimaryKeyMapping, _ = queries.BindMapping(accountPubkeyFeeType, accountPubkeyFeeMapping, accountPubkeyFeePrimaryKeyColumns)
	accountPubkeyFeeInsertCacheMut       sync.RWMutex
	accountPubkeyFeeInsertCache          = make(map[string]insertCache)
	accountPubkeyFeeUpdateCacheMut       sync.RWMutex
	accountPubkeyFeeUpdateCache          = make(map[string]updateCache)
	accountPubkeyFeeUpsertCacheMut       sync.RWMutex
	accountPubkeyFeeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single accountPubkeyFee record from the query.
func (q accountPubkeyFeeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccountPubkeyFee, error) {
	o := &AccountPubkeyFee{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for account_pubkey_fee")
	}

	return o, nil
}

// All returns all AccountPubkeyFee records from the query.
func (q accountPubkeyFeeQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccountPubkeyFeeSlice, error) {
	var o []*AccountPubkeyFee

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AccountPubkeyFee slice")
	}

	return o, nil
}

// Count returns the count of all AccountPubkeyFee records in the query.
func (q accountPubkeyFeeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count account_pubkey_fee rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q accountPubkeyFeeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if account_pubkey_fee exists")
	}

	return count > 0, nil
}

// AccountPubkeyFees retrieves all the records using an executor.
func AccountPubkeyFees(mods ...qm.QueryMod) accountPubkeyFeeQuery {
	mods = append(mods, qm.From("`account_pubkey_fee`"))
	return accountPubkeyFeeQuery{NewQuery(mods...)}
}

// FindAccountPubkeyFee retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccountPubkeyFee(ctx context.Context, exec boil.ContextExecutor, iD uint64, selectCols ...string) (*AccountPubkeyFee, error) {
	accountPubkeyFeeObj := &AccountPubkeyFee{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `account_pubkey_fee` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, accountPubkeyFeeObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from account_pubkey_fee")
	}

	return accountPubkeyFeeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccountPubkeyFee) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no account_pubkey_fee provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(accountPubkeyFeeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accountPubkeyFeeInsertCacheMut.RLock()
	cache, cached := accountPubkeyFeeInsertCache[key]
	accountPubkeyFeeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accountPubkeyFeeAllColumns,
			accountPubkeyFeeColumnsWithDefault,
			accountPubkeyFeeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accountPubkeyFeeType, accountPubkeyFeeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accountPubkeyFeeType, accountPubkeyFeeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `account_pubkey_fee` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `account_pubkey_fee` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `account_pubkey_fee` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, accountPubkeyFeePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into account_pubkey_fee")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == accountPubkeyFeeMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for account_pubkey_fee")
	}

CacheNoHooks:
	if !cached {
		accountPubkeyFeeInsertCacheMut.Lock()
		accountPubkeyFeeInsertCache[key] = cache
		accountPubkeyFeeInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the AccountPubkeyFee.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccountPubkeyFee) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	key := makeCacheKey(columns, nil)
	accountPubkeyFeeUpdateCacheMut.RLock()
	cache, cached := accountPubkeyFeeUpdateCache[key]
	accountPubkeyFeeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accountPubkeyFeeAllColumns,
			accountPubkeyFeePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update account_pubkey_fee, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `account_pubkey_fee` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, accountPubkeyFeePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accountPubkeyFeeType, accountPubkeyFeeMapping, append(wl, accountPubkeyFeePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update account_pubkey_fee row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for account_pubkey_fee")
	}

	if !cached {
		accountPubkeyFeeUpdateCacheMut.Lock()
		accountPubkeyFeeUpdateCache[key] = cache
		accountPubkeyFeeUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q accountPubkeyFeeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for account_pubkey_fee")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for account_pubkey_fee")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccountPubkeyFeeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountPubkeyFeePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `account_pubkey_fee` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, accountPubkeyFeePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in accountPubkeyFee slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all accountPubkeyFee")
	}
	return rowsAff, nil
}

var mySQLAccountPubkeyFeeUniqueColumns = []string{
	"id",
	"wallet_address",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AccountPubkeyFee) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no account_pubkey_fee provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	nzDefaults := queries.NonZeroDefaultSet(accountPubkeyFeeColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLAccountPubkeyFeeUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accountPubkeyFeeUpsertCacheMut.RLock()
	cache, cached := accountPubkeyFeeUpsertCache[key]
	accountPubkeyFeeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			accountPubkeyFeeAllColumns,
			accountPubkeyFeeColumnsWithDefault,
			accountPubkeyFeeColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			accountPubkeyFeeAllColumns,
			accountPubkeyFeePrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert account_pubkey_fee, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "account_pubkey_fee", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `account_pubkey_fee` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(accountPubkeyFeeType, accountPubkeyFeeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accountPubkeyFeeType, accountPubkeyFeeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for account_pubkey_fee")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == accountPubkeyFeeMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(accountPubkeyFeeType, accountPubkeyFeeMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for account_pubkey_fee")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for account_pubkey_fee")
	}

CacheNoHooks:
	if !cached {
		accountPubkeyFeeUpsertCacheMut.Lock()
		accountPubkeyFeeUpsertCache[key] = cache
		accountPubkeyFeeUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single AccountPubkeyFee record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccountPubkeyFee) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AccountPubkeyFee provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accountPubkeyFeePrimaryKeyMapping)
	sql := "DELETE FROM `account_pubkey_fee` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from account_pubkey_fee")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for account_pubkey_fee")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q accountPubkeyFeeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no accountPubkeyFeeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from account_pubkey_fee")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for account_pubkey_fee")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccountPubkeyFeeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountPubkeyFeePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `account_pubkey_fee` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, accountPubkeyFeePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from accountPubkeyFee slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for account_pubkey_fee")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccountPubkeyFee) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccountPubkeyFee(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountPubkeyFeeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccountPubkeyFeeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountPubkeyFeePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `account_pubkey_fee`.* FROM `account_pubkey_fee` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, accountPubkeyFeePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AccountPubkeyFeeSlice")
	}

	*o = slice

	return nil
}

// AccountPubkeyFeeExists checks if the AccountPubkeyFee row exists.
func AccountPubkeyFeeExists(ctx context.Context, exec boil.ContextExecutor, iD uint64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `account_pubkey_fee` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if account_pubkey_fee exists")
	}

	return exists, nil
}
