// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// AccountPubkeyQuoine is an object representing the database table.
type AccountPubkeyQuoine struct {
	ID            uint64    `boil:"id" json:"id" toml:"id" yaml:"id"`
	WalletAddress string    `boil:"wallet_address" json:"wallet_address" toml:"wallet_address" yaml:"wallet_address"`
	Account       string    `boil:"account" json:"account" toml:"account" yaml:"account"`
	IsAllocated   null.Bool `boil:"is_allocated" json:"is_allocated,omitempty" toml:"is_allocated" yaml:"is_allocated,omitempty"`
	UpdatedAt     null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *accountPubkeyQuoineR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accountPubkeyQuoineL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccountPubkeyQuoineColumns = struct {
	ID            string
	WalletAddress string
	Account       string
	IsAllocated   string
	UpdatedAt     string
}{
	ID:            "id",
	WalletAddress: "wallet_address",
	Account:       "account",
	IsAllocated:   "is_allocated",
	UpdatedAt:     "updated_at",
}

// Generated where

var AccountPubkeyQuoineWhere = struct {
	ID            whereHelperuint64
	WalletAddress whereHelperstring
	Account       whereHelperstring
	IsAllocated   whereHelpernull_Bool
	UpdatedAt     whereHelpernull_Time
}{
	ID:            whereHelperuint64{field: "`account_pubkey_quoine`.`id`"},
	WalletAddress: whereHelperstring{field: "`account_pubkey_quoine`.`wallet_address`"},
	Account:       whereHelperstring{field: "`account_pubkey_quoine`.`account`"},
	IsAllocated:   whereHelpernull_Bool{field: "`account_pubkey_quoine`.`is_allocated`"},
	UpdatedAt:     whereHelpernull_Time{field: "`account_pubkey_quoine`.`updated_at`"},
}

// AccountPubkeyQuoineRels is where relationship names are stored.
var AccountPubkeyQuoineRels = struct {
}{}

// accountPubkeyQuoineR is where relationships are stored.
type accountPubkeyQuoineR struct {
}

// NewStruct creates a new relationship struct
func (*accountPubkeyQuoineR) NewStruct() *accountPubkeyQuoineR {
	return &accountPubkeyQuoineR{}
}

// accountPubkeyQuoineL is where Load methods for each relationship are stored.
type accountPubkeyQuoineL struct{}

var (
	accountPubkeyQuoineAllColumns            = []string{"id", "wallet_address", "account", "is_allocated", "updated_at"}
	accountPubkeyQuoineColumnsWithoutDefault = []string{"wallet_address", "account"}
	accountPubkeyQuoineColumnsWithDefault    = []string{"id", "is_allocated", "updated_at"}
	accountPubkeyQuoinePrimaryKeyColumns     = []string{"id"}
)

type (
	// AccountPubkeyQuoineSlice is an alias for a slice of pointers to AccountPubkeyQuoine.
	// This should generally be used opposed to []AccountPubkeyQuoine.
	AccountPubkeyQuoineSlice []*AccountPubkeyQuoine

	accountPubkeyQuoineQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accountPubkeyQuoineType                 = reflect.TypeOf(&AccountPubkeyQuoine{})
	accountPubkeyQuoineMapping              = queries.MakeStructMapping(accountPubkeyQuoineType)
	accountPubkeyQuoinePrimaryKeyMapping, _ = queries.BindMapping(accountPubkeyQuoineType, accountPubkeyQuoineMapping, accountPubkeyQuoinePrimaryKeyColumns)
	accountPubkeyQuoineInsertCacheMut       sync.RWMutex
	accountPubkeyQuoineInsertCache          = make(map[string]insertCache)
	accountPubkeyQuoineUpdateCacheMut       sync.RWMutex
	accountPubkeyQuoineUpdateCache          = make(map[string]updateCache)
	accountPubkeyQuoineUpsertCacheMut       sync.RWMutex
	accountPubkeyQuoineUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single accountPubkeyQuoine record from the query.
func (q accountPubkeyQuoineQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccountPubkeyQuoine, error) {
	o := &AccountPubkeyQuoine{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for account_pubkey_quoine")
	}

	return o, nil
}

// All returns all AccountPubkeyQuoine records from the query.
func (q accountPubkeyQuoineQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccountPubkeyQuoineSlice, error) {
	var o []*AccountPubkeyQuoine

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AccountPubkeyQuoine slice")
	}

	return o, nil
}

// Count returns the count of all AccountPubkeyQuoine records in the query.
func (q accountPubkeyQuoineQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count account_pubkey_quoine rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q accountPubkeyQuoineQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if account_pubkey_quoine exists")
	}

	return count > 0, nil
}

// AccountPubkeyQuoines retrieves all the records using an executor.
func AccountPubkeyQuoines(mods ...qm.QueryMod) accountPubkeyQuoineQuery {
	mods = append(mods, qm.From("`account_pubkey_quoine`"))
	return accountPubkeyQuoineQuery{NewQuery(mods...)}
}

// FindAccountPubkeyQuoine retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccountPubkeyQuoine(ctx context.Context, exec boil.ContextExecutor, iD uint64, selectCols ...string) (*AccountPubkeyQuoine, error) {
	accountPubkeyQuoineObj := &AccountPubkeyQuoine{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `account_pubkey_quoine` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, accountPubkeyQuoineObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from account_pubkey_quoine")
	}

	return accountPubkeyQuoineObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccountPubkeyQuoine) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no account_pubkey_quoine provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(accountPubkeyQuoineColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accountPubkeyQuoineInsertCacheMut.RLock()
	cache, cached := accountPubkeyQuoineInsertCache[key]
	accountPubkeyQuoineInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accountPubkeyQuoineAllColumns,
			accountPubkeyQuoineColumnsWithDefault,
			accountPubkeyQuoineColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accountPubkeyQuoineType, accountPubkeyQuoineMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accountPubkeyQuoineType, accountPubkeyQuoineMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `account_pubkey_quoine` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `account_pubkey_quoine` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `account_pubkey_quoine` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, accountPubkeyQuoinePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into account_pubkey_quoine")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == accountPubkeyQuoineMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for account_pubkey_quoine")
	}

CacheNoHooks:
	if !cached {
		accountPubkeyQuoineInsertCacheMut.Lock()
		accountPubkeyQuoineInsertCache[key] = cache
		accountPubkeyQuoineInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the AccountPubkeyQuoine.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccountPubkeyQuoine) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	key := makeCacheKey(columns, nil)
	accountPubkeyQuoineUpdateCacheMut.RLock()
	cache, cached := accountPubkeyQuoineUpdateCache[key]
	accountPubkeyQuoineUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accountPubkeyQuoineAllColumns,
			accountPubkeyQuoinePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update account_pubkey_quoine, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `account_pubkey_quoine` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, accountPubkeyQuoinePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accountPubkeyQuoineType, accountPubkeyQuoineMapping, append(wl, accountPubkeyQuoinePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update account_pubkey_quoine row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for account_pubkey_quoine")
	}

	if !cached {
		accountPubkeyQuoineUpdateCacheMut.Lock()
		accountPubkeyQuoineUpdateCache[key] = cache
		accountPubkeyQuoineUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q accountPubkeyQuoineQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for account_pubkey_quoine")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for account_pubkey_quoine")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccountPubkeyQuoineSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountPubkeyQuoinePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `account_pubkey_quoine` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, accountPubkeyQuoinePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in accountPubkeyQuoine slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all accountPubkeyQuoine")
	}
	return rowsAff, nil
}

var mySQLAccountPubkeyQuoineUniqueColumns = []string{
	"id",
	"wallet_address",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AccountPubkeyQuoine) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no account_pubkey_quoine provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	nzDefaults := queries.NonZeroDefaultSet(accountPubkeyQuoineColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLAccountPubkeyQuoineUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accountPubkeyQuoineUpsertCacheMut.RLock()
	cache, cached := accountPubkeyQuoineUpsertCache[key]
	accountPubkeyQuoineUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			accountPubkeyQuoineAllColumns,
			accountPubkeyQuoineColumnsWithDefault,
			accountPubkeyQuoineColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			accountPubkeyQuoineAllColumns,
			accountPubkeyQuoinePrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert account_pubkey_quoine, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "account_pubkey_quoine", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `account_pubkey_quoine` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(accountPubkeyQuoineType, accountPubkeyQuoineMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accountPubkeyQuoineType, accountPubkeyQuoineMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for account_pubkey_quoine")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == accountPubkeyQuoineMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(accountPubkeyQuoineType, accountPubkeyQuoineMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for account_pubkey_quoine")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for account_pubkey_quoine")
	}

CacheNoHooks:
	if !cached {
		accountPubkeyQuoineUpsertCacheMut.Lock()
		accountPubkeyQuoineUpsertCache[key] = cache
		accountPubkeyQuoineUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single AccountPubkeyQuoine record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccountPubkeyQuoine) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AccountPubkeyQuoine provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accountPubkeyQuoinePrimaryKeyMapping)
	sql := "DELETE FROM `account_pubkey_quoine` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from account_pubkey_quoine")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for account_pubkey_quoine")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q accountPubkeyQuoineQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no accountPubkeyQuoineQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from account_pubkey_quoine")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for account_pubkey_quoine")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccountPubkeyQuoineSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountPubkeyQuoinePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `account_pubkey_quoine` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, accountPubkeyQuoinePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from accountPubkeyQuoine slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for account_pubkey_quoine")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccountPubkeyQuoine) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccountPubkeyQuoine(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountPubkeyQuoineSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccountPubkeyQuoineSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountPubkeyQuoinePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `account_pubkey_quoine`.* FROM `account_pubkey_quoine` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, accountPubkeyQuoinePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AccountPubkeyQuoineSlice")
	}

	*o = slice

	return nil
}

// AccountPubkeyQuoineExists checks if the AccountPubkeyQuoine row exists.
func AccountPubkeyQuoineExists(ctx context.Context, exec boil.ContextExecutor, iD uint64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `account_pubkey_quoine` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if account_pubkey_quoine exists")
	}

	return exists, nil
}
