# syntax=docker/dockerfile:1

# This file demonstrates a basic build pattern without an explicit `go mod download` step

# It's less efficient for iterative builds as it doesn't leverage Docker layer caching for Go modules

############################

# 1) build

# Note: set sha checked by `docker pull golang:1.26.2 && docker inspect`

############################
# FROM golang:1.26.2 AS build
FROM golang:1.26.2@sha256:ce63a16e0f7063787ebb4eb28e72d477b00b4726f79874b3205a965ffd797ab2 AS build
WORKDIR /src

# COPY cmd pkg internal ./
COPY go.mod go.sum ./
COPY cmd/ ./cmd/
COPY internal/ ./internal/
COPY pkg/ ./pkg/

ARG CMD_PATH=cmd/watch
ARG APP_VERSION=dev

# go build

RUN CGO_ENABLED=0 GOOS=linux \
    go build -trimpath \
      -ldflags="-s -w -X main.appVersion=${APP_VERSION}" \
      -o /out/app ./${CMD_PATH}

############################

# 2) runtime: minimal image

############################
FROM gcr.io/distroless/static-debian12:nonroot AS runtime
WORKDIR /
COPY --from=build /out/app /app
USER nonroot:nonroot
ENTRYPOINT ["/app"]
