# syntax=docker/dockerfile:1

# use BuildKit bind mounts

############################
# 1) build
# Note: set sha checked by `docker pull golang:1.26.2 && docker inspect`
############################
#FROM golang:1.26.2 AS build
FROM golang:1.26.2@sha256:ce63a16e0f7063787ebb4eb28e72d477b00b4726f79874b3205a965ffd797ab2 AS build
WORKDIR /src

RUN --mount=type=bind,source=go.mod,target=/src/go.mod,ro \
    --mount=type=bind,source=go.sum,target=/src/go.sum,ro \
    go mod download

# Which cmd to build (e.g. cmd/watch)
ARG CMD_PATH=cmd/watch
ARG APP_VERSION=dev

WORKDIR /src

# go build
RUN --mount=type=bind,source=.,target=/src,ro \
    --mount=type=bind,source=.git,target=/src/.git,ro \
    CGO_ENABLED=0 GOOS=linux \
    go build -trimpath \
      -ldflags="-s -w -X main.appVersion==${APP_VERSION}" \
      -o /out/app ./${CMD_PATH}

############################
# 2) runtime: minimal image
############################
FROM gcr.io/distroless/static-debian12:nonroot AS runtime
WORKDIR /
COPY --from=build /out/app /app
USER nonroot:nonroot
ENTRYPOINT ["/app"]
