# syntax=docker/dockerfile:1


############################
# 1) build: resolve git tag + build selected cmd
############################
FROM golang:1.25.6 AS build
WORKDIR /src

# go mod download (cacheable)
COPY go.mod go.sum ./
RUN go mod download

ARG CMD_PATH=cmd/watch
ARG APP_VERSION_VAR=main.appVersion

# copy source (it may require .git as well)
COPY . .

# go build
RUN APP_VERSION="$(git describe --tags --abbrev=0 2>/dev/null || echo dev)" && \
    echo "Building ${CMD_PATH} with version=${APP_VERSION}" && \
    CGO_ENABLED=0 GOOS=linux \
    go build -trimpath \
      -ldflags="-s -w -X ${APP_VERSION_VAR}=${APP_VERSION}" \
      -o /out/app ./${CMD_PATH}

############################
# 2) runtime: minimal image
############################
FROM gcr.io/distroless/static-debian12:nonroot AS runtime
WORKDIR /
COPY --from=build /out/app /app
USER nonroot:nonroot
ENTRYPOINT ["/app"]
