# syntax=docker/dockerfile:1

############################
# 1) build: resolve git tag + build selected cmd
# Note: set sha checked by `docker pull golang:1.25.6 && docker inspect`
############################
#FROM golang:1.25.6 AS build
FROM golang:1.25.6@sha256:ce63a16e0f7063787ebb4eb28e72d477b00b4726f79874b3205a965ffd797ab2 AS build
WORKDIR /src

# go mod download (cacheable but extracting cost may be high)
COPY go.mod go.sum ./
RUN --mount=type=cache,id=go-mod,target=/go/pkg/mod,sharing=locked \
    go mod download

ARG CMD_PATH=cmd/watch

# copy source (it may require .git as well)
COPY . .

# go build
RUN --mount=type=cache,id=go-mod,target=/go/pkg/mod,sharing=locked \
    --mount=type=cache,id=go-build,target=/root/.cache/go-build,sharing=locked \
    APP_VERSION="$(git describe --tags --abbrev=0 2>/dev/null || echo dev)" && \
    echo "Building ${CMD_PATH} with version=${APP_VERSION}" && \
    CGO_ENABLED=0 GOOS=linux \
    go build -trimpath \
      -ldflags="-s -w -X main.appVersion=${APP_VERSION}" \
      -o /out/app ./${CMD_PATH}

############################
# 2) runtime: minimal image
############################
FROM gcr.io/distroless/static-debian12:nonroot AS runtime
WORKDIR /
COPY --from=build /out/app /app
USER nonroot:nonroot
ENTRYPOINT ["/app"]
