// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccountKey     string
	Address        string
	AuthAccountKey string
	AuthFullpubkey string
	PaymentRequest string
	Seed           string
	TX             string
	TXInput        string
	TXOutput       string
}{
	AccountKey:     "account_key",
	Address:        "address",
	AuthAccountKey: "auth_account_key",
	AuthFullpubkey: "auth_fullpubkey",
	PaymentRequest: "payment_request",
	Seed:           "seed",
	TX:             "tx",
	TXInput:        "tx_input",
	TXOutput:       "tx_output",
}
