// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// MultisigHistory is an object representing the database table.
type MultisigHistory struct {
	ID              int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	Coin            string    `boil:"coin" json:"coin" toml:"coin" yaml:"coin"`
	Account         string    `boil:"account" json:"account" toml:"account" yaml:"account"`
	FullPublicKey   string    `boil:"full_public_key" json:"full_public_key" toml:"full_public_key" yaml:"full_public_key"`
	AuthAddress1    string    `boil:"auth_address1" json:"auth_address1" toml:"auth_address1" yaml:"auth_address1"`
	AuthAddress2    string    `boil:"auth_address2" json:"auth_address2" toml:"auth_address2" yaml:"auth_address2"`
	AuthAddress3    string    `boil:"auth_address3" json:"auth_address3" toml:"auth_address3" yaml:"auth_address3"`
	MultisigAddress string    `boil:"multisig_address" json:"multisig_address" toml:"multisig_address" yaml:"multisig_address"`
	RedeemScript    string    `boil:"redeem_script" json:"redeem_script" toml:"redeem_script" yaml:"redeem_script"`
	IsExported      bool      `boil:"is_exported" json:"is_exported" toml:"is_exported" yaml:"is_exported"`
	UpdatedAt       null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *multisigHistoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L multisigHistoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MultisigHistoryColumns = struct {
	ID              string
	Coin            string
	Account         string
	FullPublicKey   string
	AuthAddress1    string
	AuthAddress2    string
	AuthAddress3    string
	MultisigAddress string
	RedeemScript    string
	IsExported      string
	UpdatedAt       string
}{
	ID:              "id",
	Coin:            "coin",
	Account:         "account",
	FullPublicKey:   "full_public_key",
	AuthAddress1:    "auth_address1",
	AuthAddress2:    "auth_address2",
	AuthAddress3:    "auth_address3",
	MultisigAddress: "multisig_address",
	RedeemScript:    "redeem_script",
	IsExported:      "is_exported",
	UpdatedAt:       "updated_at",
}

// Generated where

var MultisigHistoryWhere = struct {
	ID              whereHelperint64
	Coin            whereHelperstring
	Account         whereHelperstring
	FullPublicKey   whereHelperstring
	AuthAddress1    whereHelperstring
	AuthAddress2    whereHelperstring
	AuthAddress3    whereHelperstring
	MultisigAddress whereHelperstring
	RedeemScript    whereHelperstring
	IsExported      whereHelperbool
	UpdatedAt       whereHelpernull_Time
}{
	ID:              whereHelperint64{field: "`multisig_history`.`id`"},
	Coin:            whereHelperstring{field: "`multisig_history`.`coin`"},
	Account:         whereHelperstring{field: "`multisig_history`.`account`"},
	FullPublicKey:   whereHelperstring{field: "`multisig_history`.`full_public_key`"},
	AuthAddress1:    whereHelperstring{field: "`multisig_history`.`auth_address1`"},
	AuthAddress2:    whereHelperstring{field: "`multisig_history`.`auth_address2`"},
	AuthAddress3:    whereHelperstring{field: "`multisig_history`.`auth_address3`"},
	MultisigAddress: whereHelperstring{field: "`multisig_history`.`multisig_address`"},
	RedeemScript:    whereHelperstring{field: "`multisig_history`.`redeem_script`"},
	IsExported:      whereHelperbool{field: "`multisig_history`.`is_exported`"},
	UpdatedAt:       whereHelpernull_Time{field: "`multisig_history`.`updated_at`"},
}

// MultisigHistoryRels is where relationship names are stored.
var MultisigHistoryRels = struct {
}{}

// multisigHistoryR is where relationships are stored.
type multisigHistoryR struct {
}

// NewStruct creates a new relationship struct
func (*multisigHistoryR) NewStruct() *multisigHistoryR {
	return &multisigHistoryR{}
}

// multisigHistoryL is where Load methods for each relationship are stored.
type multisigHistoryL struct{}

var (
	multisigHistoryAllColumns            = []string{"id", "coin", "account", "full_public_key", "auth_address1", "auth_address2", "auth_address3", "multisig_address", "redeem_script", "is_exported", "updated_at"}
	multisigHistoryColumnsWithoutDefault = []string{"coin", "account", "full_public_key", "auth_address1", "auth_address2", "auth_address3", "multisig_address", "redeem_script"}
	multisigHistoryColumnsWithDefault    = []string{"id", "is_exported", "updated_at"}
	multisigHistoryPrimaryKeyColumns     = []string{"id"}
)

type (
	// MultisigHistorySlice is an alias for a slice of pointers to MultisigHistory.
	// This should generally be used opposed to []MultisigHistory.
	MultisigHistorySlice []*MultisigHistory

	multisigHistoryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	multisigHistoryType                 = reflect.TypeOf(&MultisigHistory{})
	multisigHistoryMapping              = queries.MakeStructMapping(multisigHistoryType)
	multisigHistoryPrimaryKeyMapping, _ = queries.BindMapping(multisigHistoryType, multisigHistoryMapping, multisigHistoryPrimaryKeyColumns)
	multisigHistoryInsertCacheMut       sync.RWMutex
	multisigHistoryInsertCache          = make(map[string]insertCache)
	multisigHistoryUpdateCacheMut       sync.RWMutex
	multisigHistoryUpdateCache          = make(map[string]updateCache)
	multisigHistoryUpsertCacheMut       sync.RWMutex
	multisigHistoryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single multisigHistory record from the query.
func (q multisigHistoryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MultisigHistory, error) {
	o := &MultisigHistory{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for multisig_history")
	}

	return o, nil
}

// All returns all MultisigHistory records from the query.
func (q multisigHistoryQuery) All(ctx context.Context, exec boil.ContextExecutor) (MultisigHistorySlice, error) {
	var o []*MultisigHistory

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MultisigHistory slice")
	}

	return o, nil
}

// Count returns the count of all MultisigHistory records in the query.
func (q multisigHistoryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count multisig_history rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q multisigHistoryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if multisig_history exists")
	}

	return count > 0, nil
}

// MultisigHistories retrieves all the records using an executor.
func MultisigHistories(mods ...qm.QueryMod) multisigHistoryQuery {
	mods = append(mods, qm.From("`multisig_history`"))
	return multisigHistoryQuery{NewQuery(mods...)}
}

// FindMultisigHistory retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMultisigHistory(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*MultisigHistory, error) {
	multisigHistoryObj := &MultisigHistory{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `multisig_history` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, multisigHistoryObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from multisig_history")
	}

	return multisigHistoryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MultisigHistory) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no multisig_history provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(multisigHistoryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	multisigHistoryInsertCacheMut.RLock()
	cache, cached := multisigHistoryInsertCache[key]
	multisigHistoryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			multisigHistoryAllColumns,
			multisigHistoryColumnsWithDefault,
			multisigHistoryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(multisigHistoryType, multisigHistoryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(multisigHistoryType, multisigHistoryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `multisig_history` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `multisig_history` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `multisig_history` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, multisigHistoryPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into multisig_history")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == multisigHistoryMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for multisig_history")
	}

CacheNoHooks:
	if !cached {
		multisigHistoryInsertCacheMut.Lock()
		multisigHistoryInsertCache[key] = cache
		multisigHistoryInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the MultisigHistory.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MultisigHistory) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	key := makeCacheKey(columns, nil)
	multisigHistoryUpdateCacheMut.RLock()
	cache, cached := multisigHistoryUpdateCache[key]
	multisigHistoryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			multisigHistoryAllColumns,
			multisigHistoryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update multisig_history, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `multisig_history` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, multisigHistoryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(multisigHistoryType, multisigHistoryMapping, append(wl, multisigHistoryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update multisig_history row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for multisig_history")
	}

	if !cached {
		multisigHistoryUpdateCacheMut.Lock()
		multisigHistoryUpdateCache[key] = cache
		multisigHistoryUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q multisigHistoryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for multisig_history")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for multisig_history")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MultisigHistorySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), multisigHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `multisig_history` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, multisigHistoryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in multisigHistory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all multisigHistory")
	}
	return rowsAff, nil
}

var mySQLMultisigHistoryUniqueColumns = []string{
	"id",
	"full_public_key",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MultisigHistory) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no multisig_history provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	nzDefaults := queries.NonZeroDefaultSet(multisigHistoryColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLMultisigHistoryUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	multisigHistoryUpsertCacheMut.RLock()
	cache, cached := multisigHistoryUpsertCache[key]
	multisigHistoryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			multisigHistoryAllColumns,
			multisigHistoryColumnsWithDefault,
			multisigHistoryColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			multisigHistoryAllColumns,
			multisigHistoryPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert multisig_history, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "multisig_history", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `multisig_history` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(multisigHistoryType, multisigHistoryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(multisigHistoryType, multisigHistoryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for multisig_history")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == multisigHistoryMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(multisigHistoryType, multisigHistoryMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for multisig_history")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for multisig_history")
	}

CacheNoHooks:
	if !cached {
		multisigHistoryUpsertCacheMut.Lock()
		multisigHistoryUpsertCache[key] = cache
		multisigHistoryUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single MultisigHistory record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MultisigHistory) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MultisigHistory provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), multisigHistoryPrimaryKeyMapping)
	sql := "DELETE FROM `multisig_history` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from multisig_history")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for multisig_history")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q multisigHistoryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no multisigHistoryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from multisig_history")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for multisig_history")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MultisigHistorySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), multisigHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `multisig_history` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, multisigHistoryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from multisigHistory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for multisig_history")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MultisigHistory) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMultisigHistory(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MultisigHistorySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MultisigHistorySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), multisigHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `multisig_history`.* FROM `multisig_history` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, multisigHistoryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MultisigHistorySlice")
	}

	*o = slice

	return nil
}

// MultisigHistoryExists checks if the MultisigHistory row exists.
func MultisigHistoryExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `multisig_history` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if multisig_history exists")
	}

	return exists, nil
}

// InsertAll inserts all rows with the specified column values, using an executor.
func (o MultisigHistorySlice) InsertAll(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	var sql string
	vals := []interface{}{}
	for i, row := range o {
		if !boil.TimestampsAreSkipped(ctx) {
			currTime := time.Now().In(boil.GetLocation())

			if queries.MustTime(row.UpdatedAt).IsZero() {
				queries.SetScanner(&row.UpdatedAt, currTime)
			}
		}

		nzDefaults := queries.NonZeroDefaultSet(multisigHistoryColumnsWithDefault, row)
		wl, _ := columns.InsertColumnSet(
			multisigHistoryAllColumns,
			multisigHistoryColumnsWithDefault,
			multisigHistoryColumnsWithoutDefault,
			nzDefaults,
		)
		if i == 0 {
			sql = "INSERT INTO `multisig_history` " + "(`" + strings.Join(wl, "`,`") + "`)" + " VALUES "
		}
		sql += strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), len(vals)+1, len(wl))
		if i != len(o)-1 {
			sql += ","
		}
		valMapping, err := queries.BindMapping(multisigHistoryType, multisigHistoryMapping, wl)
		if err != nil {
			return err
		}
		value := reflect.Indirect(reflect.ValueOf(row))
		vals = append(vals, queries.ValuesFromMapping(value, valMapping)...)
	}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, vals...)
	}

	_, err := exec.ExecContext(ctx, sql, vals...)
	if err != nil {
		return errors.Wrap(err, "models: unable to insert into multisig_history")
	}

	return nil
}
