#!/usr/bin/env bash

# XRP E2E Workflow Script - Pattern 2: 2-of-2 Multisig Payment Transfer
# This script automates the complete XRP multi-signature transaction flow:
#   keygen seed/key → address export → watch address import →
#   fund sender + signer accounts → set-signer-list → sign SignerListSet →
#   submit SignerListSet → create multisig payment TX →
#   sign1 (keygen) → sign2 (keygen as second signer) → watch send → ledger_accept → verify
#
# Usage: ./scripts/operation/xrp/e2e/e2e-p2.sh [OPTIONS]
#
# Options:
#   --cleanup           Stop containers and cleanup state
#   --reset             Full reset and run from scratch
#   --verbose           Enable verbose output (set -x)
#   --non-interactive   Run without prompts (for CI/CD)
#   -h, --help          Display this help message
#
# Transaction Pattern:
#   Pattern 2: XRP 2-of-2 multisig payment transfer
#   - Address Type: XRP classic address (ed25519 or secp256k1)
#   - Address Format: r... (base58)
#   - Multisig: Signer list with 2 authorized signers (quorum=2)
#   - Signing: Keygen wallet (first signer) + Keygen wallet second DB (second signer)
#
# Account Setup:
#   - PAYMENT_ACCOUNT: "payment" — multisig sender; holds the SignerList
#   - CLIENT_ACCOUNT:  "deposit" — receiver of the multisig payment
#   - SIGNER1: first "signer" account generated by keygen (used as signer in SignerList)
#   - SIGNER2: second "signer" account generated by a separate keygen DB
#
# Signing Architecture:
#   The XRP multisig signing flow uses the sign wallet's JSON-format signer
#   (sign/xrp/sign_transaction.go). However, the sign wallet binary does not yet
#   support XRP coin (NewSigner returns "not implemented" for XRP).
#   As a workaround, this test uses the keygen wallet for Sign 1 and documents
#   the intended Sign 2 command. Full end-to-end execution requires:
#     1. Enable XRP support in the sign wallet (NewSigner in container.go)
#     2. Update keygen sign use case to detect and handle JSON format files
#   Until then, the signing steps are validated at the file-structure level via jq.
#
# Environment Variables:
#   DB_TYPE       Database type: sqlite (default) or mysql
#   XRP_WS_HOST   rippled WebSocket host (default: 127.0.0.1)
#   XRP_WS_PORT   rippled WebSocket port (default: 6006)
#
# Required Config:
#   config/wallet/xrp/watch.yaml:  ripple.websocket_public_url overridden by XRP_WS_HOST:XRP_WS_PORT
#   config/wallet/xrp/keygen.yaml: ripple.offline_keygen: true
#
# Infrastructure:
#   rippled v3.1.0 standalone mode (compose.xrp.yaml)
#   WebSocket admin port 6006 (ws://) — direct connection, no xrpl-grpc-server
#   Ledger must be manually advanced via 'rippled ledger_accept' after each tx

set -euo pipefail

###############################################################################
# Script Configuration
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source the XRP common utilities (which also sources common.sh)
# shellcheck source=../xrp_common.sh
source "${SCRIPT_DIR}/../xrp_common.sh"

# Pattern identifier for DB isolation
export E2E_PATTERN="p2"

# Re-initialize database with correct pattern now that E2E_PATTERN is set
xrp_init_database

###############################################################################
# Configuration
###############################################################################

xrp_get_config_paths

# Number of HD keys to generate per account
KEY_NUM=5

# Accounts used in this E2E test
PAYMENT_ACCOUNT="payment" # Multisig sender
CLIENT_ACCOUNT="deposit"  # Payment receiver

# XRP amounts
FUNDING_AMOUNT_PAYMENT_XRP=200 # Fund payment (multisig sender) — needs extra for signer fees
FUNDING_AMOUNT_CLIENT_XRP=10   # Fund deposit account (activate with base reserve)
TRANSFER_AMOUNT_XRP=50.0       # Transfer amount for the multisig payment

# Multisig configuration
MULTISIG_QUORUM=2 # Require 2-of-2 signatures

###############################################################################
# Argument Parsing
###############################################################################

MODE="run"
VERBOSE=false
NON_INTERACTIVE=false

show_help() {
	cat <<EOF
XRP E2E Workflow Script - Pattern 2: 2-of-2 Multisig Payment Transfer

Usage: $0 [OPTIONS]

Options:
  --cleanup           Stop containers and cleanup state
  --reset             Full reset and run from scratch
  --verbose           Enable verbose output
  --non-interactive   Run without prompts (for CI/CD)
  -h, --help          Display this help message

Examples:
  $0               # Run E2E workflow
  $0 --reset       # Fresh start with full reset
  $0 --verbose     # Run with detailed logging
  $0 --cleanup     # Stop containers and cleanup

Environment Variables:
  DB_TYPE       sqlite (default) | mysql
  XRP_WS_HOST   rippled WebSocket host (default: 127.0.0.1)
  XRP_WS_PORT   rippled WebSocket port (default: 6006)

EOF
	exit 0
}

while [[ $# -gt 0 ]]; do
	case $1 in
	--cleanup)
		MODE="cleanup"
		shift
		;;
	--reset)
		MODE="reset"
		shift
		;;
	--verbose)
		VERBOSE=true
		set -x
		shift
		;;
	--non-interactive)
		NON_INTERACTIVE=true
		shift
		;;
	-h | --help)
		show_help
		;;
	*)
		log_error "Unknown option: $1"
		show_help
		;;
	esac
done

###############################################################################
# Phase 1: Key Generation (Keygen wallet — offline)
###############################################################################

keygen_phase() {
	log_step "Key Generation Phase (Keygen wallet)"

	log_substep "Creating mnemonic seed"
	xrp_keygen_cmd -c "${XRP_CONFIG_KEYGEN}" --coin "${XRP_COIN}" create seed || {
		log_warn "Seed already exists or error, continuing..."
	}

	log_substep "Creating ${KEY_NUM} HD keys for '${PAYMENT_ACCOUNT}' account"
	xrp_keygen_cmd -c "${XRP_CONFIG_KEYGEN}" --coin "${XRP_COIN}" create hdkey \
		--account "${PAYMENT_ACCOUNT}" \
		--keynum "${KEY_NUM}"

	log_substep "Creating ${KEY_NUM} HD keys for '${CLIENT_ACCOUNT}' account"
	xrp_keygen_cmd -c "${XRP_CONFIG_KEYGEN}" --coin "${XRP_COIN}" create hdkey \
		--account "${CLIENT_ACCOUNT}" \
		--keynum "${KEY_NUM}"

	log_info "Key generation completed"
}

###############################################################################
# Phase 2: Address Export → Watch Address Import
###############################################################################

address_setup_phase() {
	log_step "Address Export (Keygen DB) → Watch Address Import Phase"

	for account in "${PAYMENT_ACCOUNT}" "${CLIENT_ACCOUNT}"; do
		log_substep "Exporting '${account}' addresses from keygen"
		local export_output
		export_output=$(xrp_keygen_cmd -c "${XRP_CONFIG_KEYGEN}" --coin "${XRP_COIN}" export address \
			--account "${account}" 2>&1) || {
			log_error "Failed to export addresses for '${account}'"
			log_error "Output: ${export_output}"
			return 1
		}

		local csv_file
		csv_file=$(xrp_extract_file_path "${export_output}")

		if [ -z "${csv_file}" ] || [ ! -f "${csv_file}" ]; then
			log_error "Failed to get address CSV for '${account}'"
			log_error "Output: ${export_output}"
			return 1
		fi
		log_info "  ${account} address CSV: ${csv_file}"

		log_substep "Importing '${account}' addresses into watch wallet"
		xrp_watch_cmd -c "${XRP_CONFIG_WATCH}" --coin "${XRP_COIN}" import address --file "${csv_file}"
	done

	log_info "Address setup completed"
}

###############################################################################
# Phase 3: Fund Addresses (from genesis account)
###############################################################################

funding_phase() {
	log_step "Funding Phase (from genesis account)"

	# Get payment address (multisig sender)
	local payment_addr
	payment_addr=$(xrp_get_address "${PAYMENT_ACCOUNT}")

	if [ -z "${payment_addr}" ]; then
		log_error "No '${PAYMENT_ACCOUNT}' address found in watch DB"
		log_error "Ensure Phase 2 (address import) ran successfully"
		return 1
	fi

	# Get deposit address (receiver)
	local client_addr
	client_addr=$(xrp_get_address "${CLIENT_ACCOUNT}")

	if [ -z "${client_addr}" ]; then
		log_error "No '${CLIENT_ACCOUNT}' address found in watch DB"
		return 1
	fi

	log_info "Payment address (sender):   ${payment_addr}"
	log_info "Deposit address (receiver): ${client_addr}"

	# Fund payment account (extra for multisig signer reservation)
	xrp_fund_address "${payment_addr}" "${FUNDING_AMOUNT_PAYMENT_XRP}"

	# Fund deposit account with base reserve to activate it
	xrp_fund_address "${client_addr}" "${FUNDING_AMOUNT_CLIENT_XRP}"

	log_info "Funding completed"
}

###############################################################################
# Helper: Get signer addresses
# Returns the payment address (signer1) and deposit address (signer2)
# from the watch DB. These serve as the two signers in the SignerList.
#
# NOTE: In a production multisig setup, signer addresses should be distinct
# from the sender and come from separate offline wallets (keygen + sign wallet).
# For this E2E test, we reuse the keygen wallet's generated addresses as signers
# since the sign wallet does not yet support XRP.
###############################################################################

xrp_get_signer_addresses() {
	local signer1_addr
	signer1_addr=$(xrp_get_address "${PAYMENT_ACCOUNT}")

	local signer2_addr
	signer2_addr=$(xrp_get_address "${CLIENT_ACCOUNT}")

	echo "${signer1_addr} ${signer2_addr}"
}

###############################################################################
# Phase 4: Set Signer List (Watch wallet — online)
###############################################################################

# Globals set by this phase
SIGNER_LIST_TX_FILE=""
SIGNER1_ADDR=""
SIGNER2_ADDR=""

set_signer_list_phase() {
	log_step "Signer List Setup Phase (Watch wallet)"

	# Get the payment (multisig sender) address
	local sender_addr
	sender_addr=$(xrp_get_address "${PAYMENT_ACCOUNT}")

	if [ -z "${sender_addr}" ]; then
		log_error "No payment address found — cannot set signer list"
		return 1
	fi

	# Determine signer addresses
	# Signer1: use the payment account's SECOND address from the DB
	# Signer2: use the deposit account's FIRST address from the DB
	# This avoids using the multisig sender (sender_addr) as its own signer,
	# which XRPL prohibits.
	if [ "${DB_TYPE}" = "sqlite" ]; then
		SIGNER1_ADDR=$(sqlite3 "${SQLITE_WATCH_DB_PATH}" \
			"SELECT wallet_address FROM address WHERE coin='xrp' AND account='${PAYMENT_ACCOUNT}' AND is_allocated=0 LIMIT 1 OFFSET 1" \
			2>/dev/null || true)
	fi

	# Fallback: use the deposit address as signer1 if we cannot get a second payment address
	if [ -z "${SIGNER1_ADDR}" ]; then
		SIGNER1_ADDR=$(xrp_get_address "${CLIENT_ACCOUNT}")
	fi

	# Signer2: fund a dedicated signer account from genesis (the deposit account's second address)
	if [ "${DB_TYPE}" = "sqlite" ]; then
		SIGNER2_ADDR=$(sqlite3 "${SQLITE_WATCH_DB_PATH}" \
			"SELECT wallet_address FROM address WHERE coin='xrp' AND account='${CLIENT_ACCOUNT}' AND is_allocated=0 LIMIT 1 OFFSET 1" \
			2>/dev/null || true)
	fi

	# Fallback: fund a genesis-derived signer address
	if [ -z "${SIGNER2_ADDR}" ]; then
		# Use a deterministic signer address from genesis for testing
		SIGNER2_ADDR="${XRP_GENESIS_ACCOUNT}"
	fi

	log_info "Multisig sender:   ${sender_addr}"
	log_info "Signer1 address:   ${SIGNER1_ADDR}"
	log_info "Signer2 address:   ${SIGNER2_ADDR}"

	# Fund signer accounts to activate them (required for signer list validation)
	if [ -n "${SIGNER1_ADDR}" ] && [ "${SIGNER1_ADDR}" != "${sender_addr}" ]; then
		xrp_fund_address "${SIGNER1_ADDR}" 10
	fi

	# Set the signer list on the sender account
	log_substep "Setting 2-of-2 signer list on ${sender_addr}"
	local signer_spec="${SIGNER1_ADDR}:1,${SIGNER2_ADDR}:1"
	local set_signer_output
	set_signer_output=$(xrp_watch_cmd -c "${XRP_CONFIG_WATCH}" --coin "${XRP_COIN}" \
		send multisig set-signer-list \
		--account "${sender_addr}" \
		--quorum "${MULTISIG_QUORUM}" \
		--signers "${signer_spec}" 2>&1) || {
		log_error "Failed to create SignerListSet transaction"
		log_error "Output: ${set_signer_output}"
		return 1
	}

	SIGNER_LIST_TX_FILE=$(xrp_extract_file_path "${set_signer_output}")

	if [ -z "${SIGNER_LIST_TX_FILE}" ]; then
		log_error "Failed to extract SignerListSet transaction file path"
		log_error "Output: ${set_signer_output}"
		return 1
	fi

	log_info "Unsigned SignerListSet TX: ${SIGNER_LIST_TX_FILE}"
	log_info "Signer list configuration:"
	log_info "  Quorum: ${MULTISIG_QUORUM}"
	log_info "  Signers: ${signer_spec}"
}

###############################################################################
# Phase 5: Sign the SignerListSet TX (Keygen wallet — offline)
# This uses the standard single-sig path to authorize the SignerListSet.
###############################################################################

# Globals set by this phase
SIGNED_SIGNER_LIST_TX_FILE=""

sign_signer_list_phase() {
	log_step "Sign SignerListSet TX Phase (Keygen wallet)"

	if [ -z "${SIGNER_LIST_TX_FILE}" ]; then
		log_error "SIGNER_LIST_TX_FILE is not set — run set_signer_list_phase first"
		return 1
	fi

	log_substep "Signing SignerListSet transaction: ${SIGNER_LIST_TX_FILE}"
	local sign_output
	sign_output=$(xrp_keygen_cmd -c "${XRP_CONFIG_KEYGEN}" --coin "${XRP_COIN}" sign signature \
		--file "${SIGNER_LIST_TX_FILE}" 2>&1) || {
		log_error "Failed to sign SignerListSet transaction"
		log_error "Output: ${sign_output}"
		return 1
	}

	SIGNED_SIGNER_LIST_TX_FILE=$(xrp_extract_file_path "${sign_output}")

	if [ -z "${SIGNED_SIGNER_LIST_TX_FILE}" ]; then
		log_error "Failed to extract signed SignerListSet file path"
		log_error "Output: ${sign_output}"
		return 1
	fi

	log_info "Signed SignerListSet TX: ${SIGNED_SIGNER_LIST_TX_FILE}"
}

###############################################################################
# Phase 6: Submit the SignerListSet TX (Watch wallet — online)
###############################################################################

submit_signer_list_phase() {
	log_step "Submit SignerListSet TX Phase (Watch wallet)"

	if [ -z "${SIGNED_SIGNER_LIST_TX_FILE}" ]; then
		log_error "SIGNED_SIGNER_LIST_TX_FILE is not set — run sign_signer_list_phase first"
		return 1
	fi

	log_substep "Submitting SignerListSet transaction: ${SIGNED_SIGNER_LIST_TX_FILE}"
	local send_output
	send_output=$(xrp_watch_cmd -c "${XRP_CONFIG_WATCH}" --coin "${XRP_COIN}" send tx \
		--file "${SIGNED_SIGNER_LIST_TX_FILE}" 2>&1) || {
		log_error "Failed to submit SignerListSet transaction"
		log_error "Output: ${send_output}"
		return 1
	}

	local tx_id
	tx_id=$(xrp_extract_tx_id "${send_output}")

	if [ -z "${tx_id}" ]; then
		log_warn "Could not extract txID; the SignerListSet tx may still have been submitted"
		log_info "Raw output: ${send_output}"
	else
		log_info "SignerListSet submitted! txID: ${tx_id}"
	fi

	# Advance ledger to validate the SignerListSet transaction
	log_substep "Advancing ledger to validate SignerListSet"
	xrp_ledger_accept

	log_info "SignerList configured on the payment account"
}

###############################################################################
# Phase 7: Create Multisig Payment TX (Watch wallet — online)
# Creates the unsigned multisig JSON file (--quorum 2 activates JSON format).
###############################################################################

# Globals set by this phase
UNSIGNED_MULTISIG_TX_FILE=""
PAYMENT_ADDR=""
CLIENT_ADDR=""

create_multisig_tx_phase() {
	log_step "Create Multisig Payment TX Phase (Watch wallet)"

	PAYMENT_ADDR=$(xrp_get_address "${PAYMENT_ACCOUNT}")
	CLIENT_ADDR=$(xrp_get_address "${CLIENT_ACCOUNT}")

	if [ -z "${PAYMENT_ADDR}" ] || [ -z "${CLIENT_ADDR}" ]; then
		log_error "Payment or client address not found in watch DB"
		return 1
	fi

	log_substep "Creating unsigned multisig transfer: ${PAYMENT_ACCOUNT} → ${CLIENT_ACCOUNT} (${TRANSFER_AMOUNT_XRP} XRP, quorum=${MULTISIG_QUORUM})"
	local create_output
	create_output=$(xrp_watch_cmd -c "${XRP_CONFIG_WATCH}" --coin "${XRP_COIN}" create transfer \
		--account1 "${PAYMENT_ACCOUNT}" \
		--account2 "${CLIENT_ACCOUNT}" \
		--amount "${TRANSFER_AMOUNT_XRP}" \
		--quorum "${MULTISIG_QUORUM}" 2>&1) || {
		log_error "Failed to create multisig transfer transaction"
		log_error "Output: ${create_output}"
		return 1
	}

	UNSIGNED_MULTISIG_TX_FILE=$(xrp_extract_file_path "${create_output}")

	if [ -z "${UNSIGNED_MULTISIG_TX_FILE}" ]; then
		log_error "Failed to extract unsigned multisig TX file path"
		log_error "Output: ${create_output}"
		return 1
	fi

	log_info "Unsigned multisig TX file: ${UNSIGNED_MULTISIG_TX_FILE}"

	# Validate initial JSON file structure
	xrp_assert_multisig_file "${UNSIGNED_MULTISIG_TX_FILE}" 0 false \
		"Initial file should have signatureCount=0 and isComplete=false"
}

###############################################################################
# Helper: Assert multisig JSON file state
# Usage: xrp_assert_multisig_file <file> <expected_count> <expected_complete> <message>
###############################################################################

xrp_assert_multisig_file() {
	local file="$1"
	local expected_count="$2"
	local expected_complete="$3"
	local message="$4"

	if [ ! -f "${file}" ]; then
		log_error "Assertion failed: file does not exist: ${file}"
		log_error "Context: ${message}"
		return 1
	fi

	if ! command -v jq >/dev/null 2>&1; then
		log_warn "jq not available — skipping JSON file assertions"
		return 0
	fi

	# Read the actual values from the JSON file
	local actual_count
	actual_count=$(jq -r '.transactions[0].signatureCount // 0' "${file}" 2>/dev/null || echo "0")

	local actual_complete
	actual_complete=$(jq -r '.transactions[0].isComplete // false' "${file}" 2>/dev/null || echo "false")

	local assertion_failed=false

	if [ "${actual_count}" != "${expected_count}" ]; then
		log_error "Assertion failed: signatureCount expected=${expected_count} actual=${actual_count}"
		log_error "Context: ${message}"
		assertion_failed=true
	fi

	if [ "${actual_complete}" != "${expected_complete}" ]; then
		log_error "Assertion failed: isComplete expected=${expected_complete} actual=${actual_complete}"
		log_error "Context: ${message}"
		assertion_failed=true
	fi

	if [ "${assertion_failed}" = "true" ]; then
		log_error "File: ${file}"
		return 1
	fi

	log_info "Assertion OK [${message}]: signatureCount=${actual_count}, isComplete=${actual_complete}"
}

###############################################################################
# Phase 8: Sign 1 — Keygen wallet (first signer)
#
# NOTE: The keygen wallet's sign_transaction.go uses ReadFileSlice (text format).
# The multisig JSON file created with --quorum 2 uses ReadXRPJSONFile (JSON format).
# Therefore, `keygen sign signature --file JSON_FILE` will fail with a parse error.
#
# To use the sign wallet (sign binary with sign/xrp/sign_transaction.go which supports
# JSON format), the sign wallet must first support XRP coin via NewSigner().
# This is tracked as an implementation gap.
#
# For the purposes of this E2E test, this phase documents the INTENDED command.
# When the gap is resolved, this phase will produce a partially-signed file with
# signatureCount=1 and isComplete=false.
###############################################################################

# Globals set by this phase
SIGNED_1_TX_FILE=""

sign_tx_phase_1() {
	log_step "Sign 1 Phase — First Signer (Keygen wallet)"

	if [ -z "${UNSIGNED_MULTISIG_TX_FILE}" ]; then
		log_error "UNSIGNED_MULTISIG_TX_FILE is not set — run create_multisig_tx_phase first"
		return 1
	fi

	log_substep "Sign 1: keygen wallet signing multisig JSON file: ${UNSIGNED_MULTISIG_TX_FILE}"
	log_info "  Signer: Keygen wallet (account: ${PAYMENT_ACCOUNT}, address: ${SIGNER1_ADDR:-unknown})"
	log_info "  Expected: signatureCount=1, isComplete=false after this step"

	local sign_output
	# NOTE: This command will currently fail because keygen's sign_transaction.go
	# uses ReadFileSlice (text format reader) on a JSON format file.
	# The fix requires keygen's sign use case to detect and handle JSON format files,
	# or a separate JSON-capable keygen sign command.
	sign_output=$(xrp_keygen_cmd -c "${XRP_CONFIG_KEYGEN}" --coin "${XRP_COIN}" sign signature \
		--file "${UNSIGNED_MULTISIG_TX_FILE}" 2>&1) || {
		log_warn "Sign 1 failed (known gap: keygen uses text format reader for JSON files)"
		log_warn "Output: ${sign_output}"
		log_warn "SKIPPING: Sign 1 requires keygen to support JSON format multisig files"
		log_warn "See: internal/application/usecase/keygen/xrp/sign_transaction.go"
		return 0  # Non-fatal: continue to document the workflow
	}

	SIGNED_1_TX_FILE=$(xrp_extract_file_path "${sign_output}")

	if [ -z "${SIGNED_1_TX_FILE}" ]; then
		log_warn "Failed to extract Sign 1 output file path — skipping assertion"
		return 0
	fi

	log_info "Sign 1 output file: ${SIGNED_1_TX_FILE}"

	# Assert: after Sign 1, signatureCount should be 1 and isComplete should be false
	xrp_assert_multisig_file "${SIGNED_1_TX_FILE}" 1 false \
		"After Sign 1: signatureCount=1, isComplete=false"
}

###############################################################################
# Phase 9: Sign 2 — Sign wallet (second signer)
#
# NOTE: The sign wallet (sign binary) currently returns "not implemented" for XRP
# in NewSigner (see internal/di/container.go:NewSigner). The sign/xrp/sign_transaction.go
# use case IS implemented (JSON format, signature accumulation), but is not yet
# reachable via the sign binary CLI.
#
# This phase documents the INTENDED command. When the sign wallet supports XRP,
# this phase will produce a fully-signed file with signatureCount=2 and isComplete=true.
###############################################################################

# Globals set by this phase
SIGNED_2_TX_FILE=""

sign_tx_phase_2() {
	log_step "Sign 2 Phase — Second Signer (Sign wallet)"

	local input_file="${SIGNED_1_TX_FILE:-${UNSIGNED_MULTISIG_TX_FILE}}"

	if [ -z "${input_file}" ]; then
		log_warn "No input file for Sign 2 — skipping"
		return 0
	fi

	log_substep "Sign 2: sign wallet signing partially-signed multisig JSON file: ${input_file}"
	log_info "  Signer: Sign wallet (second authorized signer)"
	log_info "  Expected: signatureCount=2, isComplete=true after this step"

	# NOTE: The sign binary does not yet support XRP (NewSigner returns error for XRP).
	# The intended command would be:
	#   sign -c config/wallet/xrp/sign.yaml --coin xrp sign signature --file INPUT_FILE
	# where sign.yaml points to a separate sign wallet DB with the second signer's key.
	#
	# For now, we document the gap and skip.
	log_warn "Sign 2 is currently not executable: sign wallet does not support XRP yet"
	log_warn "Intended command (once implemented):"
	log_warn "  sign -c config/wallet/xrp/sign.yaml --coin xrp sign signature --file ${input_file}"
	log_warn "See: internal/di/container.go:NewSigner (XRP case returns 'not implemented')"
	log_warn "See: internal/application/usecase/sign/xrp/sign_transaction.go (implementation ready)"

	return 0  # Non-fatal: continue to document the workflow
}

###############################################################################
# Phase 10: Broadcast (Watch wallet — online)
# Reads the fully-signed JSON file and submits via watch send tx.
###############################################################################

send_multisig_tx_phase() {
	log_step "Broadcast Multisig TX Phase (Watch wallet)"

	local signed_file="${SIGNED_2_TX_FILE:-${SIGNED_1_TX_FILE}}"

	if [ -z "${signed_file}" ]; then
		log_warn "No completed signed file available — signing phases were skipped"
		log_warn "Full broadcast test requires Sign 1 and Sign 2 to complete successfully"
		log_info "Skipping broadcast phase"
		return 0
	fi

	# Check if the file is complete before attempting to send
	if command -v jq >/dev/null 2>&1; then
		local is_complete
		is_complete=$(jq -r '.transactions[0].isComplete // false' "${signed_file}" 2>/dev/null || echo "false")
		if [ "${is_complete}" != "true" ]; then
			log_warn "Signed file is not yet complete (isComplete=false)"
			log_warn "Broadcast requires all ${MULTISIG_QUORUM} signatures to be collected"
			log_warn "File: ${signed_file}"
			return 0
		fi
	fi

	log_substep "Sending fully-signed multisig transaction: ${signed_file}"
	local send_output
	send_output=$(xrp_watch_cmd -c "${XRP_CONFIG_WATCH}" --coin "${XRP_COIN}" send tx \
		--file "${signed_file}" 2>&1) || {
		log_error "Failed to send multisig transaction"
		log_error "Output: ${send_output}"
		return 1
	}

	local tx_id
	tx_id=$(xrp_extract_tx_id "${send_output}")

	if [ -z "${tx_id}" ]; then
		log_warn "Could not extract txID from output; the tx may still have been sent"
		log_info "Raw output: ${send_output}"
	else
		log_info "Multisig transaction sent! txID: ${tx_id}"
	fi

	# Advance ledger to validate the transaction (required in standalone mode)
	log_substep "Advancing ledger to validate multisig transaction"
	xrp_ledger_accept
}

###############################################################################
# Phase 11: Confirmation Monitoring (Watch wallet — online)
###############################################################################

monitor_phase() {
	log_step "Monitoring Phase (Watch wallet)"

	log_substep "Monitoring sent transactions for confirmation"
	xrp_watch_cmd -c "${XRP_CONFIG_WATCH}" --coin "${XRP_COIN}" monitor senttx || {
		log_warn "Monitor returned non-zero (may be no transactions to monitor yet)"
	}

	log_info "Monitoring completed"
}

###############################################################################
# Full E2E Workflow
###############################################################################

e2e_full_workflow() {
	log_step "XRP E2E Workflow - Pattern 2: 2-of-2 Multisig Payment Transfer"
	log_info "DB type: ${DB_TYPE}"
	log_info "WS:      ws://${XRP_WS_HOST}:${XRP_WS_PORT}"
	log_info "Quorum:  ${MULTISIG_QUORUM}-of-${MULTISIG_QUORUM}"
	echo ""
	log_info "NOTE: Sign 1 and Sign 2 phases are partially implemented."
	log_info "Phases 1-7 (setup, SignerListSet, multisig TX creation) run end-to-end."
	log_info "Signing of the multisig JSON file requires additional implementation."
	log_info "See script header for details."
	echo ""

	xrp_check_prerequisites
	xrp_setup_infrastructure
	xrp_init_sqlite_db

	keygen_phase
	address_setup_phase
	funding_phase
	set_signer_list_phase
	sign_signer_list_phase
	submit_signer_list_phase
	create_multisig_tx_phase
	sign_tx_phase_1
	sign_tx_phase_2
	send_multisig_tx_phase
	monitor_phase

	echo ""
	log_info "E2E Pattern 2 completed!"
	log_info ""
	log_info "Summary of phase results:"
	log_info "  Phases 1-3 (key gen, address import, funding): COMPLETE"
	log_info "  Phase 4-6 (SignerList setup, sign, submit):    COMPLETE"
	log_info "  Phase 7   (create multisig TX JSON file):      COMPLETE"
	log_info "  Phase 8   (Sign 1 - keygen wallet):            PENDING IMPLEMENTATION"
	log_info "  Phase 9   (Sign 2 - sign wallet):              PENDING IMPLEMENTATION"
	log_info "  Phase 10  (broadcast fully-signed TX):         PENDING (depends on 8, 9)"
	log_info ""
	log_info "To complete implementation:"
	log_info "  1. Update keygen sign_transaction.go to detect and handle JSON format files"
	log_info "  2. Enable XRP in sign wallet (container.go:NewSigner)"
	log_info "  3. Create config/wallet/xrp/sign.yaml for the sign wallet"
}

###############################################################################
# Main
###############################################################################

trap 'log_error "Script failed at line $LINENO"' ERR

main() {
	case "${MODE}" in
	cleanup)
		xrp_cleanup
		;;
	reset)
		xrp_full_reset
		e2e_full_workflow
		;;
	run)
		e2e_full_workflow
		;;
	*)
		log_error "Invalid mode: ${MODE}"
		exit 1
		;;
	esac
}

main
