# Bitcoin Cash Node Configuration - Sign Wallet 2 (bch-sign2)
# Container: bch-sign2 (sign2)
# Wallet Type: Sign wallet - Offline node for multisig signing operations
# https://docs.bitcoincashnode.org/
lang=en

regtest=1
server=1

# Config options rpcuser and rpcpassword will soon be deprecated.
# Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth.
rpcuser=xyz
rpcpassword=xyz

txindex=1
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:2900

[regtest]
rpcport=18443
rpcbind=0.0.0.0
rpcallowip=10.0.0.0/8
rpcallowip=172.16.0.0/12
rpcallowip=192.168.0.0/16

