package btc

// Descriptor Service - BTC ONLY
//
// ┌─────────────────────────────────────────────────────────────────────────────┐
// │ WARNING: DO NOT USE THIS FILE FOR BCH (Bitcoin Cash) IMPLEMENTATIONS        │
// │                                                                             │
// │ BCH does NOT support output descriptors (BIP380).                           │
// │ BCH uses legacy wallet with address export/import workflow instead.         │
// │                                                                             │
// │ For BCH implementations, see:                                               │
// │   - internal/infrastructure/api/btc/bch/                                   │
// │   - docs/chains/bch/README.md                                               │
// └─────────────────────────────────────────────────────────────────────────────┘

import (
	"github.com/btcsuite/btcd/chaincfg"

	btcdescriptor "github.com/hiromaily/go-crypto-wallet/pkg/chains/btc/descriptor"
)

// DescriptorService is a thin wrapper around pkg/chains/btc/descriptor.DescriptorService
// that satisfies the DescriptorServicer interface.
//
// Note: Descriptors generated by this service do NOT include checksums.
// The watch wallet adds checksums using Bitcoin Core's getdescriptorinfo RPC before importing.
type DescriptorService = btcdescriptor.DescriptorService

// NewDescriptorService creates a descriptor service for the given Bitcoin network parameters.
func NewDescriptorService(chainParams *chaincfg.Params) *DescriptorService {
	return btcdescriptor.NewDescriptorService(chainParams)
}
