// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: address.proto

package xrp

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGenerateAddress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	XAddress       string                 `protobuf:"bytes,1,opt,name=xAddress" json:"xAddress,omitempty"`
	ClassicAddress string                 `protobuf:"bytes,2,opt,name=classicAddress" json:"classicAddress,omitempty"`
	Address        string                 `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Secret         string                 `protobuf:"bytes,4,opt,name=secret" json:"secret,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResponseGenerateAddress) Reset() {
	*x = ResponseGenerateAddress{}
	mi := &file_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGenerateAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGenerateAddress) ProtoMessage() {}

func (x *ResponseGenerateAddress) ProtoReflect() protoreflect.Message {
	mi := &file_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGenerateAddress.ProtoReflect.Descriptor instead.
func (*ResponseGenerateAddress) Descriptor() ([]byte, []int) {
	return file_address_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGenerateAddress) GetXAddress() string {
	if x != nil {
		return x.XAddress
	}
	return ""
}

func (x *ResponseGenerateAddress) GetClassicAddress() string {
	if x != nil {
		return x.ClassicAddress
	}
	return ""
}

func (x *ResponseGenerateAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ResponseGenerateAddress) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ResponseGenerateXAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XAddress      string                 `protobuf:"bytes,1,opt,name=xAddress" json:"xAddress,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGenerateXAddress) Reset() {
	*x = ResponseGenerateXAddress{}
	mi := &file_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGenerateXAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGenerateXAddress) ProtoMessage() {}

func (x *ResponseGenerateXAddress) ProtoReflect() protoreflect.Message {
	mi := &file_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGenerateXAddress.ProtoReflect.Descriptor instead.
func (*ResponseGenerateXAddress) Descriptor() ([]byte, []int) {
	return file_address_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseGenerateXAddress) GetXAddress() string {
	if x != nil {
		return x.XAddress
	}
	return ""
}

func (x *ResponseGenerateXAddress) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type RequestIsValidAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestIsValidAddress) Reset() {
	*x = RequestIsValidAddress{}
	mi := &file_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestIsValidAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestIsValidAddress) ProtoMessage() {}

func (x *RequestIsValidAddress) ProtoReflect() protoreflect.Message {
	mi := &file_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestIsValidAddress.ProtoReflect.Descriptor instead.
func (*RequestIsValidAddress) Descriptor() ([]byte, []int) {
	return file_address_proto_rawDescGZIP(), []int{2}
}

func (x *RequestIsValidAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ResponseIsValidAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=isValid" json:"isValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseIsValidAddress) Reset() {
	*x = ResponseIsValidAddress{}
	mi := &file_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseIsValidAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseIsValidAddress) ProtoMessage() {}

func (x *ResponseIsValidAddress) ProtoReflect() protoreflect.Message {
	mi := &file_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseIsValidAddress.ProtoReflect.Descriptor instead.
func (*ResponseIsValidAddress) Descriptor() ([]byte, []int) {
	return file_address_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseIsValidAddress) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_address_proto protoreflect.FileDescriptor

const file_address_proto_rawDesc = "" +
	"\n" +
	"\raddress.proto\x12\x11rippleapi.address\x1a\x1bgoogle/protobuf/empty.proto\"\x8f\x01\n" +
	"\x17ResponseGenerateAddress\x12\x1a\n" +
	"\bxAddress\x18\x01 \x01(\tR\bxAddress\x12&\n" +
	"\x0eclassicAddress\x18\x02 \x01(\tR\x0eclassicAddress\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\"N\n" +
	"\x18ResponseGenerateXAddress\x12\x1a\n" +
	"\bxAddress\x18\x01 \x01(\tR\bxAddress\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"1\n" +
	"\x15RequestIsValidAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"2\n" +
	"\x16ResponseIsValidAddress\x12\x18\n" +
	"\aisValid\x18\x01 \x01(\bR\aisValid2\xaf\x02\n" +
	"\x10RippleAddressAPI\x12W\n" +
	"\x0fGenerateAddress\x12\x16.google.protobuf.Empty\x1a*.rippleapi.address.ResponseGenerateAddress\"\x00\x12Y\n" +
	"\x10GenerateXAddress\x12\x16.google.protobuf.Empty\x1a+.rippleapi.address.ResponseGenerateXAddress\"\x00\x12g\n" +
	"\x0eIsValidAddress\x12(.rippleapi.address.RequestIsValidAddress\x1a).rippleapi.address.ResponseIsValidAddress\"\x00BFZ?github.com/hiromaily/go-crypto-wallet/pkg/infrastructure/api/ripple/xrp\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_address_proto_rawDescOnce sync.Once
	file_address_proto_rawDescData []byte
)

func file_address_proto_rawDescGZIP() []byte {
	file_address_proto_rawDescOnce.Do(func() {
		file_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_address_proto_rawDesc), len(file_address_proto_rawDesc)))
	})
	return file_address_proto_rawDescData
}

var file_address_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_address_proto_goTypes = []any{
	(*ResponseGenerateAddress)(nil),  // 0: rippleapi.address.ResponseGenerateAddress
	(*ResponseGenerateXAddress)(nil), // 1: rippleapi.address.ResponseGenerateXAddress
	(*RequestIsValidAddress)(nil),    // 2: rippleapi.address.RequestIsValidAddress
	(*ResponseIsValidAddress)(nil),   // 3: rippleapi.address.ResponseIsValidAddress
	(*emptypb.Empty)(nil),            // 4: google.protobuf.Empty
}
var file_address_proto_depIdxs = []int32{
	4, // 0: rippleapi.address.RippleAddressAPI.GenerateAddress:input_type -> google.protobuf.Empty
	4, // 1: rippleapi.address.RippleAddressAPI.GenerateXAddress:input_type -> google.protobuf.Empty
	2, // 2: rippleapi.address.RippleAddressAPI.IsValidAddress:input_type -> rippleapi.address.RequestIsValidAddress
	0, // 3: rippleapi.address.RippleAddressAPI.GenerateAddress:output_type -> rippleapi.address.ResponseGenerateAddress
	1, // 4: rippleapi.address.RippleAddressAPI.GenerateXAddress:output_type -> rippleapi.address.ResponseGenerateXAddress
	3, // 5: rippleapi.address.RippleAddressAPI.IsValidAddress:output_type -> rippleapi.address.ResponseIsValidAddress
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_address_proto_init() }
func file_address_proto_init() {
	if File_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_address_proto_rawDesc), len(file_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_address_proto_goTypes,
		DependencyIndexes: file_address_proto_depIdxs,
		MessageInfos:      file_address_proto_msgTypes,
	}.Build()
	File_address_proto = out.File
	file_address_proto_goTypes = nil
	file_address_proto_depIdxs = nil
}
