// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: eth_detail_tx.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getETHDetailTXByID = `-- name: GetETHDetailTXByID :one
SELECT id, tx_id, uuid, current_tx_type, sender_account, sender_address, receiver_account, receiver_address, amount, fee, gas_limit, nonce, unsigned_hex_tx, signed_hex_tx, sent_hash_tx, unsigned_updated_at, sent_updated_at FROM eth_detail_tx
WHERE id = ?
`

func (q *Queries) GetETHDetailTXByID(ctx context.Context, id int64) (EthDetailTx, error) {
	row := q.db.QueryRowContext(ctx, getETHDetailTXByID, id)
	var i EthDetailTx
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.Uuid,
		&i.CurrentTxType,
		&i.SenderAccount,
		&i.SenderAddress,
		&i.ReceiverAccount,
		&i.ReceiverAddress,
		&i.Amount,
		&i.Fee,
		&i.GasLimit,
		&i.Nonce,
		&i.UnsignedHexTx,
		&i.SignedHexTx,
		&i.SentHashTx,
		&i.UnsignedUpdatedAt,
		&i.SentUpdatedAt,
	)
	return i, err
}

const getETHDetailTXSentHashList = `-- name: GetETHDetailTXSentHashList :many
SELECT eth_detail_tx.sent_hash_tx
FROM eth_detail_tx
INNER JOIN tx ON tx.id = eth_detail_tx.tx_id
WHERE tx.coin = ? AND eth_detail_tx.current_tx_type = ?
`

type GetETHDetailTXSentHashListParams struct {
	Coin          TxCoin
	CurrentTxType int8
}

func (q *Queries) GetETHDetailTXSentHashList(ctx context.Context, arg GetETHDetailTXSentHashListParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getETHDetailTXSentHashList, arg.Coin, arg.CurrentTxType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sent_hash_tx string
		if err := rows.Scan(&sent_hash_tx); err != nil {
			return nil, err
		}
		items = append(items, sent_hash_tx)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getETHDetailTXsByTxID = `-- name: GetETHDetailTXsByTxID :many
SELECT id, tx_id, uuid, current_tx_type, sender_account, sender_address, receiver_account, receiver_address, amount, fee, gas_limit, nonce, unsigned_hex_tx, signed_hex_tx, sent_hash_tx, unsigned_updated_at, sent_updated_at FROM eth_detail_tx
WHERE tx_id = ?
`

func (q *Queries) GetETHDetailTXsByTxID(ctx context.Context, txID int64) ([]EthDetailTx, error) {
	rows, err := q.db.QueryContext(ctx, getETHDetailTXsByTxID, txID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EthDetailTx
	for rows.Next() {
		var i EthDetailTx
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Uuid,
			&i.CurrentTxType,
			&i.SenderAccount,
			&i.SenderAddress,
			&i.ReceiverAccount,
			&i.ReceiverAddress,
			&i.Amount,
			&i.Fee,
			&i.GasLimit,
			&i.Nonce,
			&i.UnsignedHexTx,
			&i.SignedHexTx,
			&i.SentHashTx,
			&i.UnsignedUpdatedAt,
			&i.SentUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertETHDetailTX = `-- name: InsertETHDetailTX :execresult
INSERT INTO eth_detail_tx (
  tx_id, uuid, current_tx_type, sender_account, sender_address,
  receiver_account, receiver_address, amount, fee, gas_limit, nonce,
  unsigned_hex_tx, signed_hex_tx, sent_hash_tx, unsigned_updated_at, sent_updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertETHDetailTXParams struct {
	TxID              int64
	Uuid              string
	CurrentTxType     int8
	SenderAccount     string
	SenderAddress     string
	ReceiverAccount   string
	ReceiverAddress   string
	Amount            uint64
	Fee               uint64
	GasLimit          uint32
	Nonce             uint64
	UnsignedHexTx     string
	SignedHexTx       string
	SentHashTx        string
	UnsignedUpdatedAt sql.NullTime
	SentUpdatedAt     sql.NullTime
}

func (q *Queries) InsertETHDetailTX(ctx context.Context, arg InsertETHDetailTXParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertETHDetailTX,
		arg.TxID,
		arg.Uuid,
		arg.CurrentTxType,
		arg.SenderAccount,
		arg.SenderAddress,
		arg.ReceiverAccount,
		arg.ReceiverAddress,
		arg.Amount,
		arg.Fee,
		arg.GasLimit,
		arg.Nonce,
		arg.UnsignedHexTx,
		arg.SignedHexTx,
		arg.SentHashTx,
		arg.UnsignedUpdatedAt,
		arg.SentUpdatedAt,
	)
}

const updateETHDetailTXAfterSent = `-- name: UpdateETHDetailTXAfterSent :execresult
UPDATE eth_detail_tx
SET current_tx_type = ?, signed_hex_tx = ?, sent_hash_tx = ?, sent_updated_at = ?
WHERE uuid = ?
`

type UpdateETHDetailTXAfterSentParams struct {
	CurrentTxType int8
	SignedHexTx   string
	SentHashTx    string
	SentUpdatedAt sql.NullTime
	Uuid          string
}

func (q *Queries) UpdateETHDetailTXAfterSent(ctx context.Context, arg UpdateETHDetailTXAfterSentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateETHDetailTXAfterSent,
		arg.CurrentTxType,
		arg.SignedHexTx,
		arg.SentHashTx,
		arg.SentUpdatedAt,
		arg.Uuid,
	)
}

const updateETHDetailTXType = `-- name: UpdateETHDetailTXType :execresult
UPDATE eth_detail_tx
SET current_tx_type = ?
WHERE id = ?
`

type UpdateETHDetailTXTypeParams struct {
	CurrentTxType int8
	ID            int64
}

func (q *Queries) UpdateETHDetailTXType(ctx context.Context, arg UpdateETHDetailTXTypeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateETHDetailTXType, arg.CurrentTxType, arg.ID)
}

const updateETHDetailTXTypeBySentHash = `-- name: UpdateETHDetailTXTypeBySentHash :execresult
UPDATE eth_detail_tx
SET current_tx_type = ?
WHERE sent_hash_tx = ?
`

type UpdateETHDetailTXTypeBySentHashParams struct {
	CurrentTxType int8
	SentHashTx    string
}

func (q *Queries) UpdateETHDetailTXTypeBySentHash(ctx context.Context, arg UpdateETHDetailTXTypeBySentHashParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateETHDetailTXTypeBySentHash, arg.CurrentTxType, arg.SentHashTx)
}
