// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tx.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteAllTx = `-- name: DeleteAllTx :execresult
DELETE FROM tx
`

func (q *Queries) DeleteAllTx(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAllTx)
}

const getAllTx = `-- name: GetAllTx :many
SELECT id, coin, action, updated_at FROM tx
`

func (q *Queries) GetAllTx(ctx context.Context) ([]Tx, error) {
	rows, err := q.db.QueryContext(ctx, getAllTx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tx
	for rows.Next() {
		var i Tx
		if err := rows.Scan(
			&i.ID,
			&i.Coin,
			&i.Action,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxTxID = `-- name: GetMaxTxID :one
SELECT MAX(id) as max_id FROM tx
WHERE coin = ? AND action = ?
`

type GetMaxTxIDParams struct {
	Coin   TxCoin
	Action TxAction
}

func (q *Queries) GetMaxTxID(ctx context.Context, arg GetMaxTxIDParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxTxID, arg.Coin, arg.Action)
	var max_id interface{}
	err := row.Scan(&max_id)
	return max_id, err
}

const getTxByID = `-- name: GetTxByID :one
SELECT id, coin, action, updated_at FROM tx
WHERE id = ?
`

func (q *Queries) GetTxByID(ctx context.Context, id int64) (Tx, error) {
	row := q.db.QueryRowContext(ctx, getTxByID, id)
	var i Tx
	err := row.Scan(
		&i.ID,
		&i.Coin,
		&i.Action,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTx = `-- name: InsertTx :execresult
INSERT INTO tx (coin, action, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
`

type InsertTxParams struct {
	Coin   TxCoin
	Action TxAction
}

func (q *Queries) InsertTx(ctx context.Context, arg InsertTxParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertTx, arg.Coin, arg.Action)
}

const updateTx = `-- name: UpdateTx :exec
UPDATE tx
SET coin = ?, action = ?, updated_at = ?
WHERE id = ?
`

type UpdateTxParams struct {
	Coin      TxCoin
	Action    TxAction
	UpdatedAt sql.NullTime
	ID        int64
}

func (q *Queries) UpdateTx(ctx context.Context, arg UpdateTxParams) error {
	_, err := q.db.ExecContext(ctx, updateTx,
		arg.Coin,
		arg.Action,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
