// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: xrp_signer_list.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deactivateXRPSignerListByAccountID = `-- name: DeactivateXRPSignerListByAccountID :execresult
UPDATE xrp_signer_list
SET is_active = FALSE, updated_at = ?
WHERE account_id = ? AND is_active = TRUE
`

type DeactivateXRPSignerListByAccountIDParams struct {
	UpdatedAt sql.NullTime
	AccountID string
}

func (q *Queries) DeactivateXRPSignerListByAccountID(ctx context.Context, arg DeactivateXRPSignerListByAccountIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deactivateXRPSignerListByAccountID, arg.UpdatedAt, arg.AccountID)
}

const getXRPSignerListByAccountID = `-- name: GetXRPSignerListByAccountID :one
SELECT id, account_id, signer_quorum, is_active, set_tx_hash, created_at, updated_at FROM xrp_signer_list
WHERE account_id = ? AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetXRPSignerListByAccountID(ctx context.Context, accountID string) (XrpSignerList, error) {
	row := q.db.QueryRowContext(ctx, getXRPSignerListByAccountID, accountID)
	var i XrpSignerList
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SignerQuorum,
		&i.IsActive,
		&i.SetTxHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getXRPSignerListByID = `-- name: GetXRPSignerListByID :one
SELECT id, account_id, signer_quorum, is_active, set_tx_hash, created_at, updated_at FROM xrp_signer_list
WHERE id = ?
`

func (q *Queries) GetXRPSignerListByID(ctx context.Context, id int64) (XrpSignerList, error) {
	row := q.db.QueryRowContext(ctx, getXRPSignerListByID, id)
	var i XrpSignerList
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SignerQuorum,
		&i.IsActive,
		&i.SetTxHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getXRPSignerListHistoryByAccountID = `-- name: GetXRPSignerListHistoryByAccountID :many
SELECT id, account_id, signer_quorum, is_active, set_tx_hash, created_at, updated_at FROM xrp_signer_list
WHERE account_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetXRPSignerListHistoryByAccountID(ctx context.Context, accountID string) ([]XrpSignerList, error) {
	rows, err := q.db.QueryContext(ctx, getXRPSignerListHistoryByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XrpSignerList
	for rows.Next() {
		var i XrpSignerList
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.SignerQuorum,
			&i.IsActive,
			&i.SetTxHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertXRPSignerList = `-- name: InsertXRPSignerList :execresult
INSERT INTO xrp_signer_list (
  account_id, signer_quorum, is_active, set_tx_hash, created_at
) VALUES (?, ?, ?, ?, ?)
`

type InsertXRPSignerListParams struct {
	AccountID    string
	SignerQuorum uint32
	IsActive     bool
	SetTxHash    sql.NullString
	CreatedAt    sql.NullTime
}

func (q *Queries) InsertXRPSignerList(ctx context.Context, arg InsertXRPSignerListParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertXRPSignerList,
		arg.AccountID,
		arg.SignerQuorum,
		arg.IsActive,
		arg.SetTxHash,
		arg.CreatedAt,
	)
}

const updateXRPSignerListStatus = `-- name: UpdateXRPSignerListStatus :execresult
UPDATE xrp_signer_list
SET is_active = ?, updated_at = ?
WHERE id = ?
`

type UpdateXRPSignerListStatusParams struct {
	IsActive  bool
	UpdatedAt sql.NullTime
	ID        int64
}

func (q *Queries) UpdateXRPSignerListStatus(ctx context.Context, arg UpdateXRPSignerListStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateXRPSignerListStatus, arg.IsActive, arg.UpdatedAt, arg.ID)
}

const updateXRPSignerListTxHash = `-- name: UpdateXRPSignerListTxHash :execresult
UPDATE xrp_signer_list
SET set_tx_hash = ?, updated_at = ?
WHERE id = ?
`

type UpdateXRPSignerListTxHashParams struct {
	SetTxHash sql.NullString
	UpdatedAt sql.NullTime
	ID        int64
}

func (q *Queries) UpdateXRPSignerListTxHash(ctx context.Context, arg UpdateXRPSignerListTxHashParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateXRPSignerListTxHash, arg.SetTxHash, arg.UpdatedAt, arg.ID)
}
