#!/bin/sh

# Prerequisite
# create wallet
#  $ bitcoin-cli createwallet watch
#  $ bitcoin-cli createwallet keygen
#  $ bitcoin-cli createwallet sign

# reset database and wallet if you want to start from the beginning
# $ make rm-local-wallet-dat
# $ make create-wallets

set -eu

###############################################################################
# keygen wallet
###############################################################################
# create seed
keygen create seed

# create hdkey for client, deposit, payment account
keygen create hdkey -account client -keynum 10
keygen create hdkey -account deposit -keynum 10
keygen create hdkey -account payment -keynum 10
keygen create hdkey -account stored -keynum 10

# import generated private key into keygen wallet
keygen import privkey -account client
keygen import privkey -account deposit
keygen import privkey -account payment
keygen import privkey -account stored


###############################################################################
# sign wallet
###############################################################################
# create seed
sign create seed

# create hdkey for authorization
sign -wallet sign1 create hdkey
sign2 -wallet sign2 create hdkey
sign3 -wallet sign3 create hdkey
sign4 -wallet sign4 create hdkey
sign5 -wallet sign5 create hdkey

# import generated private key into sign wallet
sign -wallet sign1 import privkey
sign2 -wallet sign2 import privkey
sign3 -wallet sign3 import privkey
sign4 -wallet sign4 import privkey
sign5 -wallet sign5 import privkey

# export full-pubkey as csv file
# sign -wallet sign1 export fullpubkey
file_fullpubkey_auth1=$(sign -wallet sign1 export fullpubkey)
file_fullpubkey_auth2=$(sign2 -wallet sign2 export fullpubkey)
file_fullpubkey_auth3=$(sign3 -wallet sign3 export fullpubkey)
file_fullpubkey_auth4=$(sign4 -wallet sign4 export fullpubkey)
file_fullpubkey_auth5=$(sign5 -wallet sign5 export fullpubkey)


###############################################################################
# keygen wallet
###############################################################################
# import full-pubkey
# keygen import fullpubkey -file ./data/pubkey/auth1_1588399093997165000.csv
keygen import fullpubkey -file ${file_fullpubkey_auth1##*\[fileName\]: }
keygen import fullpubkey -file ${file_fullpubkey_auth2##*\[fileName\]: }
keygen import fullpubkey -file ${file_fullpubkey_auth3##*\[fileName\]: }
keygen import fullpubkey -file ${file_fullpubkey_auth4##*\[fileName\]: }
keygen import fullpubkey -file ${file_fullpubkey_auth5##*\[fileName\]: }

# create multisig address
keygen create multisig -account deposit
keygen create multisig -account payment
keygen create multisig -account stored

# export address
file_address_client=$(keygen export address -account client)
file_address_deposit=$(keygen export address -account deposit)
file_address_payment=$(keygen export address -account payment)
file_address_stored=$(keygen export address -account stored)


###############################################################################
# watch only wallet
###############################################################################
# import addresses generated by keygen wallet
# if wallet.dat is deleted, rescan is required by `-rescan`
wallet import address -account client -file ${file_address_client##*\[fileName\]: }
wallet import address -account deposit -file ${file_address_deposit##*\[fileName\]: }
wallet import address -account payment -file ${file_address_payment##*\[fileName\]: }
wallet import address -account stored -file ${file_address_stored##*\[fileName\]: }
