#!/bin/sh

# Prerequisite
# create wallet
#  $ bitcoin-cli createwallet watch
#  $ bitcoin-cli createwallet keygen
#  $ bitcoin-cli createwallet sign

# reset database and wallet if you want to start from the beginning
# - reset wallet.dat
#   $ rm -rf ~/Library/Application\ Support/Bitcoin/testnet3/wallets/wallet.dat
#   $ docker-compose up btc-wallet-db btc-keygen-db btc-signature-db
# - load wallet
#	$ bitcoin-cli loadwallet watch
#	$ bitcoin-cli loadwallet keygen
#	$ bitcoin-cli loadwallet sign

set -eu

###############################################################################
# keygen wallet
###############################################################################
# create seed
keygen create seed

# create hdkey for client, receipt, payment account
keygen create hdkey -account client -keynum 10
keygen create hdkey -account receipt -keynum 10
keygen create hdkey -account payment -keynum 10
keygen create hdkey -account stored -keynum 10

# import generated private key into keygen wallet
keygen import privkey -account client
keygen import privkey -account receipt
keygen import privkey -account payment
keygen import privkey -account stored

# export created public address as csv
file_pubkey_client=$(keygen export address -account client)
file_pubkey_receipt=$(keygen export address -account receipt)
file_pubkey_payment=$(keygen export address -account payment)
file_pubkey_stored=$(keygen export address -account stored)


###############################################################################
# sign wallet
###############################################################################
# create seed
sign create seed

# create hdkey for authorization
sign create hdkey

# import generated private key into sign wallet
sign import privkey

# import pubkey exported from keygen wallet into sign wallet
#sign import address -account receipt -file ./data/pubkey/receipt_1_1586831083436291000.csv
sign import address -account receipt -file ${file_pubkey_receipt##*\[fileName\]: }
sign import address -account payment -file ${file_pubkey_payment##*\[fileName\]: }
sign import address -account stored -file ${file_pubkey_stored##*\[fileName\]: }

# generate multisig addresses
sign add multisig -account receipt
sign add multisig -account payment
sign add multisig -account stored

# export multisig address
file_multisig_receipt=$(sign export multisig -account receipt)
file_multisig_payment=$(sign export multisig -account payment)
file_multisig_stored=$(sign export multisig -account stored)


###############################################################################
# keygen wallet
###############################################################################
# import multisig address generated by sign wallet
#keygen import multisig -account receipt -file ./data/pubkey/receipt_2_1586924056349877000.csv
keygen import multisig -account receipt -file ${file_multisig_receipt##*\[fileName\]: }
keygen import multisig -account payment -file ${file_multisig_payment##*\[fileName\]: }
keygen import multisig -account stored -file ${file_multisig_stored##*\[fileName\]: }

# export addresses of multisig account for watch only wallet
file_multisig_receipt=$(keygen export multisig -account receipt)
file_multisig_payment=$(keygen export multisig -account payment)
file_multisig_stored=$(keygen export multisig -account stored)


###############################################################################
# watch only wallet
###############################################################################
# import addresses generated by keygen wallet
# if wallet.dat is deleted, rescan is required by `-rescan`
wallet import address -account client -file ${file_pubkey_client##*\[fileName\]: }
wallet import address -account receipt -file ${file_multisig_receipt##*\[fileName\]: }
wallet import address -account payment -file ${file_multisig_payment##*\[fileName\]: }
wallet import address -account stored -file ${file_multisig_stored##*\[fileName\]: }
