#!/bin/sh

#After reset database and `docker-compose up`

# reset wallet.dat
rm -rf ~/Library/Application\ Support/Bitcoin/testnet3/wallets/wallet.dat
sleep 5


###############################################################################
# keygen wallet
###############################################################################
# create seed
keygen create seed

# create hdkey for client, receipt, payment account
keygen create hdkey -account client -keynum 10
keygen create hdkey -account receipt -keynum 10
keygen create hdkey -account payment -keynum 10
keygen create hdkey -account stored -keynum 10

# import generated private key into keygen wallet
keygen import privkey -account client
keygen import privkey -account receipt
keygen import privkey -account payment
keygen import privkey -account stored

# export created public address as csv
keygen export address -account client
keygen export address -account receipt
keygen export address -account payment
keygen export address -account stored


###############################################################################
# sign wallet
###############################################################################
# create seed
sign create seed

# create hdkey for authorization
sign create hdkey

# import generated private key into sign wallet
sign import privkey

# import pubkey exported from keygen wallet into sign wallet
sign import address -account receipt -file ./data/pubkey/receipt_1_1586831083436291000.csv
sign import address -account payment -file ./data/pubkey/payment_1_1586831473462845000.csv
sign import address -account stored -file ./data/pubkey/stored_1_1586834862891724000.csv

# generate multisig addresses
sign add multisig -account receipt
sign add multisig -account payment
sign add multisig -account stored

# export multisig address
sign export multisig -account receipt
sign export multisig -account payment
sign export multisig -account stored


###############################################################################
# keygen wallet
###############################################################################
# import multisig address generated by sign wallet
keygen import multisig -account receipt -file ./data/pubkey/receipt_2_1586924056349877000.csv
keygen import multisig -account payment -file ./data/pubkey/payment_2_1586924079206568000.csv
keygen import multisig -account stored -file ./data/pubkey/stored_2_1586924095160302000.csv

# export addresses of multisig account for watch only wallet
keygen export multisig -account receipt
keygen export multisig -account payment
keygen export multisig -account stored


###############################################################################
# watch only wallet
###############################################################################
# import addresses generated by keygen wallet
# if wallet.dat is deleted, rescan is required by `-rescan`
wallet import key -account client -file ./data/pubkey/client_1_1586824834340971000.csv
wallet import key -account receipt -file ./data/pubkey/receipt_3_1586924529063261000.csv
wallet import key -account payment -file ./data/pubkey/payment_3_1586924551969624000.csv
wallet import key -account stored -file ./data/pubkey/stored_3_1586924566780575000.csv

#bitcoin-cli -rpcuser=xyz -rpcpassword=xyz getaddressinfo 2NFGyMVYxV5zw3B4xfEQTwrxv5uFEVP95mg
