// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hiromaily/go-crypto-wallet/internal/domain/chains/btc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTxOutputRepositorier creates a new instance of MockTxOutputRepositorier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxOutputRepositorier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxOutputRepositorier {
	mock := &MockTxOutputRepositorier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxOutputRepositorier is an autogenerated mock type for the TxOutputRepositorier type
type MockTxOutputRepositorier struct {
	mock.Mock
}

type MockTxOutputRepositorier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxOutputRepositorier) EXPECT() *MockTxOutputRepositorier_Expecter {
	return &MockTxOutputRepositorier_Expecter{mock: &_m.Mock}
}

// GetAllByTxID provides a mock function for the type MockTxOutputRepositorier
func (_mock *MockTxOutputRepositorier) GetAllByTxID(id int64) ([]*btc.BTCTxOutput, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByTxID")
	}

	var r0 []*btc.BTCTxOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]*btc.BTCTxOutput, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []*btc.BTCTxOutput); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*btc.BTCTxOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxOutputRepositorier_GetAllByTxID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByTxID'
type MockTxOutputRepositorier_GetAllByTxID_Call struct {
	*mock.Call
}

// GetAllByTxID is a helper method to define mock.On call
//   - id int64
func (_e *MockTxOutputRepositorier_Expecter) GetAllByTxID(id interface{}) *MockTxOutputRepositorier_GetAllByTxID_Call {
	return &MockTxOutputRepositorier_GetAllByTxID_Call{Call: _e.mock.On("GetAllByTxID", id)}
}

func (_c *MockTxOutputRepositorier_GetAllByTxID_Call) Run(run func(id int64)) *MockTxOutputRepositorier_GetAllByTxID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTxOutputRepositorier_GetAllByTxID_Call) Return(bTCTxOutputs []*btc.BTCTxOutput, err error) *MockTxOutputRepositorier_GetAllByTxID_Call {
	_c.Call.Return(bTCTxOutputs, err)
	return _c
}

func (_c *MockTxOutputRepositorier_GetAllByTxID_Call) RunAndReturn(run func(id int64) ([]*btc.BTCTxOutput, error)) *MockTxOutputRepositorier_GetAllByTxID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOne provides a mock function for the type MockTxOutputRepositorier
func (_mock *MockTxOutputRepositorier) GetOne(id int64) (*btc.BTCTxOutput, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOne")
	}

	var r0 *btc.BTCTxOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*btc.BTCTxOutput, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *btc.BTCTxOutput); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*btc.BTCTxOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxOutputRepositorier_GetOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOne'
type MockTxOutputRepositorier_GetOne_Call struct {
	*mock.Call
}

// GetOne is a helper method to define mock.On call
//   - id int64
func (_e *MockTxOutputRepositorier_Expecter) GetOne(id interface{}) *MockTxOutputRepositorier_GetOne_Call {
	return &MockTxOutputRepositorier_GetOne_Call{Call: _e.mock.On("GetOne", id)}
}

func (_c *MockTxOutputRepositorier_GetOne_Call) Run(run func(id int64)) *MockTxOutputRepositorier_GetOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTxOutputRepositorier_GetOne_Call) Return(bTCTxOutput *btc.BTCTxOutput, err error) *MockTxOutputRepositorier_GetOne_Call {
	_c.Call.Return(bTCTxOutput, err)
	return _c
}

func (_c *MockTxOutputRepositorier_GetOne_Call) RunAndReturn(run func(id int64) (*btc.BTCTxOutput, error)) *MockTxOutputRepositorier_GetOne_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockTxOutputRepositorier
func (_mock *MockTxOutputRepositorier) Insert(txItem *btc.BTCTxOutput) error {
	ret := _mock.Called(txItem)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*btc.BTCTxOutput) error); ok {
		r0 = returnFunc(txItem)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxOutputRepositorier_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockTxOutputRepositorier_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - txItem *btc.BTCTxOutput
func (_e *MockTxOutputRepositorier_Expecter) Insert(txItem interface{}) *MockTxOutputRepositorier_Insert_Call {
	return &MockTxOutputRepositorier_Insert_Call{Call: _e.mock.On("Insert", txItem)}
}

func (_c *MockTxOutputRepositorier_Insert_Call) Run(run func(txItem *btc.BTCTxOutput)) *MockTxOutputRepositorier_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *btc.BTCTxOutput
		if args[0] != nil {
			arg0 = args[0].(*btc.BTCTxOutput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTxOutputRepositorier_Insert_Call) Return(err error) *MockTxOutputRepositorier_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxOutputRepositorier_Insert_Call) RunAndReturn(run func(txItem *btc.BTCTxOutput) error) *MockTxOutputRepositorier_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertBulk provides a mock function for the type MockTxOutputRepositorier
func (_mock *MockTxOutputRepositorier) InsertBulk(txItems []*btc.BTCTxOutput) error {
	ret := _mock.Called(txItems)

	if len(ret) == 0 {
		panic("no return value specified for InsertBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*btc.BTCTxOutput) error); ok {
		r0 = returnFunc(txItems)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxOutputRepositorier_InsertBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertBulk'
type MockTxOutputRepositorier_InsertBulk_Call struct {
	*mock.Call
}

// InsertBulk is a helper method to define mock.On call
//   - txItems []*btc.BTCTxOutput
func (_e *MockTxOutputRepositorier_Expecter) InsertBulk(txItems interface{}) *MockTxOutputRepositorier_InsertBulk_Call {
	return &MockTxOutputRepositorier_InsertBulk_Call{Call: _e.mock.On("InsertBulk", txItems)}
}

func (_c *MockTxOutputRepositorier_InsertBulk_Call) Run(run func(txItems []*btc.BTCTxOutput)) *MockTxOutputRepositorier_InsertBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*btc.BTCTxOutput
		if args[0] != nil {
			arg0 = args[0].([]*btc.BTCTxOutput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTxOutputRepositorier_InsertBulk_Call) Return(err error) *MockTxOutputRepositorier_InsertBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxOutputRepositorier_InsertBulk_Call) RunAndReturn(run func(txItems []*btc.BTCTxOutput) error) *MockTxOutputRepositorier_InsertBulk_Call {
	_c.Call.Return(run)
	return _c
}
