name: docker-build-debug (without cache-mount)

# 1. use cache, Dockerfile_without_bindmount (first time):  1m 30s
# 2. use cache, Dockerfile_without_bindmount (second time): 1m 31s
# 3. not cache, Dockerfile_without_bindmount (first time):  1m 41s
# 4. not cache, Dockerfile_without_bindmount (second time): 1m 31s
# 5. use cache, Dockerfile_without_mount (first time):  1m 38s
# 6. use cache, Dockerfile_without_mount (second time): 1m 36s
# 7. not cache, Dockerfile_without_mount (first time):  1m 52s
# 8. not cache, Dockerfile_without_mount (second time): 1m 44s
# 9. use cache, Dockerfile (first time):   1m 30s
# 10. use cache, Dockerfile (second time): 1m 29s
# 11. not cache, Dockerfile (first time):  1m 14s
# 12. not cache, Dockerfile (second time): 1m 21s

on:
  workflow_dispatch:
    inputs:
      use_cache:
        description: "Use GitHub Actions Cache (true/false)"
        type: boolean
        default: true
      dockerfile:
        description: "Dockerfile path"
        type: choice
        required: true
        default: "./docker/Dockerfile"
        options:
          - "./docker/Dockerfile"
          - "./docker/Dockerfile_without_bindmount"
          - "./docker/Dockerfile_without_mount"
      # dockerfile:
      #   description: "Dockerfile path"
      #   type: string
      #   default: "./docker/Dockerfile_without_bindmount"
      run_twice:
        description: "Build twice in the same job to verify cache hits"
        type: boolean
        default: true

permissions:
  contents: read
  actions: write # for cache type=gha

env:
  DOCKERFILE: ${{ inputs.dockerfile }}
  CMD_PATH: cmd/watch
  #GHA_CACHE_SCOPE: go-crypto-wallet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (fetch tags)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # docker driver では cache-to type=gha がexportできない
      - name: Set up Buildx (docker-container driver)
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          driver: docker-container

      # First: always run
      - name: Build (first)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ${{ env.DOCKERFILE }}
          push: false
          build-args: |
            CMD_PATH=${{ env.CMD_PATH }}
          cache-from: ${{ inputs.use_cache == 'true' && format('type=gha,scope=go-{0}', hashFiles(env.DOCKERFILE, 'go.mod', 'go.sum')) || '' }}
          cache-to: ${{ inputs.use_cache == 'true' && format('type=gha,mode=max,scope=go-{0}', hashFiles(env.DOCKERFILE, 'go.mod', 'go.sum')) || '' }}
          # cache-from: type=gha,scope=go-${{ hashFiles(env.DOCKERFILE, 'go.mod', 'go.sum') }}
          # cache-to: type=gha,mode=max,scope=go-${{ hashFiles(env.DOCKERFILE, 'go.mod', 'go.sum') }}

      # Second: check how it works by cache for debugging
      - name: Build (second; should be faster if caches work)
        if: ${{ inputs.run_twice }}
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ${{ env.DOCKERFILE }}
          push: false
          build-args: |
            CMD_PATH=${{ env.CMD_PATH }}
          cache-from: ${{ inputs.use_cache == 'true' && format('type=gha,scope=go-{0}', hashFiles(env.DOCKERFILE, 'go.mod', 'go.sum')) || '' }}
          cache-to: ${{ inputs.use_cache == 'true' && format('type=gha,mode=max,scope=go-{0}', hashFiles(env.DOCKERFILE, 'go.mod', 'go.sum')) || '' }}
          # cache-from: type=gha,scope=go-${{ hashFiles(env.DOCKERFILE, 'go.mod', 'go.sum') }}
          # cache-to: type=gha,mode=max,scope=go-${{ hashFiles(env.DOCKERFILE, 'go.mod', 'go.sum') }}
