name: docker-build-debug (without cache-mount)

# 1. code not changed
# RUN go mod download: CACHED
# COPY --from=deps /src/go.sum /src/go.sum: DONE 63.0s
# RUN go build: 40s
# exporting to GitHub Actions Cache: DONE 36.2s
# 2. dockerfile go mod download position changed (combined with build)
# RUN go mod download: 13.2s
# RUN go build: 38s
# exporting to GitHub Actions Cache: DONE 92.7s

on:
  workflow_dispatch:
    inputs:
      run_twice:
        description: "Build twice in the same job to verify cache hits"
        type: boolean
        default: true

permissions:
  contents: read
  actions: write # for cache type=gha

env:
  DOCKERFILE: ./docker/Dockerfile_without_cache
  #GHA_CACHE_SCOPE: go-crypto-wallet
  CMD_PATH: cmd/watch
  APP_VERSION_VAR: main.appVersion

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (fetch tags)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # docker driver では cache-to type=gha がexportできない
      - name: Set up Buildx (docker-container driver)
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          driver: docker-container

      # First: always run
      - name: Build (first)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ${{ env.DOCKERFILE }}
          push: false
          build-args: |
            CMD_PATH=${{ env.CMD_PATH }}
            APP_VERSION_VAR=${{ env.APP_VERSION_VAR }}
          # cache-from: type=gha,scope=go-${{ hashFiles(env.DOCKERFILE, 'go.mod', 'go.sum') }}
          # cache-to: type=gha,mode=max,scope=go-${{ hashFiles(env.DOCKERFILE, 'go.mod', 'go.sum') }}

      # Second: check how it works by cache for debugging
      - name: Build (second; should be faster if caches work)
        if: ${{ inputs.run_twice }}
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ${{ env.DOCKERFILE }}
          push: false
          build-args: |
            CMD_PATH=${{ env.CMD_PATH }}
            APP_VERSION_VAR=${{ env.APP_VERSION_VAR }}
          # cache-from: type=gha,scope=go-${{ hashFiles(env.DOCKERFILE, 'go.mod', 'go.sum') }}
          # cache-to: type=gha,mode=max,scope=go-${{ hashFiles(env.DOCKERFILE, 'go.mod', 'go.sum') }}
