// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hiromaily/go-crypto-wallet/internal/domain/account"
	"github.com/hiromaily/go-crypto-wallet/internal/domain/address"
	"github.com/hiromaily/go-crypto-wallet/internal/domain/chains/btc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBTCAccountKeyRepositorier creates a new instance of MockBTCAccountKeyRepositorier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBTCAccountKeyRepositorier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBTCAccountKeyRepositorier {
	mock := &MockBTCAccountKeyRepositorier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBTCAccountKeyRepositorier is an autogenerated mock type for the BTCAccountKeyRepositorier type
type MockBTCAccountKeyRepositorier struct {
	mock.Mock
}

type MockBTCAccountKeyRepositorier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBTCAccountKeyRepositorier) EXPECT() *MockBTCAccountKeyRepositorier_Expecter {
	return &MockBTCAccountKeyRepositorier_Expecter{mock: &_m.Mock}
}

// GetAllAddrStatus provides a mock function for the type MockBTCAccountKeyRepositorier
func (_mock *MockBTCAccountKeyRepositorier) GetAllAddrStatus(accountType account.AccountType, addrStatus address.AddrStatus) ([]*btc.BTCAccountKey, error) {
	ret := _mock.Called(accountType, addrStatus)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAddrStatus")
	}

	var r0 []*btc.BTCAccountKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(account.AccountType, address.AddrStatus) ([]*btc.BTCAccountKey, error)); ok {
		return returnFunc(accountType, addrStatus)
	}
	if returnFunc, ok := ret.Get(0).(func(account.AccountType, address.AddrStatus) []*btc.BTCAccountKey); ok {
		r0 = returnFunc(accountType, addrStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*btc.BTCAccountKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(account.AccountType, address.AddrStatus) error); ok {
		r1 = returnFunc(accountType, addrStatus)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBTCAccountKeyRepositorier_GetAllAddrStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAddrStatus'
type MockBTCAccountKeyRepositorier_GetAllAddrStatus_Call struct {
	*mock.Call
}

// GetAllAddrStatus is a helper method to define mock.On call
//   - accountType account.AccountType
//   - addrStatus address.AddrStatus
func (_e *MockBTCAccountKeyRepositorier_Expecter) GetAllAddrStatus(accountType interface{}, addrStatus interface{}) *MockBTCAccountKeyRepositorier_GetAllAddrStatus_Call {
	return &MockBTCAccountKeyRepositorier_GetAllAddrStatus_Call{Call: _e.mock.On("GetAllAddrStatus", accountType, addrStatus)}
}

func (_c *MockBTCAccountKeyRepositorier_GetAllAddrStatus_Call) Run(run func(accountType account.AccountType, addrStatus address.AddrStatus)) *MockBTCAccountKeyRepositorier_GetAllAddrStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 account.AccountType
		if args[0] != nil {
			arg0 = args[0].(account.AccountType)
		}
		var arg1 address.AddrStatus
		if args[1] != nil {
			arg1 = args[1].(address.AddrStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_GetAllAddrStatus_Call) Return(bTCAccountKeys []*btc.BTCAccountKey, err error) *MockBTCAccountKeyRepositorier_GetAllAddrStatus_Call {
	_c.Call.Return(bTCAccountKeys, err)
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_GetAllAddrStatus_Call) RunAndReturn(run func(accountType account.AccountType, addrStatus address.AddrStatus) ([]*btc.BTCAccountKey, error)) *MockBTCAccountKeyRepositorier_GetAllAddrStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllMultiAddr provides a mock function for the type MockBTCAccountKeyRepositorier
func (_mock *MockBTCAccountKeyRepositorier) GetAllMultiAddr(accountType account.AccountType, addrs []string) ([]*btc.BTCAccountKey, error) {
	ret := _mock.Called(accountType, addrs)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMultiAddr")
	}

	var r0 []*btc.BTCAccountKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(account.AccountType, []string) ([]*btc.BTCAccountKey, error)); ok {
		return returnFunc(accountType, addrs)
	}
	if returnFunc, ok := ret.Get(0).(func(account.AccountType, []string) []*btc.BTCAccountKey); ok {
		r0 = returnFunc(accountType, addrs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*btc.BTCAccountKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(account.AccountType, []string) error); ok {
		r1 = returnFunc(accountType, addrs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBTCAccountKeyRepositorier_GetAllMultiAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMultiAddr'
type MockBTCAccountKeyRepositorier_GetAllMultiAddr_Call struct {
	*mock.Call
}

// GetAllMultiAddr is a helper method to define mock.On call
//   - accountType account.AccountType
//   - addrs []string
func (_e *MockBTCAccountKeyRepositorier_Expecter) GetAllMultiAddr(accountType interface{}, addrs interface{}) *MockBTCAccountKeyRepositorier_GetAllMultiAddr_Call {
	return &MockBTCAccountKeyRepositorier_GetAllMultiAddr_Call{Call: _e.mock.On("GetAllMultiAddr", accountType, addrs)}
}

func (_c *MockBTCAccountKeyRepositorier_GetAllMultiAddr_Call) Run(run func(accountType account.AccountType, addrs []string)) *MockBTCAccountKeyRepositorier_GetAllMultiAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 account.AccountType
		if args[0] != nil {
			arg0 = args[0].(account.AccountType)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_GetAllMultiAddr_Call) Return(bTCAccountKeys []*btc.BTCAccountKey, err error) *MockBTCAccountKeyRepositorier_GetAllMultiAddr_Call {
	_c.Call.Return(bTCAccountKeys, err)
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_GetAllMultiAddr_Call) RunAndReturn(run func(accountType account.AccountType, addrs []string) ([]*btc.BTCAccountKey, error)) *MockBTCAccountKeyRepositorier_GetAllMultiAddr_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxIndex provides a mock function for the type MockBTCAccountKeyRepositorier
func (_mock *MockBTCAccountKeyRepositorier) GetMaxIndex(ctx context.Context, accountType account.AccountType) (int64, error) {
	ret := _mock.Called(ctx, accountType)

	if len(ret) == 0 {
		panic("no return value specified for GetMaxIndex")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, account.AccountType) (int64, error)); ok {
		return returnFunc(ctx, accountType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, account.AccountType) int64); ok {
		r0 = returnFunc(ctx, accountType)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, account.AccountType) error); ok {
		r1 = returnFunc(ctx, accountType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBTCAccountKeyRepositorier_GetMaxIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxIndex'
type MockBTCAccountKeyRepositorier_GetMaxIndex_Call struct {
	*mock.Call
}

// GetMaxIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - accountType account.AccountType
func (_e *MockBTCAccountKeyRepositorier_Expecter) GetMaxIndex(ctx interface{}, accountType interface{}) *MockBTCAccountKeyRepositorier_GetMaxIndex_Call {
	return &MockBTCAccountKeyRepositorier_GetMaxIndex_Call{Call: _e.mock.On("GetMaxIndex", ctx, accountType)}
}

func (_c *MockBTCAccountKeyRepositorier_GetMaxIndex_Call) Run(run func(ctx context.Context, accountType account.AccountType)) *MockBTCAccountKeyRepositorier_GetMaxIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 account.AccountType
		if args[1] != nil {
			arg1 = args[1].(account.AccountType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_GetMaxIndex_Call) Return(n int64, err error) *MockBTCAccountKeyRepositorier_GetMaxIndex_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_GetMaxIndex_Call) RunAndReturn(run func(ctx context.Context, accountType account.AccountType) (int64, error)) *MockBTCAccountKeyRepositorier_GetMaxIndex_Call {
	_c.Call.Return(run)
	return _c
}

// GetOneMaxID provides a mock function for the type MockBTCAccountKeyRepositorier
func (_mock *MockBTCAccountKeyRepositorier) GetOneMaxID(accountType account.AccountType) (*btc.BTCAccountKey, error) {
	ret := _mock.Called(accountType)

	if len(ret) == 0 {
		panic("no return value specified for GetOneMaxID")
	}

	var r0 *btc.BTCAccountKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(account.AccountType) (*btc.BTCAccountKey, error)); ok {
		return returnFunc(accountType)
	}
	if returnFunc, ok := ret.Get(0).(func(account.AccountType) *btc.BTCAccountKey); ok {
		r0 = returnFunc(accountType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*btc.BTCAccountKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(account.AccountType) error); ok {
		r1 = returnFunc(accountType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBTCAccountKeyRepositorier_GetOneMaxID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOneMaxID'
type MockBTCAccountKeyRepositorier_GetOneMaxID_Call struct {
	*mock.Call
}

// GetOneMaxID is a helper method to define mock.On call
//   - accountType account.AccountType
func (_e *MockBTCAccountKeyRepositorier_Expecter) GetOneMaxID(accountType interface{}) *MockBTCAccountKeyRepositorier_GetOneMaxID_Call {
	return &MockBTCAccountKeyRepositorier_GetOneMaxID_Call{Call: _e.mock.On("GetOneMaxID", accountType)}
}

func (_c *MockBTCAccountKeyRepositorier_GetOneMaxID_Call) Run(run func(accountType account.AccountType)) *MockBTCAccountKeyRepositorier_GetOneMaxID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 account.AccountType
		if args[0] != nil {
			arg0 = args[0].(account.AccountType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_GetOneMaxID_Call) Return(bTCAccountKey *btc.BTCAccountKey, err error) *MockBTCAccountKeyRepositorier_GetOneMaxID_Call {
	_c.Call.Return(bTCAccountKey, err)
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_GetOneMaxID_Call) RunAndReturn(run func(accountType account.AccountType) (*btc.BTCAccountKey, error)) *MockBTCAccountKeyRepositorier_GetOneMaxID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertBulk provides a mock function for the type MockBTCAccountKeyRepositorier
func (_mock *MockBTCAccountKeyRepositorier) InsertBulk(items []*btc.BTCAccountKey) error {
	ret := _mock.Called(items)

	if len(ret) == 0 {
		panic("no return value specified for InsertBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*btc.BTCAccountKey) error); ok {
		r0 = returnFunc(items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBTCAccountKeyRepositorier_InsertBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertBulk'
type MockBTCAccountKeyRepositorier_InsertBulk_Call struct {
	*mock.Call
}

// InsertBulk is a helper method to define mock.On call
//   - items []*btc.BTCAccountKey
func (_e *MockBTCAccountKeyRepositorier_Expecter) InsertBulk(items interface{}) *MockBTCAccountKeyRepositorier_InsertBulk_Call {
	return &MockBTCAccountKeyRepositorier_InsertBulk_Call{Call: _e.mock.On("InsertBulk", items)}
}

func (_c *MockBTCAccountKeyRepositorier_InsertBulk_Call) Run(run func(items []*btc.BTCAccountKey)) *MockBTCAccountKeyRepositorier_InsertBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*btc.BTCAccountKey
		if args[0] != nil {
			arg0 = args[0].([]*btc.BTCAccountKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_InsertBulk_Call) Return(err error) *MockBTCAccountKeyRepositorier_InsertBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_InsertBulk_Call) RunAndReturn(run func(items []*btc.BTCAccountKey) error) *MockBTCAccountKeyRepositorier_InsertBulk_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAddr provides a mock function for the type MockBTCAccountKeyRepositorier
func (_mock *MockBTCAccountKeyRepositorier) UpdateAddr(accountType account.AccountType, addr string, keyAddress string) (int64, error) {
	ret := _mock.Called(accountType, addr, keyAddress)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAddr")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(account.AccountType, string, string) (int64, error)); ok {
		return returnFunc(accountType, addr, keyAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(account.AccountType, string, string) int64); ok {
		r0 = returnFunc(accountType, addr, keyAddress)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(account.AccountType, string, string) error); ok {
		r1 = returnFunc(accountType, addr, keyAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBTCAccountKeyRepositorier_UpdateAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAddr'
type MockBTCAccountKeyRepositorier_UpdateAddr_Call struct {
	*mock.Call
}

// UpdateAddr is a helper method to define mock.On call
//   - accountType account.AccountType
//   - addr string
//   - keyAddress string
func (_e *MockBTCAccountKeyRepositorier_Expecter) UpdateAddr(accountType interface{}, addr interface{}, keyAddress interface{}) *MockBTCAccountKeyRepositorier_UpdateAddr_Call {
	return &MockBTCAccountKeyRepositorier_UpdateAddr_Call{Call: _e.mock.On("UpdateAddr", accountType, addr, keyAddress)}
}

func (_c *MockBTCAccountKeyRepositorier_UpdateAddr_Call) Run(run func(accountType account.AccountType, addr string, keyAddress string)) *MockBTCAccountKeyRepositorier_UpdateAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 account.AccountType
		if args[0] != nil {
			arg0 = args[0].(account.AccountType)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_UpdateAddr_Call) Return(n int64, err error) *MockBTCAccountKeyRepositorier_UpdateAddr_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_UpdateAddr_Call) RunAndReturn(run func(accountType account.AccountType, addr string, keyAddress string) (int64, error)) *MockBTCAccountKeyRepositorier_UpdateAddr_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAddrStatus provides a mock function for the type MockBTCAccountKeyRepositorier
func (_mock *MockBTCAccountKeyRepositorier) UpdateAddrStatus(accountType account.AccountType, addrStatus address.AddrStatus, strWIFs []string) (int64, error) {
	ret := _mock.Called(accountType, addrStatus, strWIFs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAddrStatus")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(account.AccountType, address.AddrStatus, []string) (int64, error)); ok {
		return returnFunc(accountType, addrStatus, strWIFs)
	}
	if returnFunc, ok := ret.Get(0).(func(account.AccountType, address.AddrStatus, []string) int64); ok {
		r0 = returnFunc(accountType, addrStatus, strWIFs)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(account.AccountType, address.AddrStatus, []string) error); ok {
		r1 = returnFunc(accountType, addrStatus, strWIFs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBTCAccountKeyRepositorier_UpdateAddrStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAddrStatus'
type MockBTCAccountKeyRepositorier_UpdateAddrStatus_Call struct {
	*mock.Call
}

// UpdateAddrStatus is a helper method to define mock.On call
//   - accountType account.AccountType
//   - addrStatus address.AddrStatus
//   - strWIFs []string
func (_e *MockBTCAccountKeyRepositorier_Expecter) UpdateAddrStatus(accountType interface{}, addrStatus interface{}, strWIFs interface{}) *MockBTCAccountKeyRepositorier_UpdateAddrStatus_Call {
	return &MockBTCAccountKeyRepositorier_UpdateAddrStatus_Call{Call: _e.mock.On("UpdateAddrStatus", accountType, addrStatus, strWIFs)}
}

func (_c *MockBTCAccountKeyRepositorier_UpdateAddrStatus_Call) Run(run func(accountType account.AccountType, addrStatus address.AddrStatus, strWIFs []string)) *MockBTCAccountKeyRepositorier_UpdateAddrStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 account.AccountType
		if args[0] != nil {
			arg0 = args[0].(account.AccountType)
		}
		var arg1 address.AddrStatus
		if args[1] != nil {
			arg1 = args[1].(address.AddrStatus)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_UpdateAddrStatus_Call) Return(n int64, err error) *MockBTCAccountKeyRepositorier_UpdateAddrStatus_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_UpdateAddrStatus_Call) RunAndReturn(run func(accountType account.AccountType, addrStatus address.AddrStatus, strWIFs []string) (int64, error)) *MockBTCAccountKeyRepositorier_UpdateAddrStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMultisigAddr provides a mock function for the type MockBTCAccountKeyRepositorier
func (_mock *MockBTCAccountKeyRepositorier) UpdateMultisigAddr(accountType account.AccountType, item *btc.BTCAccountKey) (int64, error) {
	ret := _mock.Called(accountType, item)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMultisigAddr")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(account.AccountType, *btc.BTCAccountKey) (int64, error)); ok {
		return returnFunc(accountType, item)
	}
	if returnFunc, ok := ret.Get(0).(func(account.AccountType, *btc.BTCAccountKey) int64); ok {
		r0 = returnFunc(accountType, item)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(account.AccountType, *btc.BTCAccountKey) error); ok {
		r1 = returnFunc(accountType, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBTCAccountKeyRepositorier_UpdateMultisigAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMultisigAddr'
type MockBTCAccountKeyRepositorier_UpdateMultisigAddr_Call struct {
	*mock.Call
}

// UpdateMultisigAddr is a helper method to define mock.On call
//   - accountType account.AccountType
//   - item *btc.BTCAccountKey
func (_e *MockBTCAccountKeyRepositorier_Expecter) UpdateMultisigAddr(accountType interface{}, item interface{}) *MockBTCAccountKeyRepositorier_UpdateMultisigAddr_Call {
	return &MockBTCAccountKeyRepositorier_UpdateMultisigAddr_Call{Call: _e.mock.On("UpdateMultisigAddr", accountType, item)}
}

func (_c *MockBTCAccountKeyRepositorier_UpdateMultisigAddr_Call) Run(run func(accountType account.AccountType, item *btc.BTCAccountKey)) *MockBTCAccountKeyRepositorier_UpdateMultisigAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 account.AccountType
		if args[0] != nil {
			arg0 = args[0].(account.AccountType)
		}
		var arg1 *btc.BTCAccountKey
		if args[1] != nil {
			arg1 = args[1].(*btc.BTCAccountKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_UpdateMultisigAddr_Call) Return(n int64, err error) *MockBTCAccountKeyRepositorier_UpdateMultisigAddr_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_UpdateMultisigAddr_Call) RunAndReturn(run func(accountType account.AccountType, item *btc.BTCAccountKey) (int64, error)) *MockBTCAccountKeyRepositorier_UpdateMultisigAddr_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMultisigAddrs provides a mock function for the type MockBTCAccountKeyRepositorier
func (_mock *MockBTCAccountKeyRepositorier) UpdateMultisigAddrs(accountType account.AccountType, items []*btc.BTCAccountKey) (int64, error) {
	ret := _mock.Called(accountType, items)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMultisigAddrs")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(account.AccountType, []*btc.BTCAccountKey) (int64, error)); ok {
		return returnFunc(accountType, items)
	}
	if returnFunc, ok := ret.Get(0).(func(account.AccountType, []*btc.BTCAccountKey) int64); ok {
		r0 = returnFunc(accountType, items)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(account.AccountType, []*btc.BTCAccountKey) error); ok {
		r1 = returnFunc(accountType, items)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBTCAccountKeyRepositorier_UpdateMultisigAddrs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMultisigAddrs'
type MockBTCAccountKeyRepositorier_UpdateMultisigAddrs_Call struct {
	*mock.Call
}

// UpdateMultisigAddrs is a helper method to define mock.On call
//   - accountType account.AccountType
//   - items []*btc.BTCAccountKey
func (_e *MockBTCAccountKeyRepositorier_Expecter) UpdateMultisigAddrs(accountType interface{}, items interface{}) *MockBTCAccountKeyRepositorier_UpdateMultisigAddrs_Call {
	return &MockBTCAccountKeyRepositorier_UpdateMultisigAddrs_Call{Call: _e.mock.On("UpdateMultisigAddrs", accountType, items)}
}

func (_c *MockBTCAccountKeyRepositorier_UpdateMultisigAddrs_Call) Run(run func(accountType account.AccountType, items []*btc.BTCAccountKey)) *MockBTCAccountKeyRepositorier_UpdateMultisigAddrs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 account.AccountType
		if args[0] != nil {
			arg0 = args[0].(account.AccountType)
		}
		var arg1 []*btc.BTCAccountKey
		if args[1] != nil {
			arg1 = args[1].([]*btc.BTCAccountKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_UpdateMultisigAddrs_Call) Return(n int64, err error) *MockBTCAccountKeyRepositorier_UpdateMultisigAddrs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBTCAccountKeyRepositorier_UpdateMultisigAddrs_Call) RunAndReturn(run func(accountType account.AccountType, items []*btc.BTCAccountKey) (int64, error)) *MockBTCAccountKeyRepositorier_UpdateMultisigAddrs_Call {
	_c.Call.Return(run)
	return _c
}
