// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTxSender creates a new instance of MockTxSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxSender {
	mock := &MockTxSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxSender is an autogenerated mock type for the TxSender type
type MockTxSender struct {
	mock.Mock
}

type MockTxSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxSender) EXPECT() *MockTxSender_Expecter {
	return &MockTxSender_Expecter{mock: &_m.Mock}
}

// SendSignedRawTransaction provides a mock function for the type MockTxSender
func (_mock *MockTxSender) SendSignedRawTransaction(ctx context.Context, signedTxHex string) (string, error) {
	ret := _mock.Called(ctx, signedTxHex)

	if len(ret) == 0 {
		panic("no return value specified for SendSignedRawTransaction")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, signedTxHex)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, signedTxHex)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, signedTxHex)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxSender_SendSignedRawTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSignedRawTransaction'
type MockTxSender_SendSignedRawTransaction_Call struct {
	*mock.Call
}

// SendSignedRawTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - signedTxHex string
func (_e *MockTxSender_Expecter) SendSignedRawTransaction(ctx interface{}, signedTxHex interface{}) *MockTxSender_SendSignedRawTransaction_Call {
	return &MockTxSender_SendSignedRawTransaction_Call{Call: _e.mock.On("SendSignedRawTransaction", ctx, signedTxHex)}
}

func (_c *MockTxSender_SendSignedRawTransaction_Call) Run(run func(ctx context.Context, signedTxHex string)) *MockTxSender_SendSignedRawTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxSender_SendSignedRawTransaction_Call) Return(s string, err error) *MockTxSender_SendSignedRawTransaction_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTxSender_SendSignedRawTransaction_Call) RunAndReturn(run func(ctx context.Context, signedTxHex string) (string, error)) *MockTxSender_SendSignedRawTransaction_Call {
	_c.Call.Return(run)
	return _c
}
