// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockETHRawKeyImporter creates a new instance of MockETHRawKeyImporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockETHRawKeyImporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockETHRawKeyImporter {
	mock := &MockETHRawKeyImporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockETHRawKeyImporter is an autogenerated mock type for the ETHRawKeyImporter type
type MockETHRawKeyImporter struct {
	mock.Mock
}

type MockETHRawKeyImporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockETHRawKeyImporter) EXPECT() *MockETHRawKeyImporter_Expecter {
	return &MockETHRawKeyImporter_Expecter{mock: &_m.Mock}
}

// ImportRawKey provides a mock function for the type MockETHRawKeyImporter
func (_mock *MockETHRawKeyImporter) ImportRawKey(ctx context.Context, hexKey string, passPhrase string) (string, error) {
	ret := _mock.Called(ctx, hexKey, passPhrase)

	if len(ret) == 0 {
		panic("no return value specified for ImportRawKey")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, hexKey, passPhrase)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, hexKey, passPhrase)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, hexKey, passPhrase)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockETHRawKeyImporter_ImportRawKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportRawKey'
type MockETHRawKeyImporter_ImportRawKey_Call struct {
	*mock.Call
}

// ImportRawKey is a helper method to define mock.On call
//   - ctx context.Context
//   - hexKey string
//   - passPhrase string
func (_e *MockETHRawKeyImporter_Expecter) ImportRawKey(ctx interface{}, hexKey interface{}, passPhrase interface{}) *MockETHRawKeyImporter_ImportRawKey_Call {
	return &MockETHRawKeyImporter_ImportRawKey_Call{Call: _e.mock.On("ImportRawKey", ctx, hexKey, passPhrase)}
}

func (_c *MockETHRawKeyImporter_ImportRawKey_Call) Run(run func(ctx context.Context, hexKey string, passPhrase string)) *MockETHRawKeyImporter_ImportRawKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockETHRawKeyImporter_ImportRawKey_Call) Return(s string, err error) *MockETHRawKeyImporter_ImportRawKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockETHRawKeyImporter_ImportRawKey_Call) RunAndReturn(run func(ctx context.Context, hexKey string, passPhrase string) (string, error)) *MockETHRawKeyImporter_ImportRawKey_Call {
	_c.Call.Return(run)
	return _c
}
