// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMPCInboundTransport creates a new instance of MockMPCInboundTransport. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMPCInboundTransport(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMPCInboundTransport {
	mock := &MockMPCInboundTransport{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMPCInboundTransport is an autogenerated mock type for the MPCInboundTransport type
type MockMPCInboundTransport struct {
	mock.Mock
}

type MockMPCInboundTransport_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMPCInboundTransport) EXPECT() *MockMPCInboundTransport_Expecter {
	return &MockMPCInboundTransport_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockMPCInboundTransport
func (_mock *MockMPCInboundTransport) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMPCInboundTransport_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMPCInboundTransport_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockMPCInboundTransport_Expecter) Close() *MockMPCInboundTransport_Close_Call {
	return &MockMPCInboundTransport_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockMPCInboundTransport_Close_Call) Run(run func()) *MockMPCInboundTransport_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMPCInboundTransport_Close_Call) Return(err error) *MockMPCInboundTransport_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMPCInboundTransport_Close_Call) RunAndReturn(run func() error) *MockMPCInboundTransport_Close_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueOutbound provides a mock function for the type MockMPCInboundTransport
func (_mock *MockMPCInboundTransport) EnqueueOutbound(msg []byte) error {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueOutbound")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMPCInboundTransport_EnqueueOutbound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueOutbound'
type MockMPCInboundTransport_EnqueueOutbound_Call struct {
	*mock.Call
}

// EnqueueOutbound is a helper method to define mock.On call
//   - msg []byte
func (_e *MockMPCInboundTransport_Expecter) EnqueueOutbound(msg interface{}) *MockMPCInboundTransport_EnqueueOutbound_Call {
	return &MockMPCInboundTransport_EnqueueOutbound_Call{Call: _e.mock.On("EnqueueOutbound", msg)}
}

func (_c *MockMPCInboundTransport_EnqueueOutbound_Call) Run(run func(msg []byte)) *MockMPCInboundTransport_EnqueueOutbound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMPCInboundTransport_EnqueueOutbound_Call) Return(err error) *MockMPCInboundTransport_EnqueueOutbound_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMPCInboundTransport_EnqueueOutbound_Call) RunAndReturn(run func(msg []byte) error) *MockMPCInboundTransport_EnqueueOutbound_Call {
	_c.Call.Return(run)
	return _c
}

// Listen provides a mock function for the type MockMPCInboundTransport
func (_mock *MockMPCInboundTransport) Listen(ctx context.Context, listenAddr string) error {
	ret := _mock.Called(ctx, listenAddr)

	if len(ret) == 0 {
		panic("no return value specified for Listen")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, listenAddr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMPCInboundTransport_Listen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listen'
type MockMPCInboundTransport_Listen_Call struct {
	*mock.Call
}

// Listen is a helper method to define mock.On call
//   - ctx context.Context
//   - listenAddr string
func (_e *MockMPCInboundTransport_Expecter) Listen(ctx interface{}, listenAddr interface{}) *MockMPCInboundTransport_Listen_Call {
	return &MockMPCInboundTransport_Listen_Call{Call: _e.mock.On("Listen", ctx, listenAddr)}
}

func (_c *MockMPCInboundTransport_Listen_Call) Run(run func(ctx context.Context, listenAddr string)) *MockMPCInboundTransport_Listen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMPCInboundTransport_Listen_Call) Return(err error) *MockMPCInboundTransport_Listen_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMPCInboundTransport_Listen_Call) RunAndReturn(run func(ctx context.Context, listenAddr string) error) *MockMPCInboundTransport_Listen_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type MockMPCInboundTransport
func (_mock *MockMPCInboundTransport) Receive(ctx context.Context) (<-chan []byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 <-chan []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan []byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMPCInboundTransport_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockMPCInboundTransport_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMPCInboundTransport_Expecter) Receive(ctx interface{}) *MockMPCInboundTransport_Receive_Call {
	return &MockMPCInboundTransport_Receive_Call{Call: _e.mock.On("Receive", ctx)}
}

func (_c *MockMPCInboundTransport_Receive_Call) Run(run func(ctx context.Context)) *MockMPCInboundTransport_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMPCInboundTransport_Receive_Call) Return(bytesCh <-chan []byte, err error) *MockMPCInboundTransport_Receive_Call {
	_c.Call.Return(bytesCh, err)
	return _c
}

func (_c *MockMPCInboundTransport_Receive_Call) RunAndReturn(run func(ctx context.Context) (<-chan []byte, error)) *MockMPCInboundTransport_Receive_Call {
	_c.Call.Return(run)
	return _c
}
