// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"crypto/ecdsa"
	"math/big"

	"github.com/hiromaily/go-crypto-wallet/internal/domain/chains/eth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTxSigner creates a new instance of MockTxSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxSigner {
	mock := &MockTxSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxSigner is an autogenerated mock type for the TxSigner type
type MockTxSigner struct {
	mock.Mock
}

type MockTxSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxSigner) EXPECT() *MockTxSigner_Expecter {
	return &MockTxSigner_Expecter{mock: &_m.Mock}
}

// SignTxWithPrivateKey provides a mock function for the type MockTxSigner
func (_mock *MockTxSigner) SignTxWithPrivateKey(rawTx *eth.RawTx, privKey *ecdsa.PrivateKey, chainID *big.Int) (*eth.RawTx, error) {
	ret := _mock.Called(rawTx, privKey, chainID)

	if len(ret) == 0 {
		panic("no return value specified for SignTxWithPrivateKey")
	}

	var r0 *eth.RawTx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*eth.RawTx, *ecdsa.PrivateKey, *big.Int) (*eth.RawTx, error)); ok {
		return returnFunc(rawTx, privKey, chainID)
	}
	if returnFunc, ok := ret.Get(0).(func(*eth.RawTx, *ecdsa.PrivateKey, *big.Int) *eth.RawTx); ok {
		r0 = returnFunc(rawTx, privKey, chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eth.RawTx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*eth.RawTx, *ecdsa.PrivateKey, *big.Int) error); ok {
		r1 = returnFunc(rawTx, privKey, chainID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxSigner_SignTxWithPrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignTxWithPrivateKey'
type MockTxSigner_SignTxWithPrivateKey_Call struct {
	*mock.Call
}

// SignTxWithPrivateKey is a helper method to define mock.On call
//   - rawTx *eth.RawTx
//   - privKey *ecdsa.PrivateKey
//   - chainID *big.Int
func (_e *MockTxSigner_Expecter) SignTxWithPrivateKey(rawTx interface{}, privKey interface{}, chainID interface{}) *MockTxSigner_SignTxWithPrivateKey_Call {
	return &MockTxSigner_SignTxWithPrivateKey_Call{Call: _e.mock.On("SignTxWithPrivateKey", rawTx, privKey, chainID)}
}

func (_c *MockTxSigner_SignTxWithPrivateKey_Call) Run(run func(rawTx *eth.RawTx, privKey *ecdsa.PrivateKey, chainID *big.Int)) *MockTxSigner_SignTxWithPrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *eth.RawTx
		if args[0] != nil {
			arg0 = args[0].(*eth.RawTx)
		}
		var arg1 *ecdsa.PrivateKey
		if args[1] != nil {
			arg1 = args[1].(*ecdsa.PrivateKey)
		}
		var arg2 *big.Int
		if args[2] != nil {
			arg2 = args[2].(*big.Int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTxSigner_SignTxWithPrivateKey_Call) Return(v *eth.RawTx, err error) *MockTxSigner_SignTxWithPrivateKey_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockTxSigner_SignTxWithPrivateKey_Call) RunAndReturn(run func(rawTx *eth.RawTx, privKey *ecdsa.PrivateKey, chainID *big.Int) (*eth.RawTx, error)) *MockTxSigner_SignTxWithPrivateKey_Call {
	_c.Call.Return(run)
	return _c
}
