// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"crypto/ecdsa"

	mock "github.com/stretchr/testify/mock"
)

// NewMockETHKeyAccessor creates a new instance of MockETHKeyAccessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockETHKeyAccessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockETHKeyAccessor {
	mock := &MockETHKeyAccessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockETHKeyAccessor is an autogenerated mock type for the ETHKeyAccessor type
type MockETHKeyAccessor struct {
	mock.Mock
}

type MockETHKeyAccessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockETHKeyAccessor) EXPECT() *MockETHKeyAccessor_Expecter {
	return &MockETHKeyAccessor_Expecter{mock: &_m.Mock}
}

// GetKeyDir provides a mock function for the type MockETHKeyAccessor
func (_mock *MockETHKeyAccessor) GetKeyDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKeyDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockETHKeyAccessor_GetKeyDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyDir'
type MockETHKeyAccessor_GetKeyDir_Call struct {
	*mock.Call
}

// GetKeyDir is a helper method to define mock.On call
func (_e *MockETHKeyAccessor_Expecter) GetKeyDir() *MockETHKeyAccessor_GetKeyDir_Call {
	return &MockETHKeyAccessor_GetKeyDir_Call{Call: _e.mock.On("GetKeyDir")}
}

func (_c *MockETHKeyAccessor_GetKeyDir_Call) Run(run func()) *MockETHKeyAccessor_GetKeyDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockETHKeyAccessor_GetKeyDir_Call) Return(s string) *MockETHKeyAccessor_GetKeyDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockETHKeyAccessor_GetKeyDir_Call) RunAndReturn(run func() string) *MockETHKeyAccessor_GetKeyDir_Call {
	_c.Call.Return(run)
	return _c
}

// ToECDSA provides a mock function for the type MockETHKeyAccessor
func (_mock *MockETHKeyAccessor) ToECDSA(privKey string) (*ecdsa.PrivateKey, error) {
	ret := _mock.Called(privKey)

	if len(ret) == 0 {
		panic("no return value specified for ToECDSA")
	}

	var r0 *ecdsa.PrivateKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*ecdsa.PrivateKey, error)); ok {
		return returnFunc(privKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *ecdsa.PrivateKey); ok {
		r0 = returnFunc(privKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ecdsa.PrivateKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(privKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockETHKeyAccessor_ToECDSA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToECDSA'
type MockETHKeyAccessor_ToECDSA_Call struct {
	*mock.Call
}

// ToECDSA is a helper method to define mock.On call
//   - privKey string
func (_e *MockETHKeyAccessor_Expecter) ToECDSA(privKey interface{}) *MockETHKeyAccessor_ToECDSA_Call {
	return &MockETHKeyAccessor_ToECDSA_Call{Call: _e.mock.On("ToECDSA", privKey)}
}

func (_c *MockETHKeyAccessor_ToECDSA_Call) Run(run func(privKey string)) *MockETHKeyAccessor_ToECDSA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockETHKeyAccessor_ToECDSA_Call) Return(privateKey *ecdsa.PrivateKey, err error) *MockETHKeyAccessor_ToECDSA_Call {
	_c.Call.Return(privateKey, err)
	return _c
}

func (_c *MockETHKeyAccessor_ToECDSA_Call) RunAndReturn(run func(privKey string) (*ecdsa.PrivateKey, error)) *MockETHKeyAccessor_ToECDSA_Call {
	_c.Call.Return(run)
	return _c
}
