package imports

import (
	"flag"
	"fmt"

	"github.com/mitchellh/cli"

	"github.com/hiromaily/go-bitcoin/pkg/account"
	"github.com/hiromaily/go-bitcoin/pkg/wallet/wallets"
)

// MultisigCommand multisig subcommand
type MultisigCommand struct {
	name     string
	synopsis string
	ui       cli.Ui
	wallet   wallets.Signer
}

// Synopsis is explanation for this subcommand
func (c *MultisigCommand) Synopsis() string {
	return c.synopsis
}

// Help returns usage for this subcommand
func (c *MultisigCommand) Help() string {
	return `Usage: sign import address [options...]
Options:
  -file     signed transaction file path
  -account  target account
`
}

// Run executes this subcommand
func (c *MultisigCommand) Run(args []string) int {
	c.ui.Info(c.Synopsis())

	var (
		filePath string
		acnt     string
	)
	flags := flag.NewFlagSet(c.name, flag.ContinueOnError)
	flags.StringVar(&filePath, "file", "", "import file path for signed transactions")
	flags.StringVar(&acnt, "account", "", "target account")
	if err := flags.Parse(args); err != nil {
		return 1
	}

	//validator
	if filePath == "" {
		c.ui.Error("file path option [-file] is required")
		return 1
	}
	if !account.ValidateAccountType(acnt) {
		c.ui.Error("account option [-account] is invalid")
		return 1
	}
	if !account.NotAllow(acnt, []account.AccountType{account.AccountTypeAuthorization, account.AccountTypeClient}) {
		c.ui.Error(fmt.Sprintf("account: %s/%s is not allowed", account.AccountTypeAuthorization, account.AccountTypeClient))
		return 1
	}

	// import public key generated by keygen wallet to database
	err := c.wallet.ImportPubKey(filePath, account.AccountType(acnt))
	if err != nil {
		c.ui.Error(fmt.Sprintf("fail to call ImportMultisigAddress() %+v", err))
		return 1
	}
	c.ui.Output("Done!")

	return 0
}
